/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { baselinesPreviewCreateBaseline } from "../../funcs/baselinesPreviewCreateBaseline.js";
import { CreateBaselineRequest$zodSchema } from "../../models/createbaselineop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: CreateBaselineRequest$zodSchema,
};

export const tool$baselinesPreviewCreateBaseline: ToolDefinition<typeof args> =
  {
    name: "baselines-preview-create-baseline",
    description: `Create baseline

**Preview.** Available to teams with the \`baselines_api\` feature flag.

Create a baseline in the team. A baseline can target all servers, a custom set (when the
plan is not yet known), or one or more specific platforms. When it targets platforms, the
disk layout is validated by the same rules a deploy applies — against the smallest of the
selected platforms — so a baseline that saves here can be dispatched verbatim.
`,
    annotations: {
      "title": "",
      "destructiveHint": false,
      "idempotentHint": false,
      "openWorldHint": false,
      "readOnlyHint": false,
    },
    args,
    tool: async (client, args, ctx) => {
      const [result] = await baselinesPreviewCreateBaseline(
        client,
        args.request,
        { fetchOptions: { signal: ctx.signal } },
      ).$inspect();

      if (!result.ok) {
        return {
          content: [{ type: "text", text: result.error.message }],
          isError: true,
        };
      }

      return formatResult(result.value);
    },
  };
