/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { blockStoragePostStorageVolumes } from "../../funcs/blockStoragePostStorageVolumes.js";
import { PostStorageVolumesRequest$zodSchema } from "../../models/poststoragevolumesop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: PostStorageVolumesRequest$zodSchema,
};

export const tool$blockStoragePostStorageVolumes: ToolDefinition<typeof args> =
  {
    name: "block-storage-post-storage-volumes",
    description: `Create volume

Allows you to add persistent storage to a project. These volumes can be used to store data across your servers.`,
    annotations: {
      "title": "",
      "destructiveHint": false,
      "idempotentHint": false,
      "openWorldHint": false,
      "readOnlyHint": false,
    },
    args,
    tool: async (client, args, ctx) => {
      const [result] = await blockStoragePostStorageVolumes(
        client,
        args.request,
        { fetchOptions: { signal: ctx.signal } },
      ).$inspect();

      if (!result.ok) {
        return {
          content: [{ type: "text", text: result.error.message }],
          isError: true,
        };
      }

      return formatResult(result.value);
    },
  };
