/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { blockStorageGetStorageVolumes } from "../../funcs/blockStorageGetStorageVolumes.js";
import { GetStorageVolumesRequest$zodSchema } from "../../models/getstoragevolumesop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: GetStorageVolumesRequest$zodSchema.optional(),
};

export const tool$blockStorageGetStorageVolumes: ToolDefinition<typeof args> = {
  name: "block-storage-get-storage-volumes",
  description: `List volumes

Lists all the volumes from a team.`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": true,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await blockStorageGetStorageVolumes(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
