/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { elasticIpsDeleteElasticIpBgpSession } from "../../funcs/elasticIpsDeleteElasticIpBgpSession.js";
import { DeleteElasticIpBgpSessionRequest$zodSchema } from "../../models/deleteelasticipbgpsessionop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: DeleteElasticIpBgpSessionRequest$zodSchema,
};

export const tool$elasticIpsDeleteElasticIpBgpSession: ToolDefinition<
  typeof args
> = {
  name: "elastic-ips-delete-elastic-ip-bgp-session",
  description: `Delete a BGP session

Stop announcing an elastic IP from a server`,
  annotations: {
    "title": "",
    "destructiveHint": true,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await elasticIpsDeleteElasticIpBgpSession(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
