/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { filesystemStorageUpdateFilesystem } from "../../funcs/filesystemStorageUpdateFilesystem.js";
import { PatchStorageFilesystemsRequest$zodSchema } from "../../models/patchstoragefilesystemsop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: PatchStorageFilesystemsRequest$zodSchema,
};

export const tool$filesystemStorageUpdateFilesystem: ToolDefinition<
  typeof args
> = {
  name: "filesystem-storage-update-filesystem",
  description: `Update filesystem

Allow you to upgrade the size of a filesystem.`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await filesystemStorageUpdateFilesystem(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
