/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { filesystemStorageCreateFilesystem } from "../../funcs/filesystemStorageCreateFilesystem.js";
import { PostStorageFilesystemsRequest$zodSchema } from "../../models/poststoragefilesystemsop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: PostStorageFilesystemsRequest$zodSchema,
};

export const tool$filesystemStorageCreateFilesystem: ToolDefinition<
  typeof args
> = {
  name: "filesystem-storage-create-filesystem",
  description: `Create filesystem

Allows you to add persistent storage to a project. These filesystems can be used to store data across your servers.`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await filesystemStorageCreateFilesystem(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
