/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { firewallsDelete } from "../../funcs/firewallsDelete.js";
import { DeleteFirewallRequest$zodSchema } from "../../models/deletefirewallop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: DeleteFirewallRequest$zodSchema,
};

export const tool$firewallsDelete: ToolDefinition<typeof args> = {
  name: "firewalls-delete",
  description: `Delete Firewall

Delete a firewall`,
  annotations: {
    "title": "",
    "destructiveHint": true,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await firewallsDelete(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(void 0, apiCall);
  },
};
