/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { firewallsUpdate } from "../../funcs/firewallsUpdate.js";
import { UpdateFirewallRequest$zodSchema } from "../../models/updatefirewallop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: UpdateFirewallRequest$zodSchema,
};

export const tool$firewallsUpdate: ToolDefinition<typeof args> = {
  name: "firewalls-update",
  description: `Update Firewall

Update a firewall`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await firewallsUpdate(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
