/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { firewallsCreate } from "../../funcs/firewallsCreate.js";
import { CreateFirewallRequest$zodSchema } from "../../models/createfirewallop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: CreateFirewallRequest$zodSchema,
};

export const tool$firewallsCreate: ToolDefinition<typeof args> = {
  name: "firewalls-create",
  description: `Create a firewall

Create a firewall`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await firewallsCreate(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
