/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { firewallsAssignmentsCreate } from "../../funcs/firewallsAssignmentsCreate.js";
import { CreateFirewallAssignmentRequest$zodSchema } from "../../models/createfirewallassignmentop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: CreateFirewallAssignmentRequest$zodSchema,
};

export const tool$firewallsAssignmentsCreate: ToolDefinition<typeof args> = {
  name: "firewalls-assignments-create",
  description: `Assign server to firewall

Assigns a server to a firewall by its ID.`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await firewallsAssignmentsCreate(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
