/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { ipAddressesGet } from "../../funcs/ipAddressesGet.js";
import { GetIpRequest$zodSchema } from "../../models/getipop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: GetIpRequest$zodSchema,
};

export const tool$ipAddressesGet: ToolDefinition<typeof args> = {
  name: "ip-addresses-get",
  description: `Retrieve an IP

Retrieve an IP Address`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": true,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await ipAddressesGet(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
