/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { kubernetesClustersCreateKubernetesCluster } from "../../funcs/kubernetesClustersCreateKubernetesCluster.js";
import { CreateKubernetesCluster$zodSchema } from "../../models/createkubernetescluster.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: CreateKubernetesCluster$zodSchema,
};

export const tool$kubernetesClustersCreateKubernetesCluster: ToolDefinition<
  typeof args
> = {
  name: "kubernetes-clusters-create-kubernetes-cluster",
  description: `Create a Kubernetes Cluster

Creates a new managed Kubernetes cluster. The cluster will be provisioned using Cluster API (CAPI) on the Management Cluster.

**Note:** This feature requires the \`managed_k8s_clusters_api\` feature flag to be enabled for your team. Maximum of 1 cluster per project.

Cluster names must follow Kubernetes naming rules: lowercase alphanumeric characters or hyphens, must start and end with an alphanumeric character, and be at most 63 characters long.
`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await kubernetesClustersCreateKubernetesCluster(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
