/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { kubernetesClustersDeleteKubernetesCluster } from "../../funcs/kubernetesClustersDeleteKubernetesCluster.js";
import { DeleteKubernetesClusterRequest$zodSchema } from "../../models/deletekubernetesclusterop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: DeleteKubernetesClusterRequest$zodSchema,
};

export const tool$kubernetesClustersDeleteKubernetesCluster: ToolDefinition<
  typeof args
> = {
  name: "kubernetes-clusters-delete-kubernetes-cluster",
  description: `Delete a Kubernetes Cluster

Deletes a Kubernetes cluster. This action is irreversible and will destroy all cluster resources.
`,
  annotations: {
    "title": "",
    "destructiveHint": true,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await kubernetesClustersDeleteKubernetesCluster(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
