/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { lksCreateLKSNodePool } from "../../funcs/lksCreateLKSNodePool.js";
import { CreateLksNodePoolRequest$zodSchema } from "../../models/createlksnodepoolop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: CreateLksNodePoolRequest$zodSchema,
};

export const tool$lksCreateLKSNodePool: ToolDefinition<typeof args> = {
  name: "lks-create-lks-node-pool",
  description: `Create a node pool

Adds a node pool to an LKS cluster. The platform provisions \`count\` servers of \`plan\` from stock, so both fields are required.

\`kubernetes_version\` defaults to the control-plane patch and may never be newer than it. \`max_pods_per_node\` is set once, here — it cannot be changed later.
`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await lksCreateLKSNodePool(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
