/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { lksGetLKSClusterKubeconfig } from "../../funcs/lksGetLKSClusterKubeconfig.js";
import { GetLksClusterKubeconfigRequest$zodSchema } from "../../models/getlksclusterkubeconfigop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: GetLksClusterKubeconfigRequest$zodSchema,
};

export const tool$lksGetLKSClusterKubeconfig: ToolDefinition<typeof args> = {
  name: "lks-get-lks-cluster-kubeconfig",
  description: `Get the cluster kubeconfig

Returns the kubeconfig for the cluster. It only exists once the control plane is up, so this endpoint answers 409 \`NOT_READY\` while the cluster is still provisioning — poll \`GET /lks/clusters/{id}\` until \`kubeconfig_url\` is set.
`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": true,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await lksGetLKSClusterKubeconfig(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
