/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { lksGetLKSNodePool } from "../../funcs/lksGetLKSNodePool.js";
import { GetLksNodePoolRequest$zodSchema } from "../../models/getlksnodepoolop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: GetLksNodePoolRequest$zodSchema,
};

export const tool$lksGetLKSNodePool: ToolDefinition<typeof args> = {
  name: "lks-get-lks-node-pool",
  description: `Get a node pool

Retrieves a single node pool of an LKS cluster. \`ready_nodes\` reports how many of the pool's \`count\` nodes have joined the cluster.
`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": true,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await lksGetLKSNodePool(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
