/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { managedDatabasesUpdateManagedDatabase } from "../../funcs/managedDatabasesUpdateManagedDatabase.js";
import { UpdateManagedDatabaseRequest$zodSchema } from "../../models/updatemanageddatabaseop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: UpdateManagedDatabaseRequest$zodSchema,
};

export const tool$managedDatabasesUpdateManagedDatabase: ToolDefinition<
  typeof args
> = {
  name: "managed-databases-update-managed-database",
  description: `Update a managed database`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await managedDatabasesUpdateManagedDatabase(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
