/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { objectStoragePostStorageBuckets } from "../../funcs/objectStoragePostStorageBuckets.js";
import { PostStorageBucketsRequest$zodSchema } from "../../models/poststoragebucketsop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: PostStorageBucketsRequest$zodSchema,
};

export const tool$objectStoragePostStorageBuckets: ToolDefinition<typeof args> =
  {
    name: "object-storage-post-storage-buckets",
    description: `Create bucket

Creates a new object storage bucket for a project.`,
    annotations: {
      "title": "",
      "destructiveHint": false,
      "idempotentHint": false,
      "openWorldHint": false,
      "readOnlyHint": false,
    },
    args,
    tool: async (client, args, ctx) => {
      const [result] = await objectStoragePostStorageBuckets(
        client,
        args.request,
        { fetchOptions: { signal: ctx.signal } },
      ).$inspect();

      if (!result.ok) {
        return {
          content: [{ type: "text", text: result.error.message }],
          isError: true,
        };
      }

      return formatResult(result.value);
    },
  };
