/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { objectStorageGetStorageUsage } from "../../funcs/objectStorageGetStorageUsage.js";
import { GetStorageUsageRequest$zodSchema } from "../../models/getstorageusageop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: GetStorageUsageRequest$zodSchema,
};

export const tool$objectStorageGetStorageUsage: ToolDefinition<typeof args> = {
  name: "object-storage-get-storage-usage",
  description: `List storage usage

Returns daily object storage usage for a project. Each row reports the canonical usage in bytes for a single storage on a given day, plus the provider-reported raw value.
`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": true,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await objectStorageGetStorageUsage(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
