/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { objectStorageGetStorageBucketLifecycleRules } from "../../funcs/objectStorageGetStorageBucketLifecycleRules.js";
import { GetStorageBucketLifecycleRulesRequest$zodSchema } from "../../models/getstoragebucketlifecyclerulesop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: GetStorageBucketLifecycleRulesRequest$zodSchema,
};

export const tool$objectStorageGetStorageBucketLifecycleRules: ToolDefinition<
  typeof args
> = {
  name: "object-storage-get-storage-bucket-lifecycle-rules",
  description: `List lifecycle rules

Lists all lifecycle rules for a specific object storage bucket.`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": true,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await objectStorageGetStorageBucketLifecycleRules(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
