/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { privateNetworksDeleteAssignment } from "../../funcs/privateNetworksDeleteAssignment.js";
import { DeleteVirtualNetworksAssignmentsRequest$zodSchema } from "../../models/deletevirtualnetworksassignmentsop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: DeleteVirtualNetworksAssignmentsRequest$zodSchema,
};

export const tool$privateNetworksDeleteAssignment: ToolDefinition<typeof args> =
  {
    name: "private-networks-delete-assignment",
    description: `Delete Virtual Network Assignment

Allow you to remove a Virtual Network assignment.
`,
    annotations: {
      "title": "",
      "destructiveHint": true,
      "idempotentHint": false,
      "openWorldHint": false,
      "readOnlyHint": false,
    },
    args,
    tool: async (client, args, ctx) => {
      const [result, apiCall] = await privateNetworksDeleteAssignment(
        client,
        args.request,
        { fetchOptions: { signal: ctx.signal } },
      ).$inspect();

      if (!result.ok) {
        return {
          content: [{ type: "text", text: result.error.message }],
          isError: true,
        };
      }

      return formatResult(void 0, apiCall);
    },
  };
