/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { projectsUpdate } from "../../funcs/projectsUpdate.js";
import { UpdateProjectRequest$zodSchema } from "../../models/updateprojectop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: UpdateProjectRequest$zodSchema,
};

export const tool$projectsUpdate: ToolDefinition<typeof args> = {
  name: "projects-update",
  description: `Update a Project`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await projectsUpdate(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
