/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { projectsGetProject } from "../../funcs/projectsGetProject.js";
import { GetProjectRequest$zodSchema } from "../../models/getprojectop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: GetProjectRequest$zodSchema,
};

export const tool$projectsGetProject: ToolDefinition<typeof args> = {
  name: "projects-get-project",
  description: `Retrieve project

Returns a single project belonging to the current team
`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": true,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await projectsGetProject(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
