/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { publicNetworksCreatePublicNetwork } from "../../funcs/publicNetworksCreatePublicNetwork.js";
import { CreatePublicNetwork$zodSchema } from "../../models/createpublicnetwork.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: CreatePublicNetwork$zodSchema,
};

export const tool$publicNetworksCreatePublicNetwork: ToolDefinition<
  typeof args
> = {
  name: "public-networks-create-public-network",
  description: `Create a network

Provision a customer network: an IPv4 block of the chosen size plus a paired IPv6 /64. The network is allocated synchronously and returned in the response; billing is settled in the background.`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await publicNetworksCreatePublicNetwork(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
