/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { publicNetworksGetPublicNetworks } from "../../funcs/publicNetworksGetPublicNetworks.js";
import { GetPublicNetworksRequest$zodSchema } from "../../models/getpublicnetworksop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: GetPublicNetworksRequest$zodSchema.optional(),
};

export const tool$publicNetworksGetPublicNetworks: ToolDefinition<typeof args> =
  {
    name: "public-networks-get-public-networks",
    description: `List networks

List the customer networks owned by the team`,
    annotations: {
      "title": "",
      "destructiveHint": false,
      "idempotentHint": false,
      "openWorldHint": false,
      "readOnlyHint": true,
    },
    args,
    tool: async (client, args, ctx) => {
      const [result] = await publicNetworksGetPublicNetworks(
        client,
        args.request,
        { fetchOptions: { signal: ctx.signal } },
      ).$inspect();

      if (!result.ok) {
        return {
          content: [{ type: "text", text: result.error.message }],
          isError: true,
        };
      }

      return formatResult(result.value);
    },
  };
