/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { regionsFetch } from "../../funcs/regionsFetch.js";
import { GetRegionRequest$zodSchema } from "../../models/getregionop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: GetRegionRequest$zodSchema,
};

export const tool$regionsFetch: ToolDefinition<typeof args> = {
  name: "regions-fetch",
  description: `Retrieve a Region`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": true,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await regionsFetch(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
