/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { rolesGet } from "../../funcs/rolesGet.js";
import { GetRoleIdRequest$zodSchema } from "../../models/getroleidop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: GetRoleIdRequest$zodSchema,
};

export const tool$rolesGet: ToolDefinition<typeof args> = {
  name: "roles-get",
  description: `Retrieve Role`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": true,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await rolesGet(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
