/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { serversGet } from "../../funcs/serversGet.js";
import { GetServerRequest$zodSchema } from "../../models/getserverop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: GetServerRequest$zodSchema,
};

export const tool$serversGet: ToolDefinition<typeof args> = {
  name: "servers-get",
  description: `Retrieve a Server

Returns a server that belongs to the team.
`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": true,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await serversGet(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
