/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { serversUpdate } from "../../funcs/serversUpdate.js";
import { UpdateServerRequest$zodSchema } from "../../models/updateserverop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: UpdateServerRequest$zodSchema,
};

export const tool$serversUpdate: ToolDefinition<typeof args> = {
  name: "servers-update",
  description: `Update Server`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await serversUpdate(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
