/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { serversList } from "../../funcs/serversList.js";
import { GetServersRequest$zodSchema } from "../../models/getserversop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: GetServersRequest$zodSchema.optional(),
};

export const tool$serversList: ToolDefinition<typeof args> = {
  name: "servers-list",
  description: `List all Servers

Returns a list of all servers belonging to the team.
`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": true,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await serversList(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
