/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { serversCreateIpmiSession } from "../../funcs/serversCreateIpmiSession.js";
import { CreateIpmiSessionRequest$zodSchema } from "../../models/createipmisessionop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: CreateIpmiSessionRequest$zodSchema,
};

export const tool$serversCreateIpmiSession: ToolDefinition<typeof args> = {
  name: "servers-create-ipmi-session",
  description: `Generate IPMI credentials

Generates IPMI credentials for a given server. Remote access creates a VPN connection to the internal network of your server so you can connect to its IPMI.
You will have to use a VPN client such as https://openvpn.net to connect. See \`VPN Sessions\` API to create a VPN connection.

Related guide: https://docs.latitude.sh/docs/ipmi
`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await serversCreateIpmiSession(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
