/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { serversGetOutOfBand } from "../../funcs/serversGetOutOfBand.js";
import { GetServerOutOfBandRequest$zodSchema } from "../../models/getserveroutofbandop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: GetServerOutOfBandRequest$zodSchema,
};

export const tool$serversGetOutOfBand: ToolDefinition<typeof args> = {
  name: "servers-get-out-of-band",
  description: `List out-of-band connections`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": true,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await serversGetOutOfBand(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
