/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { serversLock } from "../../funcs/serversLock.js";
import { ServerLockRequest$zodSchema } from "../../models/serverlockop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: ServerLockRequest$zodSchema,
};

export const tool$serversLock: ToolDefinition<typeof args> = {
  name: "servers-lock",
  description: `Lock the server

Locks the server. A locked server cannot be deleted or modified and no actions can be performed on it.`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await serversLock(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
