/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { sshKeysRetrieve } from "../../funcs/sshKeysRetrieve.js";
import { GetSshKeyRequest$zodSchema } from "../../models/getsshkeyop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: GetSshKeyRequest$zodSchema,
};

export const tool$sshKeysRetrieve: ToolDefinition<typeof args> = {
  name: "SSH-keys-retrieve",
  description: `Retrieve a SSH Key

List all SSH Keys in the project. These keys can be used to access servers after deploy and reinstall actions.
`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": true,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await sshKeysRetrieve(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
