/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { sshKeysRemoveFromProject } from "../../funcs/sshKeysRemoveFromProject.js";
import { DeleteProjectSshKeyRequest$zodSchema } from "../../models/deleteprojectsshkeyop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: DeleteProjectSshKeyRequest$zodSchema,
};

export const tool$sshKeysRemoveFromProject: ToolDefinition<typeof args> = {
  name: "SSH-keys-remove-from-project",
  description: `Delete a Project SSH Key

Allow you remove SSH Keys in a project. Remove a SSH Key from the project won't revoke the SSH Keys access for previously deploy and reinstall actions.
`,
  annotations: {
    "title": "",
    "destructiveHint": true,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await sshKeysRemoveFromProject(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(void 0, apiCall);
  },
};
