/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { storageDeleteStorageVolumes } from "../../funcs/storageDeleteStorageVolumes.js";
import { DeleteStorageVolumesRequest$zodSchema } from "../../models/deletestoragevolumesop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: DeleteStorageVolumesRequest$zodSchema,
};

export const tool$storageDeleteStorageVolumes: ToolDefinition<typeof args> = {
  name: "storage-delete-storage-volumes",
  description: `Delete volume

Allows you to remove persistent storage from a project.`,
  annotations: {
    "title": "",
    "destructiveHint": true,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await storageDeleteStorageVolumes(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(void 0, apiCall);
  },
};
