/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { tagsUpdate } from "../../funcs/tagsUpdate.js";
import { UpdateTagRequest$zodSchema } from "../../models/updatetagop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: UpdateTagRequest$zodSchema,
};

export const tool$tagsUpdate: ToolDefinition<typeof args> = {
  name: "tags-update",
  description: `Update Tag

Update a Tag in the team.
`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await tagsUpdate(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
