/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { userDataList } from "../../funcs/userDataList.js";
import { GetUsersDataRequest$zodSchema } from "../../models/getusersdataop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: GetUsersDataRequest$zodSchema.optional(),
};

export const tool$userDataList: ToolDefinition<typeof args> = {
  name: "user-data-list",
  description: `List all User Data

List all Users Data in the project. These scripts can be used to configure servers with user data.
`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": true,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await userDataList(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
