/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { virtualMachineBackupsList } from "../../funcs/virtualMachineBackupsList.js";
import { formatResult, ToolDefinition } from "../tools.js";

export const tool$virtualMachineBackupsList: ToolDefinition = {
  name: "virtual-machine-backups-list",
  description: `List all VM backups

Lists every backup that belongs to the authenticated team.
`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": true,
  },
  tool: async (client, ctx) => {
    const [result] = await virtualMachineBackupsList(
      client,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
