/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { virtualMachinesDestroyVirtualMachineNetworkAttachment } from "../../funcs/virtualMachinesDestroyVirtualMachineNetworkAttachment.js";
import { DestroyVirtualMachineNetworkAttachmentRequest$zodSchema } from "../../models/destroyvirtualmachinenetworkattachmentop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: DestroyVirtualMachineNetworkAttachmentRequest$zodSchema,
};

export const tool$virtualMachinesDestroyVirtualMachineNetworkAttachment:
  ToolDefinition<typeof args> = {
    name: "virtual-machines-destroy-network-attachment",
    description: `Detach a network from a VM

Detaches a virtual network (VLAN) from a Virtual Machine. Work runs asynchronously and returns 202 Accepted.
`,
    annotations: {
      "title": "",
      "destructiveHint": false,
      "idempotentHint": false,
      "openWorldHint": false,
      "readOnlyHint": false,
    },
    args,
    tool: async (client, args, ctx) => {
      const [result] =
        await virtualMachinesDestroyVirtualMachineNetworkAttachment(
          client,
          args.request,
          { fetchOptions: { signal: ctx.signal } },
        ).$inspect();

      if (!result.ok) {
        return {
          content: [{ type: "text", text: result.error.message }],
          isError: true,
        };
      }

      return formatResult(result.value);
    },
  };
