/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { virtualMachineBackupsDelete } from "../../funcs/virtualMachineBackupsDelete.js";
import { DeleteVirtualMachineBackupRequest$zodSchema } from "../../models/deletevirtualmachinebackupop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: DeleteVirtualMachineBackupRequest$zodSchema,
};

export const tool$virtualMachineBackupsDelete: ToolDefinition<typeof args> = {
  name: "virtual-machine-backups-delete",
  description: `Delete VM backup

Archives and deletes a Virtual Machine backup. Work runs asynchronously and returns 202 Accepted. Only \`Ready\` or \`Failed\` backups can be deleted, and not while a restore from the backup is in progress.
`,
  annotations: {
    "title": "",
    "destructiveHint": true,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await virtualMachineBackupsDelete(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
