/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { virtualMachinesList } from "../../funcs/virtualMachinesList.js";
import { IndexVirtualMachineRequest$zodSchema } from "../../models/indexvirtualmachineop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: IndexVirtualMachineRequest$zodSchema.optional(),
};

export const tool$virtualMachinesList: ToolDefinition<typeof args> = {
  name: "virtual-machines-list",
  description: `Get Teams Virtual Machines

Show all Team's Virtual Machines.
`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": true,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await virtualMachinesList(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(void 0, apiCall);
  },
};
