/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { virtualMachineRestoresListForBackup } from "../../funcs/virtualMachineRestoresListForBackup.js";
import { ListBackupRestoresRequest$zodSchema } from "../../models/listbackuprestoresop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: ListBackupRestoresRequest$zodSchema,
};

export const tool$virtualMachineRestoresListForBackup: ToolDefinition<
  typeof args
> = {
  name: "virtual-machine-restores-list-for-backup",
  description: `List a backup's restores (top-level backup path)

Lists the restores created from the given backup, reached via the top-level backup path.
`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": true,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await virtualMachineRestoresListForBackup(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
