/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { virtualMachinesGet } from "../../funcs/virtualMachinesGet.js";
import { ShowVirtualMachineRequest$zodSchema } from "../../models/showvirtualmachineop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: ShowVirtualMachineRequest$zodSchema,
};

export const tool$virtualMachinesGet: ToolDefinition<typeof args> = {
  name: "virtual-machines-get",
  description: `Get a Virtual Machine

Show a Virtual Machine.
`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": true,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await virtualMachinesGet(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(void 0, apiCall);
  },
};
