/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { virtualMachineBackupsListForVirtualMachine } from "../../funcs/virtualMachineBackupsListForVirtualMachine.js";
import { ListVirtualMachineScopedBackupsRequest$zodSchema } from "../../models/listvirtualmachinescopedbackupsop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: ListVirtualMachineScopedBackupsRequest$zodSchema,
};

export const tool$virtualMachineBackupsListForVirtualMachine: ToolDefinition<
  typeof args
> = {
  name: "virtual-machine-backups-list-for-virtual-machine",
  description: `List a VM's backups

Lists the backups of the given Virtual Machine.
`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": true,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await virtualMachineBackupsListForVirtualMachine(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
