/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { virtualMachinesCreate } from "../../funcs/virtualMachinesCreate.js";
import { VirtualMachinePayload$zodSchema } from "../../models/virtualmachinepayload.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: VirtualMachinePayload$zodSchema,
};

export const tool$virtualMachinesCreate: ToolDefinition<typeof args> = {
  name: "virtual-machines-create",
  description: `Create a Virtual Machine

Creates a new Virtual Machine.
`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await virtualMachinesCreate(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
