/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { virtualMachineRestoresList } from "../../funcs/virtualMachineRestoresList.js";
import { formatResult, ToolDefinition } from "../tools.js";

export const tool$virtualMachineRestoresList: ToolDefinition = {
  name: "virtual-machine-restores-list",
  description: `List all VM restores

Lists every restore that belongs to the authenticated team.
`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": true,
  },
  tool: async (client, ctx) => {
    const [result] = await virtualMachineRestoresList(
      client,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
