/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { virtualMachineRestoresCreateForVirtualMachineBackup } from "../../funcs/virtualMachineRestoresCreateForVirtualMachineBackup.js";
import { CreateVirtualMachineRestoreRequest$zodSchema } from "../../models/createvirtualmachinerestoreop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: CreateVirtualMachineRestoreRequest$zodSchema,
};

export const tool$virtualMachineRestoresCreateForVirtualMachineBackup:
  ToolDefinition<typeof args> = {
    name: "virtual-machine-restores-create-for-virtual-e98",
    description: `Create VM restore

Restores a backup into a new Virtual Machine. Optionally accepts a \`name\` for the restored VM and a target \`site\` slug to restore into another region.
`,
    annotations: {
      "title": "",
      "destructiveHint": false,
      "idempotentHint": false,
      "openWorldHint": false,
      "readOnlyHint": false,
    },
    args,
    tool: async (client, args, ctx) => {
      const [result] =
        await virtualMachineRestoresCreateForVirtualMachineBackup(
          client,
          args.request,
          { fetchOptions: { signal: ctx.signal } },
        ).$inspect();

      if (!result.ok) {
        return {
          content: [{ type: "text", text: result.error.message }],
          isError: true,
        };
      }

      return formatResult(result.value);
    },
  };
