/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { virtualMachineBackupsGet } from "../../funcs/virtualMachineBackupsGet.js";
import { GetVirtualMachineBackupRequest$zodSchema } from "../../models/getvirtualmachinebackupop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: GetVirtualMachineBackupRequest$zodSchema,
};

export const tool$virtualMachineBackupsGet: ToolDefinition<typeof args> = {
  name: "virtual-machine-backups-get",
  description: `Get VM backup`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": true,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await virtualMachineBackupsGet(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
