/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ApiKey, ApiKey$zodSchema } from "./apikey.js";

export type ApiKeysMeta = {};

export const ApiKeysMeta$zodSchema: z.ZodType<ApiKeysMeta> = z.object({});

export type ApiKeys = {
  data?: Array<ApiKey> | undefined;
  meta?: ApiKeysMeta | undefined;
};

export const ApiKeys$zodSchema: z.ZodType<ApiKeys> = z.object({
  data: z.array(ApiKey$zodSchema).optional(),
  meta: z.lazy(() => ApiKeysMeta$zodSchema).optional(),
});
