/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  BandwidthPlanData,
  BandwidthPlanData$zodSchema,
} from "./bandwidthplandata.js";
import { PaginationMeta, PaginationMeta$zodSchema } from "./paginationmeta.js";

export type BandwidthPlans = {
  data?: Array<BandwidthPlanData> | undefined;
  meta?: PaginationMeta | undefined;
};

export const BandwidthPlans$zodSchema: z.ZodType<BandwidthPlans> = z.object({
  data: z.array(BandwidthPlanData$zodSchema).optional(),
  meta: PaginationMeta$zodSchema.optional(),
});
