/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { BaselineData, BaselineData$zodSchema } from "./baselinedata.js";

export type BaselinesMeta = {};

export const BaselinesMeta$zodSchema: z.ZodType<BaselinesMeta> = z.object({});

export type Baselines = {
  data?: Array<BaselineData> | undefined;
  meta?: BaselinesMeta | undefined;
};

export const Baselines$zodSchema: z.ZodType<Baselines> = z.object({
  data: z.array(BaselineData$zodSchema).optional(),
  meta: z.lazy(() => BaselinesMeta$zodSchema).optional(),
});
