/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

/**
 * Purpose of the disk group
 */
export const BaselineDiskLayoutGroupRole = {
  Os: "os",
  Storage: "storage",
  Raw: "raw",
} as const;
/**
 * Purpose of the disk group
 */
export type BaselineDiskLayoutGroupRole = ClosedEnum<
  typeof BaselineDiskLayoutGroupRole
>;

export const BaselineDiskLayoutGroupRole$zodSchema = z.enum([
  "os",
  "storage",
  "raw",
]).describe("Purpose of the disk group");

/**
 * RAID level for the group. Only valid for the 'os' and 'storage' roles
 */
export const BaselineDiskLayoutGroupRaidLevel = {
  Raid0: "raid-0",
  Raid1: "raid-1",
} as const;
/**
 * RAID level for the group. Only valid for the 'os' and 'storage' roles
 */
export type BaselineDiskLayoutGroupRaidLevel = ClosedEnum<
  typeof BaselineDiskLayoutGroupRaidLevel
>;

export const BaselineDiskLayoutGroupRaidLevel$zodSchema = z.enum([
  "raid-0",
  "raid-1",
]).describe(
  "RAID level for the group. Only valid for the 'os' and 'storage' roles",
);

/**
 * Filesystem to format the group with. Only valid for the 'storage' role
 */
export const BaselineDiskLayoutGroupFilesystem = {
  Ext4: "ext4",
} as const;
/**
 * Filesystem to format the group with. Only valid for the 'storage' role
 */
export type BaselineDiskLayoutGroupFilesystem = ClosedEnum<
  typeof BaselineDiskLayoutGroupFilesystem
>;

export const BaselineDiskLayoutGroupFilesystem$zodSchema = z.enum([
  "ext4",
]).describe(
  "Filesystem to format the group with. Only valid for the 'storage' role",
);

export type BaselineDiskLayoutGroup = {
  role?: BaselineDiskLayoutGroupRole | undefined;
  count?: number | undefined;
  raid_level?: BaselineDiskLayoutGroupRaidLevel | null | undefined;
  filesystem?: BaselineDiskLayoutGroupFilesystem | null | undefined;
  mount_point?: string | null | undefined;
};

export const BaselineDiskLayoutGroup$zodSchema: z.ZodType<
  BaselineDiskLayoutGroup
> = z.object({
  count: z.int().optional().describe("Number of disks in the group"),
  filesystem: BaselineDiskLayoutGroupFilesystem$zodSchema.nullable().optional()
    .describe(
      "Filesystem to format the group with. Only valid for the 'storage' role",
    ),
  mount_point: z.string().nullable().optional().describe(
    "Where the group is mounted. Required for the 'storage' role",
  ),
  raid_level: BaselineDiskLayoutGroupRaidLevel$zodSchema.nullable().optional()
    .describe(
      "RAID level for the group. Only valid for the 'os' and 'storage' roles",
    ),
  role: BaselineDiskLayoutGroupRole$zodSchema.optional().describe(
    "Purpose of the disk group",
  ),
});
