/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { BaselineData, BaselineData$zodSchema } from "./baselinedata.js";

export type BaselineMeta = {};

export const BaselineMeta$zodSchema: z.ZodType<BaselineMeta> = z.object({});

export type Baseline = {
  data?: BaselineData | undefined;
  meta?: BaselineMeta | undefined;
};

export const Baseline$zodSchema: z.ZodType<Baseline> = z.object({
  data: BaselineData$zodSchema.optional(),
  meta: z.lazy(() => BaselineMeta$zodSchema).optional(),
});
