/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { BgpSessionData, BgpSessionData$zodSchema } from "./bgpsessiondata.js";

export type BgpSessions = { data?: Array<BgpSessionData> | undefined };

export const BgpSessions$zodSchema: z.ZodType<BgpSessions> = z.object({
  data: z.array(BgpSessionData$zodSchema).optional(),
});
