/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

/**
 * Type of discount (percentage or fixed amount)
 */
export const BillingUsageType = {
  Percent: "percent",
  Amount: "amount",
} as const;
/**
 * Type of discount (percentage or fixed amount)
 */
export type BillingUsageType = ClosedEnum<typeof BillingUsageType>;

export const BillingUsageType$zodSchema = z.enum([
  "percent",
  "amount",
]).describe("Type of discount (percentage or fixed amount)");

export const BillingUsageUnit = {
  Quantity: "quantity",
  Hour: "hour",
  Minute: "minute",
  Gb: "GB",
} as const;
export type BillingUsageUnit = ClosedEnum<typeof BillingUsageUnit>;

export const BillingUsageUnit$zodSchema = z.enum([
  "quantity",
  "hour",
  "minute",
  "GB",
]);

export const UsageType = {
  Licensed: "licensed",
  Metered: "metered",
} as const;
export type UsageType = ClosedEnum<typeof UsageType>;

export const UsageType$zodSchema = z.enum([
  "licensed",
  "metered",
]);

export type BillingUsageMeta = {};

export const BillingUsageMeta$zodSchema: z.ZodType<BillingUsageMeta> = z.object(
  {},
);

/**
 * The project in which the returned usage belongs to
 */
export type BillingUsageProject = {
  id?: string | undefined;
  slug?: string | undefined;
  name?: string | undefined;
};

export const BillingUsageProject$zodSchema: z.ZodType<BillingUsageProject> = z
  .object({
    id: z.string().optional(),
    name: z.string().optional(),
    slug: z.string().optional(),
  }).describe("The project in which the returned usage belongs to");

/**
 * The period from the returned billing cycle
 */
export type Period = { start?: string | undefined; end?: string | undefined };

export const Period$zodSchema: z.ZodType<Period> = z.object({
  end: z.iso.datetime({ offset: true }).optional(),
  start: z.iso.datetime({ offset: true }).optional(),
}).describe("The period from the returned billing cycle");

export type Discount = {
  description: string;
  type: BillingUsageType;
  value: number;
};

export const Discount$zodSchema: z.ZodType<Discount> = z.object({
  description: z.string().describe("Description of the discount"),
  type: BillingUsageType$zodSchema.describe(
    "Type of discount (percentage or fixed amount)",
  ),
  value: z.number().describe("Value of the discount (percentage or amount)"),
});

export type BillingUsageServer = {
  id?: string | undefined;
  hostname?: string | undefined;
  plan?: string | undefined;
  tags?: Array<string> | undefined;
};

export const BillingUsageServer$zodSchema: z.ZodType<BillingUsageServer> = z
  .object({
    hostname: z.string().optional(),
    id: z.string().optional(),
    plan: z.string().optional(),
    tags: z.array(z.string()).optional(),
  });

export type Bucket = {
  id?: string | undefined;
  name?: string | undefined;
  location?: string | null | undefined;
};

export const Bucket$zodSchema: z.ZodType<Bucket> = z.object({
  id: z.string().optional(),
  location: z.string().nullable().optional(),
  name: z.string().optional(),
});

export type Metadata = {
  servers?: Array<BillingUsageServer> | undefined;
  bucket?: Bucket | undefined;
  billing_unit_divisor?: number | null | undefined;
};

export const Metadata$zodSchema: z.ZodType<Metadata> = z.object({
  billing_unit_divisor: z.int().nullable().optional().describe(
    "For products priced per divided unit (e.g. $0.01 per 1000 API calls), the divisor applied to the quantity before pricing. Omitted for products that are not priced by divided units.",
  ),
  bucket: z.lazy(() => Bucket$zodSchema).optional(),
  servers: z.array(z.lazy(() => BillingUsageServer$zodSchema)).optional(),
});

export type Product = {
  id?: string | undefined;
  resource?: string | undefined;
  name?: string | undefined;
  proration?: boolean | undefined;
  discounts?: Array<Discount> | undefined;
  discountable?: boolean | undefined;
  description?: string | undefined;
  amount_without_discount?: number | undefined;
  start?: string | undefined;
  end?: string | null | undefined;
  unit?: BillingUsageUnit | undefined;
  unit_amount?: number | undefined;
  unit_price?: number | undefined;
  usage_type?: UsageType | undefined;
  quantity?: number | undefined;
  amount?: number | undefined;
  price?: number | undefined;
  metadata?: Metadata | undefined;
};

export const Product$zodSchema: z.ZodType<Product> = z.object({
  amount: z.number().optional().describe(
    "The total usage amount of the product in cents",
  ),
  amount_without_discount: z.int().optional(),
  description: z.string().optional(),
  discountable: z.boolean().optional(),
  discounts: z.array(z.lazy(() => Discount$zodSchema)).optional(),
  end: z.iso.datetime({ offset: true }).nullable().optional(),
  id: z.string().optional(),
  metadata: z.lazy(() => Metadata$zodSchema).optional(),
  name: z.string().optional(),
  price: z.number().optional().describe(
    "The total usage price of the product in cents",
  ),
  proration: z.boolean().optional(),
  quantity: z.number().optional(),
  resource: z.string().optional(),
  start: z.iso.datetime({ offset: true }).optional(),
  unit: BillingUsageUnit$zodSchema.optional(),
  unit_amount: z.number().optional().describe(
    "The unit amount of the product in cents",
  ),
  unit_price: z.number().optional().describe(
    "The unit price of the product in cents",
  ),
  usage_type: UsageType$zodSchema.optional(),
});

export type BillingUsageAttributes = {
  project?: BillingUsageProject | undefined;
  period?: Period | undefined;
  available_credit_balance?: number | undefined;
  amount?: number | undefined;
  price?: number | undefined;
  threshold?: number | null | undefined;
  products?: Array<Product> | undefined;
};

export const BillingUsageAttributes$zodSchema: z.ZodType<
  BillingUsageAttributes
> = z.object({
  amount: z.number().optional().describe("The total usage amount in cents"),
  available_credit_balance: z.int().optional().describe(
    "The available credit balance in cents",
  ),
  period: z.lazy(() => Period$zodSchema).optional().describe(
    "The period from the returned billing cycle",
  ),
  price: z.number().optional().describe("The total usage price in cents"),
  products: z.array(z.lazy(() => Product$zodSchema)).optional(),
  project: z.lazy(() => BillingUsageProject$zodSchema).optional().describe(
    "The project in which the returned usage belongs to",
  ),
  threshold: z.number().nullable().optional().describe(
    "The threshold which we use to charge your usage, in cents",
  ),
});

export type BillingUsageData = {
  id?: string | undefined;
  type?: string | undefined;
  attributes?: BillingUsageAttributes | undefined;
};

export const BillingUsageData$zodSchema: z.ZodType<BillingUsageData> = z.object(
  {
    attributes: z.lazy(() => BillingUsageAttributes$zodSchema).optional(),
    id: z.string().optional(),
    type: z.string().optional(),
  },
);

export type BillingUsage = {
  meta?: BillingUsageMeta | undefined;
  data?: BillingUsageData | undefined;
};

export const BillingUsage$zodSchema: z.ZodType<BillingUsage> = z.object({
  data: z.lazy(() => BillingUsageData$zodSchema).optional(),
  meta: z.lazy(() => BillingUsageMeta$zodSchema).optional(),
});
