/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";
import { CustomTag, CustomTag$zodSchema } from "./customtag.js";
import { ErrorObject, ErrorObject$zodSchema } from "./errorobject.js";

export const CreateTagType2 = {
  Tags: "tags",
} as const;
export type CreateTagType2 = ClosedEnum<typeof CreateTagType2>;

export const CreateTagType2$zodSchema = z.enum([
  "tags",
]);

export type CreateTagAttributes2 = {
  name?: string | undefined;
  description?: string | null | undefined;
  color?: string | undefined;
};

export const CreateTagAttributes2$zodSchema: z.ZodType<CreateTagAttributes2> = z
  .object({
    color: z.string().default("#ffffff").describe("Color of the Tag"),
    description: z.string().nullable().optional().describe(
      "Description of the Tag",
    ),
    name: z.string().optional().describe("Name of the Tag"),
  });

export type CreateTagData2 = {
  type?: CreateTagType2 | undefined;
  attributes?: CreateTagAttributes2 | undefined;
};

export const CreateTagData2$zodSchema: z.ZodType<CreateTagData2> = z.object({
  attributes: z.lazy(() => CreateTagAttributes2$zodSchema).optional(),
  type: CreateTagType2$zodSchema.optional(),
});

export type CreateTagRequest = { data?: CreateTagData2 | undefined };

export const CreateTagRequest$zodSchema: z.ZodType<CreateTagRequest> = z.object(
  {
    data: z.lazy(() => CreateTagData2$zodSchema).optional(),
  },
);

export type CreateTagResponse = CustomTag | ErrorObject;

export const CreateTagResponse$zodSchema: z.ZodType<CreateTagResponse> = z
  .union([
    CustomTag$zodSchema,
    ErrorObject$zodSchema,
  ]);
