/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { VirtualMachine, VirtualMachine$zodSchema } from "./virtualmachine.js";

export type CreateVirtualMachineResponse = {
  ContentType: string;
  StatusCode: number;
  RawResponse: Response;
  virtual_machine?: VirtualMachine | undefined;
};

export const CreateVirtualMachineResponse$zodSchema: z.ZodType<
  CreateVirtualMachineResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  ContentType: z.string(),
  RawResponse: z.instanceof(Response),
  StatusCode: z.number().int(),
  virtual_machine: VirtualMachine$zodSchema.optional(),
});
