/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ErrorObject, ErrorObject$zodSchema } from "./errorobject.js";
import {
  VirtualMachineBackup,
  VirtualMachineBackup$zodSchema,
} from "./virtualmachinebackup.js";

export type CreateVirtualMachineBackupRequest = { virtual_machine_id: string };

export const CreateVirtualMachineBackupRequest$zodSchema: z.ZodType<
  CreateVirtualMachineBackupRequest
> = z.object({
  virtual_machine_id: z.string(),
});

export type CreateVirtualMachineBackupResponse =
  | VirtualMachineBackup
  | ErrorObject;

export const CreateVirtualMachineBackupResponse$zodSchema: z.ZodType<
  CreateVirtualMachineBackupResponse
> = z.union([
  VirtualMachineBackup$zodSchema,
  ErrorObject$zodSchema,
]);
