/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

export const CreateLksClusterType = {
  LksClusters: "lks_clusters",
} as const;
export type CreateLksClusterType = ClosedEnum<typeof CreateLksClusterType>;

export const CreateLksClusterType$zodSchema = z.enum([
  "lks_clusters",
]);

/**
 * Optional network overrides; platform defaults used if omitted
 */
export type CreateLksClusterNetwork = {
  pod_cidrs?: Array<string> | undefined;
  service_cidrs?: Array<string> | undefined;
  node_cidrs?: Array<string> | undefined;
};

export const CreateLksClusterNetwork$zodSchema: z.ZodType<
  CreateLksClusterNetwork
> = z.object({
  node_cidrs: z.array(z.string()).optional(),
  pod_cidrs: z.array(z.string()).optional(),
  service_cidrs: z.array(z.string()).optional(),
}).describe("Optional network overrides; platform defaults used if omitted");

export type CreateLksClusterAttributes = {
  name: string;
  project_id: string;
  site: string;
  kubernetes_version: string;
  description?: string | undefined;
  network?: CreateLksClusterNetwork | null | undefined;
};

export const CreateLksClusterAttributes$zodSchema: z.ZodType<
  CreateLksClusterAttributes
> = z.object({
  description: z.string().optional().describe("Optional customer description"),
  kubernetes_version: z.string().describe(
    "Kubernetes patch, exactly as listed by /lks/available_versions",
  ),
  name: z.string().describe("Display name for the cluster"),
  network: z.lazy(() => CreateLksClusterNetwork$zodSchema).nullable().optional()
    .describe("Optional network overrides; platform defaults used if omitted"),
  project_id: z.string().describe("The project ID"),
  site: z.string().describe("Site slug (single site per cluster)"),
});

export type CreateLksClusterData = {
  type: CreateLksClusterType;
  attributes: CreateLksClusterAttributes;
};

export const CreateLksClusterData$zodSchema: z.ZodType<CreateLksClusterData> = z
  .object({
    attributes: z.lazy(() => CreateLksClusterAttributes$zodSchema),
    type: CreateLksClusterType$zodSchema,
  });

export type CreateLksCluster = { data: CreateLksClusterData };

export const CreateLksCluster$zodSchema: z.ZodType<CreateLksCluster> = z.object(
  {
    data: z.lazy(() => CreateLksClusterData$zodSchema),
  },
);
