/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";
import { ErrorObject, ErrorObject$zodSchema } from "./errorobject.js";
import { FilesystemData, FilesystemData$zodSchema } from "./filesystemdata.js";

export const CreateFilesystemType2 = {
  Filesystems: "filesystems",
} as const;
export type CreateFilesystemType2 = ClosedEnum<typeof CreateFilesystemType2>;

export const CreateFilesystemType2$zodSchema = z.enum([
  "filesystems",
]);

export const CreateFilesystemProtocol2 = {
  Nfs3: "nfs3",
  Nfs4: "nfs4",
} as const;
export type CreateFilesystemProtocol2 = ClosedEnum<
  typeof CreateFilesystemProtocol2
>;

export const CreateFilesystemProtocol2$zodSchema = z.enum([
  "nfs3",
  "nfs4",
]);

export type CreateFilesystemAttributes2 = {
  project: string;
  name: string;
  region: string;
  size_in_gb?: number | undefined;
  protocols: Array<CreateFilesystemProtocol2>;
};

export const CreateFilesystemAttributes2$zodSchema: z.ZodType<
  CreateFilesystemAttributes2
> = z.object({
  name: z.string().describe(
    "Filesystem name. \"block\" is reserved and cannot be used.",
  ),
  project: z.string().describe("Project ID or slug"),
  protocols: z.array(CreateFilesystemProtocol2$zodSchema).describe(
    "NFS protocol version(s) to mount the filesystem with. Case-insensitive. Pass both nfs3 and nfs4 to allow either protocol.",
  ),
  region: z.string().describe(
    "Region (site) slug where the filesystem is provisioned. Required for high performance file storage; an unknown slug is rejected with INVALID_REGION.",
  ),
  size_in_gb: z.int().default(1500).describe(
    "Size in GB (not required, default is 1500)",
  ),
});

export type CreateFilesystemData2 = {
  type: CreateFilesystemType2;
  attributes: CreateFilesystemAttributes2;
};

export const CreateFilesystemData2$zodSchema: z.ZodType<CreateFilesystemData2> =
  z.object({
    attributes: z.lazy(() => CreateFilesystemAttributes2$zodSchema),
    type: CreateFilesystemType2$zodSchema,
  });

export type CreateFilesystemRequest = { data: CreateFilesystemData2 };

export const CreateFilesystemRequest$zodSchema: z.ZodType<
  CreateFilesystemRequest
> = z.object({
  data: z.lazy(() => CreateFilesystemData2$zodSchema),
});

/**
 * Created
 */
export type CreateFilesystemResponseBody = {
  data?: FilesystemData | undefined;
};

export const CreateFilesystemResponseBody$zodSchema: z.ZodType<
  CreateFilesystemResponseBody
> = z.object({
  data: FilesystemData$zodSchema.optional(),
}).describe("Created");

export type CreateFilesystemResponse =
  | CreateFilesystemResponseBody
  | ErrorObject;

export const CreateFilesystemResponse$zodSchema: z.ZodType<
  CreateFilesystemResponse
> = z.union([
  z.lazy(() => CreateFilesystemResponseBody$zodSchema),
  ErrorObject$zodSchema,
]);
