/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { Firewall, Firewall$zodSchema } from "./firewall.js";

export const CreateFirewallType2$zodSchema = z.enum([
  "firewalls",
]);

export type CreateFirewallType2 = z.infer<typeof CreateFirewallType2$zodSchema>;

export const CreateFirewallProtocol2$zodSchema = z.enum([
  "TCP",
  "UDP",
]);

export type CreateFirewallProtocol2 = z.infer<
  typeof CreateFirewallProtocol2$zodSchema
>;

export type CreateFirewallRule2 = {
  from?: string | undefined;
  to?: string | undefined;
  protocol?: CreateFirewallProtocol2 | undefined;
  port?: string | undefined;
};

export const CreateFirewallRule2$zodSchema: z.ZodType<
  CreateFirewallRule2,
  z.ZodTypeDef,
  unknown
> = z.object({
  from: z.string().optional(),
  port: z.string().optional(),
  protocol: CreateFirewallProtocol2$zodSchema.optional(),
  to: z.string().optional(),
});

export type CreateFirewallAttributes2 = {
  name: string;
  project: string;
  rules?: Array<CreateFirewallRule2> | undefined;
};

export const CreateFirewallAttributes2$zodSchema: z.ZodType<
  CreateFirewallAttributes2,
  z.ZodTypeDef,
  unknown
> = z.object({
  name: z.string(),
  project: z.string(),
  rules: z.array(z.lazy(() => CreateFirewallRule2$zodSchema)).optional(),
});

export type CreateFirewallData2 = {
  type: CreateFirewallType2;
  attributes?: CreateFirewallAttributes2 | undefined;
};

export const CreateFirewallData2$zodSchema: z.ZodType<
  CreateFirewallData2,
  z.ZodTypeDef,
  unknown
> = z.object({
  attributes: z.lazy(() => CreateFirewallAttributes2$zodSchema).optional(),
  type: CreateFirewallType2$zodSchema,
});

export type CreateFirewallRequest = { data: CreateFirewallData2 };

export const CreateFirewallRequest$zodSchema: z.ZodType<
  CreateFirewallRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  data: z.lazy(() => CreateFirewallData2$zodSchema),
});

export type CreateFirewallResponse = {
  ContentType: string;
  StatusCode: number;
  RawResponse: Response;
  firewall?: Firewall | undefined;
};

export const CreateFirewallResponse$zodSchema: z.ZodType<
  CreateFirewallResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  ContentType: z.string(),
  RawResponse: z.instanceof(Response),
  StatusCode: z.number().int(),
  firewall: Firewall$zodSchema.optional(),
});
