/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ErrorObject, ErrorObject$zodSchema } from "./errorobject.js";
import {
  VirtualMachineRestore,
  VirtualMachineRestore$zodSchema,
} from "./virtualmachinerestore.js";
import {
  VirtualMachineRestorePayload,
  VirtualMachineRestorePayload$zodSchema,
} from "./virtualmachinerestorepayload.js";

export type CreateVirtualMachineRestoreRequest = {
  virtual_machine_id: string;
  backup_id: string;
  virtual_machine_restore_payload?: VirtualMachineRestorePayload | undefined;
};

export const CreateVirtualMachineRestoreRequest$zodSchema: z.ZodType<
  CreateVirtualMachineRestoreRequest
> = z.object({
  backup_id: z.string(),
  virtual_machine_id: z.string(),
  virtual_machine_restore_payload: VirtualMachineRestorePayload$zodSchema
    .optional(),
});

export type CreateVirtualMachineRestoreResponse =
  | VirtualMachineRestore
  | ErrorObject;

export const CreateVirtualMachineRestoreResponse$zodSchema: z.ZodType<
  CreateVirtualMachineRestoreResponse
> = z.union([
  VirtualMachineRestore$zodSchema,
  ErrorObject$zodSchema,
]);
