/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";
import {
  LksNodePoolTaint,
  LksNodePoolTaint$zodSchema,
} from "./lksnodepooltaint.js";

export const CreateLksNodePoolType = {
  LksNodePools: "lks_node_pools",
} as const;
export type CreateLksNodePoolType = ClosedEnum<typeof CreateLksNodePoolType>;

export const CreateLksNodePoolType$zodSchema = z.enum([
  "lks_node_pools",
]);

export const TypeBareMetal = {
  BareMetal: "bare_metal",
} as const;
export type TypeBareMetal = ClosedEnum<typeof TypeBareMetal>;

export const TypeBareMetal$zodSchema = z.enum([
  "bare_metal",
]);

export type CreateLksNodePoolAttributes = {
  type?: TypeBareMetal | undefined;
  plan: string;
  count: number;
  kubernetes_version?: string | undefined;
  max_pods_per_node?: number | undefined;
  name?: string | undefined;
  description?: string | undefined;
  labels?: { [k: string]: string } | undefined;
  taints?: Array<LksNodePoolTaint> | undefined;
};

export const CreateLksNodePoolAttributes$zodSchema: z.ZodType<
  CreateLksNodePoolAttributes
> = z.object({
  count: z.int().describe("Number of nodes; must be >= 1"),
  description: z.string().optional(),
  kubernetes_version: z.string().optional().describe(
    "Patch; defaults to the cluster control-plane patch. Must not be newer than the control-plane patch (422 VERSION_SKEW)",
  ),
  labels: z.record(z.string(), z.string()).optional().describe(
    "Kubernetes labels (max 50). Keys use Kubernetes label-key syntax; reserved prefixes (kubernetes.io, k8s.io, cluster.x-k8s.io, lks.latitude.sh and their subdomains) are rejected with 422. Values may be empty. The whole map is stored as sent.",
  ),
  max_pods_per_node: z.int().optional().describe(
    "kubelet --max-pods for every node in the pool. Set once, at creation: it is immutable afterwards and a PATCH that carries it is rejected with 422. Omit to get the platform default (110).",
  ),
  name: z.string().optional().describe("Optional; generated when omitted"),
  plan: z.string().describe("Plan the pool nodes are provisioned from"),
  taints: z.array(LksNodePoolTaint$zodSchema).optional().describe(
    "Kubernetes taints (max 50). Each (key, effect) pair must be unique. Key follows the same syntax and reserved-prefix rules as a label key.",
  ),
  type: TypeBareMetal$zodSchema.optional(),
});

export type CreateLksNodePoolData = {
  type: CreateLksNodePoolType;
  attributes: CreateLksNodePoolAttributes;
};

export const CreateLksNodePoolData$zodSchema: z.ZodType<CreateLksNodePoolData> =
  z.object({
    attributes: z.lazy(() => CreateLksNodePoolAttributes$zodSchema),
    type: CreateLksNodePoolType$zodSchema,
  });

export type CreateLksNodePool = { data: CreateLksNodePoolData };

export const CreateLksNodePool$zodSchema: z.ZodType<CreateLksNodePool> = z
  .object({
    data: z.lazy(() => CreateLksNodePoolData$zodSchema),
  });
