/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { TeamInclude, TeamInclude$zodSchema } from "./teaminclude.js";

export const CustomTagDataType$zodSchema = z.enum([
  "tags",
]);

export type CustomTagDataType = z.infer<typeof CustomTagDataType$zodSchema>;

export type CustomTagDataAttributes = {
  name?: string | undefined;
  slug?: string | undefined;
  description?: string | undefined;
  color?: string | undefined;
  team?: TeamInclude | undefined;
};

export const CustomTagDataAttributes$zodSchema: z.ZodType<
  CustomTagDataAttributes,
  z.ZodTypeDef,
  unknown
> = z.object({
  color: z.string().optional(),
  description: z.string().optional(),
  name: z.string().optional(),
  slug: z.string().optional(),
  team: TeamInclude$zodSchema.optional(),
});

export type CustomTagData = {
  id?: string | undefined;
  type?: CustomTagDataType | undefined;
  attributes?: CustomTagDataAttributes | undefined;
};

export const CustomTagData$zodSchema: z.ZodType<
  CustomTagData,
  z.ZodTypeDef,
  unknown
> = z.object({
  attributes: z.lazy(() => CustomTagDataAttributes$zodSchema).optional(),
  id: z.string().optional(),
  type: CustomTagDataType$zodSchema.optional(),
});
