/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type DeleteStorageBucketsRequest = { id: string };

export const DeleteStorageBucketsRequest$zodSchema: z.ZodType<
  DeleteStorageBucketsRequest
> = z.object({
  id: z.string().describe("The object storage ID"),
});
