/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type DeleteVirtualNetworksAssignmentsRequest = { assignment_id: string };

export const DeleteVirtualNetworksAssignmentsRequest$zodSchema: z.ZodType<
  DeleteVirtualNetworksAssignmentsRequest
> = z.object({
  assignment_id: z.string(),
});

export type DeleteVirtualNetworksAssignmentsResponse = {
  ContentType: string;
  StatusCode: number;
  RawResponse: Response;
};

export const DeleteVirtualNetworksAssignmentsResponse$zodSchema: z.ZodType<
  DeleteVirtualNetworksAssignmentsResponse
> = z.object({
  ContentType: z.string(),
  RawResponse: z.custom<Response>(x => x instanceof Response),
  StatusCode: z.int(),
});
