/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type DeleteProjectUserDataRequest = {
  project_id: string;
  user_data_id: string;
};

export const DeleteProjectUserDataRequest$zodSchema: z.ZodType<
  DeleteProjectUserDataRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  project_id: z.string().describe("Project ID or Slug"),
  user_data_id: z.string(),
});

export type DeleteProjectUserDataResponse = {
  ContentType: string;
  StatusCode: number;
  RawResponse: Response;
};

export const DeleteProjectUserDataResponse$zodSchema: z.ZodType<
  DeleteProjectUserDataResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  ContentType: z.string(),
  RawResponse: z.instanceof(Response),
  StatusCode: z.number().int(),
});
