/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type DeleteLksClusterRequest = { id: string };

export const DeleteLksClusterRequest$zodSchema: z.ZodType<
  DeleteLksClusterRequest
> = z.object({
  id: z.string().describe("The cluster ID (format: `lksc_<hash>`)."),
});
