/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type DeleteFirewallAssignmentRequest = {
  firewall_id: string;
  assignment_id: string;
};

export const DeleteFirewallAssignmentRequest$zodSchema: z.ZodType<
  DeleteFirewallAssignmentRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  assignment_id: z.string().describe("The Assignment ID"),
  firewall_id: z.string().describe("The Firewall ID"),
});

export type DeleteFirewallAssignmentResponse = {
  ContentType: string;
  StatusCode: number;
  RawResponse: Response;
};

export const DeleteFirewallAssignmentResponse$zodSchema: z.ZodType<
  DeleteFirewallAssignmentResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  ContentType: z.string(),
  RawResponse: z.instanceof(Response),
  StatusCode: z.number().int(),
});
