/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type DeleteUserDataRequest = { user_data_id: string };

export const DeleteUserDataRequest$zodSchema: z.ZodType<DeleteUserDataRequest> =
  z.object({
    user_data_id: z.string(),
  });

export type DeleteUserDataResponse = {
  ContentType: string;
  StatusCode: number;
  RawResponse: Response;
};

export const DeleteUserDataResponse$zodSchema: z.ZodType<
  DeleteUserDataResponse
> = z.object({
  ContentType: z.string(),
  RawResponse: z.custom<Response>(x => x instanceof Response),
  StatusCode: z.int(),
});
