/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type DeleteLksNodePoolRequest = { cluster_id: string; id: string };

export const DeleteLksNodePoolRequest$zodSchema: z.ZodType<
  DeleteLksNodePoolRequest
> = z.object({
  cluster_id: z.string().describe("The cluster ID (format: `lksc_<hash>`)."),
  id: z.string().describe("The node pool ID (format: `lksnp_<hash>`)."),
});
