/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type DeleteStorageFilesystemsRequest = { filesystem_id: string };

export const DeleteStorageFilesystemsRequest$zodSchema: z.ZodType<
  DeleteStorageFilesystemsRequest
> = z.object({
  filesystem_id: z.string(),
});

export type DeleteStorageFilesystemsResponse = {
  ContentType: string;
  StatusCode: number;
  RawResponse: Response;
};

export const DeleteStorageFilesystemsResponse$zodSchema: z.ZodType<
  DeleteStorageFilesystemsResponse
> = z.object({
  ContentType: z.string(),
  RawResponse: z.custom<Response>(x => x instanceof Response),
  StatusCode: z.int(),
});
