/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type DeleteSshKeyRequest = { ssh_key_id: string };

export const DeleteSshKeyRequest$zodSchema: z.ZodType<
  DeleteSshKeyRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  ssh_key_id: z.string(),
});

export type DeleteSshKeyResponse = {
  ContentType: string;
  StatusCode: number;
  RawResponse: Response;
};

export const DeleteSshKeyResponse$zodSchema: z.ZodType<
  DeleteSshKeyResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  ContentType: z.string(),
  RawResponse: z.instanceof(Response),
  StatusCode: z.number().int(),
});
