/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type DeleteSshKeyRequest = { ssh_key_id: string };

export const DeleteSshKeyRequest$zodSchema: z.ZodType<DeleteSshKeyRequest> = z
  .object({
    ssh_key_id: z.string(),
  });
