/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

export const DeployConfigRole = {
  Os: "os",
  Storage: "storage",
  Raw: "raw",
} as const;
export type DeployConfigRole = ClosedEnum<typeof DeployConfigRole>;

export const DeployConfigRole$zodSchema = z.enum([
  "os",
  "storage",
  "raw",
]);

export const DeployConfigRaidLevel = {
  Raid0: "raid-0",
  Raid1: "raid-1",
} as const;
export type DeployConfigRaidLevel = ClosedEnum<typeof DeployConfigRaidLevel>;

export const DeployConfigRaidLevel$zodSchema = z.enum([
  "raid-0",
  "raid-1",
]);

export const DeployConfigFilesystem = {
  Ext4: "ext4",
  Xfs: "xfs",
} as const;
export type DeployConfigFilesystem = ClosedEnum<typeof DeployConfigFilesystem>;

export const DeployConfigFilesystem$zodSchema = z.enum([
  "ext4",
  "xfs",
]);

export type DiskLayout = {
  count: number;
  role: DeployConfigRole;
  raid_level?: DeployConfigRaidLevel | null | undefined;
  filesystem?: DeployConfigFilesystem | null | undefined;
  mount_point?: string | null | undefined;
};

export const DiskLayout$zodSchema: z.ZodType<DiskLayout> = z.object({
  count: z.int(),
  filesystem: DeployConfigFilesystem$zodSchema.nullable().optional(),
  mount_point: z.string().nullable().optional(),
  raid_level: DeployConfigRaidLevel$zodSchema.nullable().optional(),
  role: DeployConfigRole$zodSchema,
});

export type DeployConfigAttributes = {
  operating_system?: string | undefined;
  hostname?: string | undefined;
  raid?: string | undefined;
  disk_layout?: Array<DiskLayout> | null | undefined;
  user_data?: string | undefined;
  ssh_keys?: Array<string> | undefined;
  persistent_netboot?: boolean | null | undefined;
  public_network?: boolean | null | undefined;
  public_network_id?: string | null | undefined;
};

export const DeployConfigAttributes$zodSchema: z.ZodType<
  DeployConfigAttributes
> = z.object({
  disk_layout: z.array(z.lazy(() => DiskLayout$zodSchema)).nullable()
    .optional(),
  hostname: z.string().optional(),
  operating_system: z.string().optional(),
  persistent_netboot: z.boolean().nullable().optional().describe(
    "Keep network boot enabled so the server iPXE-boots on every reboot instead of booting from disk. Only supported with the 'ipxe' operating system.",
  ),
  public_network: z.boolean().nullable().optional(),
  public_network_id: z.string().nullable().optional(),
  raid: z.string().optional(),
  ssh_keys: z.array(z.string()).optional(),
  user_data: z.string().optional(),
});

export type DeployConfigData = {
  id?: string | undefined;
  attributes?: DeployConfigAttributes | undefined;
};

export const DeployConfigData$zodSchema: z.ZodType<DeployConfigData> = z.object(
  {
    attributes: z.lazy(() => DeployConfigAttributes$zodSchema).optional(),
    id: z.string().optional(),
  },
);

export type DeployConfig = { data?: DeployConfigData | undefined };

export const DeployConfig$zodSchema: z.ZodType<DeployConfig> = z.object({
  data: z.lazy(() => DeployConfigData$zodSchema).optional(),
});
