/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type DestroyTagRequest = { tag_id: string };

export const DestroyTagRequest$zodSchema: z.ZodType<
  DestroyTagRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  tag_id: z.string(),
});

export type DestroyTagResponse = {
  ContentType: string;
  StatusCode: number;
  RawResponse: Response;
};

export const DestroyTagResponse$zodSchema: z.ZodType<
  DestroyTagResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  ContentType: z.string(),
  RawResponse: z.instanceof(Response),
  StatusCode: z.number().int(),
});
