/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type DestroyTeamMemberRequest = { user_id: string };

export const DestroyTeamMemberRequest$zodSchema: z.ZodType<
  DestroyTeamMemberRequest
> = z.object({
  user_id: z.string().describe("The user ID"),
});

export type DestroyTeamMemberResponse = {
  ContentType: string;
  StatusCode: number;
  RawResponse: Response;
};

export const DestroyTeamMemberResponse$zodSchema: z.ZodType<
  DestroyTeamMemberResponse
> = z.object({
  ContentType: z.string(),
  RawResponse: z.custom<Response>(x => x instanceof Response),
  StatusCode: z.int(),
});
