/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type DestroyVirtualNetworkRequest = { vlan_id: string };

export const DestroyVirtualNetworkRequest$zodSchema: z.ZodType<
  DestroyVirtualNetworkRequest
> = z.object({
  vlan_id: z.string().describe("The virtual network ID"),
});
