/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type DestroyServerRequest = {
  server_id: string;
  reason?: string | undefined;
};

export const DestroyServerRequest$zodSchema: z.ZodType<
  DestroyServerRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  reason: z.string().describe("The reason for deleting the server").optional(),
  server_id: z.string().describe("The server ID"),
});

export type DestroyServerResponse = {
  ContentType: string;
  StatusCode: number;
  RawResponse: Response;
};

export const DestroyServerResponse$zodSchema: z.ZodType<
  DestroyServerResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  ContentType: z.string(),
  RawResponse: z.instanceof(Response),
  StatusCode: z.number().int(),
});
