/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type DestroyVirtualMachineNetworkAttachmentRequest = {
  virtual_machine_id: string;
  id: string;
};

export const DestroyVirtualMachineNetworkAttachmentRequest$zodSchema: z.ZodType<
  DestroyVirtualMachineNetworkAttachmentRequest
> = z.object({
  id: z.string().describe("The VLAN id_hash to detach"),
  virtual_machine_id: z.string(),
});

export type DestroyVirtualMachineNetworkAttachmentMeta = {
  status?: string | undefined;
};

export const DestroyVirtualMachineNetworkAttachmentMeta$zodSchema: z.ZodType<
  DestroyVirtualMachineNetworkAttachmentMeta
> = z.object({
  status: z.string().optional(),
});

/**
 * Accepted
 */
export type DestroyVirtualMachineNetworkAttachmentResponse = {
  meta?: DestroyVirtualMachineNetworkAttachmentMeta | undefined;
};

export const DestroyVirtualMachineNetworkAttachmentResponse$zodSchema:
  z.ZodType<DestroyVirtualMachineNetworkAttachmentResponse> = z.object({
    meta: z.lazy(() => DestroyVirtualMachineNetworkAttachmentMeta$zodSchema)
      .optional(),
  }).describe("Accepted");
