/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ElasticIpData, ElasticIpData$zodSchema } from "./elasticipdata.js";

export type ElasticIpsMeta = {};

export const ElasticIpsMeta$zodSchema: z.ZodType<ElasticIpsMeta> = z.object({});

export type ElasticIps = {
  data?: Array<ElasticIpData> | undefined;
  meta?: ElasticIpsMeta | undefined;
};

export const ElasticIps$zodSchema: z.ZodType<ElasticIps> = z.object({
  data: z.array(ElasticIpData$zodSchema).optional(),
  meta: z.lazy(() => ElasticIpsMeta$zodSchema).optional(),
});
