/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

export const ElasticIpDataType = {
  ElasticIps: "elastic_ips",
} as const;
export type ElasticIpDataType = ClosedEnum<typeof ElasticIpDataType>;

export const ElasticIpDataType$zodSchema = z.enum([
  "elastic_ips",
]);

/**
 * The IP address family
 */
export const ElasticIpDataFamily = {
  IPv4: "IPv4",
} as const;
/**
 * The IP address family
 */
export type ElasticIpDataFamily = ClosedEnum<typeof ElasticIpDataFamily>;

export const ElasticIpDataFamily$zodSchema = z.enum([
  "IPv4",
]).describe("The IP address family");

/**
 * The routing mode for this Elastic IP
 */
export const Mode = {
  Routed: "routed",
} as const;
/**
 * The routing mode for this Elastic IP
 */
export type Mode = ClosedEnum<typeof Mode>;

export const Mode$zodSchema = z.enum([
  "routed",
]).describe("The routing mode for this Elastic IP");

/**
 * The current status of the Elastic IP
 */
export const ElasticIpDataStatus = {
  Configuring: "configuring",
  Active: "active",
  Moving: "moving",
  Releasing: "releasing",
  Error: "error",
} as const;
/**
 * The current status of the Elastic IP
 */
export type ElasticIpDataStatus = ClosedEnum<typeof ElasticIpDataStatus>;

export const ElasticIpDataStatus$zodSchema = z.enum([
  "configuring",
  "active",
  "moving",
  "releasing",
  "error",
]).describe("The current status of the Elastic IP");

/**
 * The server this Elastic IP is assigned to
 */
export type ElasticIpDataServer = {
  id?: string | undefined;
  hostname?: string | undefined;
  primary_ipv4?: string | undefined;
  operating_system?: string | null | undefined;
};

export const ElasticIpDataServer$zodSchema: z.ZodType<ElasticIpDataServer> = z
  .object({
    hostname: z.string().optional(),
    id: z.string().optional(),
    operating_system: z.string().nullable().optional(),
    primary_ipv4: z.string().optional(),
  }).describe("The server this Elastic IP is assigned to");

/**
 * The project this Elastic IP belongs to
 */
export type ElasticIpDataProject = {
  id?: string | undefined;
  name?: string | undefined;
  slug?: string | undefined;
};

export const ElasticIpDataProject$zodSchema: z.ZodType<ElasticIpDataProject> = z
  .object({
    id: z.string().optional(),
    name: z.string().optional(),
    slug: z.string().optional(),
  }).describe("The project this Elastic IP belongs to");

/**
 * The site/location within the region
 */
export type ElasticIpDataLocation = {
  id?: string | undefined;
  name?: string | undefined;
  slug?: string | undefined;
};

export const ElasticIpDataLocation$zodSchema: z.ZodType<ElasticIpDataLocation> =
  z.object({
    id: z.string().optional(),
    name: z.string().optional(),
    slug: z.string().optional(),
  }).describe("The site/location within the region");

/**
 * The region where this Elastic IP is located
 */
export type ElasticIpDataRegion = {
  id?: string | undefined;
  name?: string | undefined;
  location?: ElasticIpDataLocation | undefined;
};

export const ElasticIpDataRegion$zodSchema: z.ZodType<ElasticIpDataRegion> = z
  .object({
    id: z.string().optional(),
    location: z.lazy(() => ElasticIpDataLocation$zodSchema).optional(),
    name: z.string().optional(),
  }).describe("The region where this Elastic IP is located");

export type ElasticIpDataAttributes = {
  address?: string | undefined;
  family?: ElasticIpDataFamily | undefined;
  prefix_length?: number | undefined;
  mode?: Mode | undefined;
  status?: ElasticIpDataStatus | undefined;
  created_at?: string | undefined;
  server?: ElasticIpDataServer | null | undefined;
  project?: ElasticIpDataProject | undefined;
  region?: ElasticIpDataRegion | null | undefined;
};

export const ElasticIpDataAttributes$zodSchema: z.ZodType<
  ElasticIpDataAttributes
> = z.object({
  address: z.string().optional(),
  created_at: z.iso.datetime({ offset: true }).optional(),
  family: ElasticIpDataFamily$zodSchema.optional(),
  mode: Mode$zodSchema.optional(),
  prefix_length: z.int().optional(),
  project: z.lazy(() => ElasticIpDataProject$zodSchema).optional(),
  region: z.lazy(() => ElasticIpDataRegion$zodSchema).nullable().optional(),
  server: z.lazy(() => ElasticIpDataServer$zodSchema).nullable().optional(),
  status: ElasticIpDataStatus$zodSchema.optional(),
});

export type ElasticIpData = {
  id?: string | null | undefined;
  type?: ElasticIpDataType | undefined;
  attributes?: ElasticIpDataAttributes | undefined;
};

export const ElasticIpData$zodSchema: z.ZodType<ElasticIpData> = z.object({
  attributes: z.lazy(() => ElasticIpDataAttributes$zodSchema).optional(),
  id: z.string().nullable().optional(),
  type: ElasticIpDataType$zodSchema.optional(),
});
