/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { EventData, EventData$zodSchema } from "./eventdata.js";

export type EventsMeta = {};

export const EventsMeta$zodSchema: z.ZodType<
  EventsMeta,
  z.ZodTypeDef,
  unknown
> = z.object({});

export type Events = {
  data?: Array<EventData> | undefined;
  meta?: EventsMeta | undefined;
};

export const Events$zodSchema: z.ZodType<Events, z.ZodTypeDef, unknown> = z
  .object({
    data: z.array(EventData$zodSchema).optional(),
    meta: z.lazy(() => EventsMeta$zodSchema).optional(),
  });
