/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { FilesystemData, FilesystemData$zodSchema } from "./filesystemdata.js";

export type FilesystemsMeta = {};

export const FilesystemsMeta$zodSchema: z.ZodType<FilesystemsMeta> = z.object(
  {},
);

export type Filesystems = {
  data?: Array<FilesystemData> | undefined;
  meta?: FilesystemsMeta | undefined;
};

export const Filesystems$zodSchema: z.ZodType<Filesystems> = z.object({
  data: z.array(FilesystemData$zodSchema).optional(),
  meta: z.lazy(() => FilesystemsMeta$zodSchema).optional(),
});
