/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";
import { ProjectInclude, ProjectInclude$zodSchema } from "./projectinclude.js";
import { TeamInclude, TeamInclude$zodSchema } from "./teaminclude.js";

export const FilesystemDataType = {
  Filesystems: "filesystems",
} as const;
export type FilesystemDataType = ClosedEnum<typeof FilesystemDataType>;

export const FilesystemDataType$zodSchema = z.enum([
  "filesystems",
]);

export const FilesystemStorageClass = {
  Standard: "standard",
  HighPerformance: "high_performance",
} as const;
export type FilesystemStorageClass = ClosedEnum<typeof FilesystemStorageClass>;

export const FilesystemStorageClass$zodSchema = z.enum([
  "standard",
  "high_performance",
]);

export type FilesystemDataAttributes = {
  name?: string | undefined;
  size_in_gb?: number | undefined;
  storage_class?: FilesystemStorageClass | null | undefined;
  created_at?: string | null | undefined;
  keyring?: string | null | undefined;
  cluster_user?: string | null | undefined;
  volume_path?: string | null | undefined;
  project?: ProjectInclude | undefined;
  team?: TeamInclude | undefined;
};

export const FilesystemDataAttributes$zodSchema: z.ZodType<
  FilesystemDataAttributes
> = z.object({
  cluster_user: z.string().nullable().optional().describe(
    "Cluster user used to mount the filesystem. Returned only for dashboard-origin requests; null until the filesystem is provisioned.",
  ),
  created_at: z.iso.datetime({ offset: true }).nullable().optional(),
  keyring: z.string().nullable().optional().describe(
    "Keyring secret used to mount the filesystem. Returned only for dashboard-origin requests; null until the filesystem is provisioned.",
  ),
  name: z.string().optional(),
  project: ProjectInclude$zodSchema.optional(),
  size_in_gb: z.int().optional(),
  storage_class: FilesystemStorageClass$zodSchema.nullable().optional(),
  team: TeamInclude$zodSchema.optional(),
  volume_path: z.string().nullable().optional().describe(
    "Path of the filesystem volume inside the cluster. Returned only for dashboard-origin requests; null until the filesystem is provisioned.",
  ),
});

export type FilesystemData = {
  id?: string | undefined;
  type?: FilesystemDataType | undefined;
  attributes?: FilesystemDataAttributes | undefined;
};

export const FilesystemData$zodSchema: z.ZodType<FilesystemData> = z.object({
  attributes: z.lazy(() => FilesystemDataAttributes$zodSchema).optional(),
  id: z.string().optional(),
  type: FilesystemDataType$zodSchema.optional(),
});
