/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

export const FirewallAssignmentDataType = {
  FirewallAssignments: "firewall_assignments",
} as const;
export type FirewallAssignmentDataType = ClosedEnum<
  typeof FirewallAssignmentDataType
>;

export const FirewallAssignmentDataType$zodSchema = z.enum([
  "firewall_assignments",
]);

export type FirewallAssignmentDataServer = {
  id?: string | undefined;
  primary_ipv4?: string | undefined;
  hostname?: string | undefined;
};

export const FirewallAssignmentDataServer$zodSchema: z.ZodType<
  FirewallAssignmentDataServer
> = z.object({
  hostname: z.string().optional(),
  id: z.string().optional(),
  primary_ipv4: z.string().optional(),
});

export type FirewallAssignmentDataFirewall = {
  id?: string | undefined;
  name?: string | undefined;
};

export const FirewallAssignmentDataFirewall$zodSchema: z.ZodType<
  FirewallAssignmentDataFirewall
> = z.object({
  id: z.string().optional(),
  name: z.string().optional(),
});

export type FirewallAssignmentDataAttributes = {
  server?: FirewallAssignmentDataServer | undefined;
  firewall?: FirewallAssignmentDataFirewall | undefined;
  firewall_id?: string | undefined;
};

export const FirewallAssignmentDataAttributes$zodSchema: z.ZodType<
  FirewallAssignmentDataAttributes
> = z.object({
  firewall: z.lazy(() => FirewallAssignmentDataFirewall$zodSchema).optional(),
  firewall_id: z.string().optional(),
  server: z.lazy(() => FirewallAssignmentDataServer$zodSchema).optional(),
});

export type FirewallAssignmentData = {
  id?: string | undefined;
  type?: FirewallAssignmentDataType | undefined;
  attributes?: FirewallAssignmentDataAttributes | undefined;
};

export const FirewallAssignmentData$zodSchema: z.ZodType<
  FirewallAssignmentData
> = z.object({
  attributes: z.lazy(() => FirewallAssignmentDataAttributes$zodSchema)
    .optional(),
  id: z.string().optional(),
  type: FirewallAssignmentDataType$zodSchema.optional(),
});
