/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

export const FirewallDataType = {
  Firewalls: "firewalls",
} as const;
export type FirewallDataType = ClosedEnum<typeof FirewallDataType>;

export const FirewallDataType$zodSchema = z.enum([
  "firewalls",
]);

export type Rule = {
  from?: string | undefined;
  to?: string | undefined;
  port?: string | undefined;
  protocol?: string | undefined;
  description?: string | null | undefined;
};

export const Rule$zodSchema: z.ZodType<Rule> = z.object({
  description: z.string().nullable().optional().describe(
    "Optional description explaining the purpose of this rule",
  ),
  from: z.string().optional().describe(
    "Source IP address, IP range in CIDR notation, or 'ANY' (e.g., \"192.168.1.1\", \"192.168.1.0/24\", \"ANY\")",
  ),
  port: z.string().optional(),
  protocol: z.string().optional(),
  to: z.string().optional().describe(
    "Destination IP address, IP range in CIDR notation, or 'ANY' (e.g., \"192.168.1.1\", \"192.168.1.0/24\", \"ANY\")",
  ),
});

export type FirewallDataProject = {
  id?: string | undefined;
  slug?: string | undefined;
  name?: string | undefined;
};

export const FirewallDataProject$zodSchema: z.ZodType<FirewallDataProject> = z
  .object({
    id: z.string().optional(),
    name: z.string().optional(),
    slug: z.string().optional(),
  });

export type FirewallDataAttributes = {
  name?: string | undefined;
  rules?: Array<Rule> | undefined;
  project?: FirewallDataProject | undefined;
};

export const FirewallDataAttributes$zodSchema: z.ZodType<
  FirewallDataAttributes
> = z.object({
  name: z.string().optional(),
  project: z.lazy(() => FirewallDataProject$zodSchema).optional(),
  rules: z.array(z.lazy(() => Rule$zodSchema)).optional(),
});

export type FirewallData = {
  id?: string | undefined;
  type?: FirewallDataType | undefined;
  attributes?: FirewallDataAttributes | undefined;
};

export const FirewallData$zodSchema: z.ZodType<FirewallData> = z.object({
  attributes: z.lazy(() => FirewallDataAttributes$zodSchema).optional(),
  id: z.string().optional(),
  type: FirewallDataType$zodSchema.optional(),
});
