/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ApiKey, ApiKey$zodSchema } from "./apikey.js";

export type GetApiKeysResponse = {
  ContentType: string;
  StatusCode: number;
  RawResponse: Response;
  api_key?: ApiKey | undefined;
};

export const GetApiKeysResponse$zodSchema: z.ZodType<
  GetApiKeysResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  ContentType: z.string(),
  RawResponse: z.instanceof(Response),
  StatusCode: z.number().int(),
  api_key: ApiKey$zodSchema.optional(),
});
