/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type GetFirewallRequest = { firewall_id: string };

export const GetFirewallRequest$zodSchema: z.ZodType<GetFirewallRequest> = z
  .object({
    firewall_id: z.string().describe("The Firewall ID"),
  });
