/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ErrorObject, ErrorObject$zodSchema } from "./errorobject.js";
import { LksCluster, LksCluster$zodSchema } from "./lkscluster.js";

export type GetLksClusterRequest = { id: string };

export const GetLksClusterRequest$zodSchema: z.ZodType<GetLksClusterRequest> = z
  .object({
    id: z.string().describe("The cluster ID (format: `lksc_<hash>`)."),
  });

export type GetLksClusterResponse = LksCluster | ErrorObject;

export const GetLksClusterResponse$zodSchema: z.ZodType<GetLksClusterResponse> =
  z.union([
    LksCluster$zodSchema,
    ErrorObject$zodSchema,
  ]);
