/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ErrorObject, ErrorObject$zodSchema } from "./errorobject.js";
import { MarketplaceApp, MarketplaceApp$zodSchema } from "./marketplaceapp.js";

export type GetMarketplaceAppRequest = { id: string };

export const GetMarketplaceAppRequest$zodSchema: z.ZodType<
  GetMarketplaceAppRequest
> = z.object({
  id: z.string().describe("The marketplace app ID or slug"),
});

export type GetMarketplaceAppResponse = MarketplaceApp | ErrorObject;

export const GetMarketplaceAppResponse$zodSchema: z.ZodType<
  GetMarketplaceAppResponse
> = z.union([
  MarketplaceApp$zodSchema,
  ErrorObject$zodSchema,
]);
