/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  OperatingSystems,
  OperatingSystems$zodSchema,
} from "./operatingsystems.js";

export type GetPlansOperatingSystemRequest = {
  pageSize?: number | undefined;
  pageNumber?: number | undefined;
};

export const GetPlansOperatingSystemRequest$zodSchema: z.ZodType<
  GetPlansOperatingSystemRequest
> = z.object({
  pageNumber: z.int().default(1).describe(
    "Page number to return (starts at 1)",
  ),
  pageSize: z.int().default(20).describe("Number of items to return per page"),
});

export type GetPlansOperatingSystemResponse = { Result: OperatingSystems };

export const GetPlansOperatingSystemResponse$zodSchema: z.ZodType<
  GetPlansOperatingSystemResponse
> = z.object({
  Result: OperatingSystems$zodSchema,
});
