/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { SshKeyData, SshKeyData$zodSchema } from "./sshkeydata.js";

export type GetProjectSshKeyRequest = {
  project_id: string;
  ssh_key_id: string;
};

export const GetProjectSshKeyRequest$zodSchema: z.ZodType<
  GetProjectSshKeyRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  project_id: z.string().describe("Project ID or Slug"),
  ssh_key_id: z.string(),
});

/**
 * Success
 */
export type GetProjectSshKeyResponseBody = { data?: SshKeyData | undefined };

export const GetProjectSshKeyResponseBody$zodSchema: z.ZodType<
  GetProjectSshKeyResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  data: SshKeyData$zodSchema.optional(),
}).describe("Success");

export type GetProjectSshKeyResponse = {
  ContentType: string;
  StatusCode: number;
  RawResponse: Response;
  object?: GetProjectSshKeyResponseBody | undefined;
};

export const GetProjectSshKeyResponse$zodSchema: z.ZodType<
  GetProjectSshKeyResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  ContentType: z.string(),
  RawResponse: z.instanceof(Response),
  StatusCode: z.number().int(),
  object: z.lazy(() => GetProjectSshKeyResponseBody$zodSchema).optional(),
});
