/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { Project, Project$zodSchema } from "./project.js";

export type GetProjectRequest = { project_id: string };

export const GetProjectRequest$zodSchema: z.ZodType<GetProjectRequest> = z
  .object({
    project_id: z.string().describe("The project ID or Slug"),
  });

export type GetProjectMeta = {};

export const GetProjectMeta$zodSchema: z.ZodType<GetProjectMeta> = z.object({});

/**
 * Success
 */
export type GetProjectResponse = {
  data?: Project | undefined;
  meta?: GetProjectMeta | undefined;
};

export const GetProjectResponse$zodSchema: z.ZodType<GetProjectResponse> = z
  .object({
    data: Project$zodSchema.optional(),
    meta: z.lazy(() => GetProjectMeta$zodSchema).optional(),
  }).describe("Success");
