/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { Plan, Plan$zodSchema } from "./plan.js";

export type GetPlanRequest = { plan_id: string };

export const GetPlanRequest$zodSchema: z.ZodType<GetPlanRequest> = z.object({
  plan_id: z.string(),
});

export type GetPlanResponse = {
  ContentType: string;
  StatusCode: number;
  RawResponse: Response;
  plan?: Plan | undefined;
};

export const GetPlanResponse$zodSchema: z.ZodType<GetPlanResponse> = z.object({
  ContentType: z.string(),
  RawResponse: z.custom<Response>(x => x instanceof Response),
  StatusCode: z.int(),
  plan: Plan$zodSchema.optional(),
});
