/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { UserData, UserData$zodSchema } from "./userdata.js";

export type GetProjectUsersDataRequest = {
  project_id: string;
  extraFieldsUserData?: string | undefined;
};

export const GetProjectUsersDataRequest$zodSchema: z.ZodType<
  GetProjectUsersDataRequest
> = z.object({
  extraFieldsUserData: z.string().default("decoded_content").describe(
    "The `decoded_content` is provided as an extra attribute that shows content in decoded form.",
  ),
  project_id: z.string().describe("Project ID or Slug"),
});

export type GetProjectUsersDataResponse = {
  ContentType: string;
  StatusCode: number;
  RawResponse: Response;
  user_data?: UserData | undefined;
};

export const GetProjectUsersDataResponse$zodSchema: z.ZodType<
  GetProjectUsersDataResponse
> = z.object({
  ContentType: z.string(),
  RawResponse: z.custom<Response>(x => x instanceof Response),
  StatusCode: z.int(),
  user_data: UserData$zodSchema.optional(),
});
