/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { Region, Region$zodSchema } from "./region.js";

export type GetRegionRequest = { region_id: string };

export const GetRegionRequest$zodSchema: z.ZodType<GetRegionRequest> = z.object(
  {
    region_id: z.string().describe("The region region_ID"),
  },
);

export type GetRegionResponse = {
  ContentType: string;
  StatusCode: number;
  RawResponse: Response;
  region?: Region | undefined;
};

export const GetRegionResponse$zodSchema: z.ZodType<GetRegionResponse> = z
  .object({
    ContentType: z.string(),
    RawResponse: z.custom<Response>(x => x instanceof Response),
    StatusCode: z.int(),
    region: Region$zodSchema.optional(),
  });
