/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { Regions, Regions$zodSchema } from "./regions.js";

export type GetRegionsRequest = {
  pageSize?: number | undefined;
  pageNumber?: number | undefined;
};

export const GetRegionsRequest$zodSchema: z.ZodType<GetRegionsRequest> = z
  .object({
    pageNumber: z.int().default(1).describe(
      "Page number to return (starts at 1)",
    ),
    pageSize: z.int().default(20).describe(
      "Number of items to return per page",
    ),
  });

export type GetRegionsResponse = { Result: Regions };

export const GetRegionsResponse$zodSchema: z.ZodType<GetRegionsResponse> = z
  .object({
    Result: Regions$zodSchema,
  });
