/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type GetServerRequest = {
  server_id: string;
  extraFieldsServers?: string | undefined;
};

export const GetServerRequest$zodSchema: z.ZodType<GetServerRequest> = z.object(
  {
    extraFieldsServers: z.string().describe(
      "The `credentials` are provided as extra attributes that is lazy loaded. To request it, just set `extra_fields[servers]=credentials` in the query string.",
    ).optional(),
    server_id: z.string().describe("The Server ID"),
  },
);
