/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ErrorObject, ErrorObject$zodSchema } from "./errorobject.js";
import { ObjectStorages, ObjectStorages$zodSchema } from "./objectstorages.js";

export type GetStorageBucketsRequest = { filterProject?: string | undefined };

export const GetStorageBucketsRequest$zodSchema: z.ZodType<
  GetStorageBucketsRequest
> = z.object({
  filterProject: z.string().describe("The project ID or Slug to filter by")
    .optional(),
});

export type GetStorageBucketsResponse = ObjectStorages | ErrorObject;

export const GetStorageBucketsResponse$zodSchema: z.ZodType<
  GetStorageBucketsResponse
> = z.union([
  ObjectStorages$zodSchema,
  ErrorObject$zodSchema,
]);
