/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { VolumeData, VolumeData$zodSchema } from "./volumedata.js";

export type GetStorageVolumesRequest = { filterProject?: string | undefined };

export const GetStorageVolumesRequest$zodSchema: z.ZodType<
  GetStorageVolumesRequest
> = z.object({
  filterProject: z.string().describe("The project ID or Slug to filter by")
    .optional(),
});

/**
 * Success
 */
export type GetStorageVolumesResponse = {
  data?: Array<VolumeData> | undefined;
};

export const GetStorageVolumesResponse$zodSchema: z.ZodType<
  GetStorageVolumesResponse
> = z.object({
  data: z.array(VolumeData$zodSchema).optional(),
}).describe("Success");
