/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { StoragePlans, StoragePlans$zodSchema } from "./storageplans.js";

export type GetStoragePlansResponse = {
  ContentType: string;
  StatusCode: number;
  RawResponse: Response;
  storage_plans?: StoragePlans | undefined;
};

export const GetStoragePlansResponse$zodSchema: z.ZodType<
  GetStoragePlansResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  ContentType: z.string(),
  RawResponse: z.instanceof(Response),
  StatusCode: z.number().int(),
  storage_plans: StoragePlans$zodSchema.optional(),
});
