/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { VolumeData, VolumeData$zodSchema } from "./volumedata.js";

export type GetStorageVolumeRequest = { id: string };

export const GetStorageVolumeRequest$zodSchema: z.ZodType<
  GetStorageVolumeRequest
> = z.object({
  id: z.string().describe("The volume storage ID"),
});

/**
 * Success
 */
export type GetStorageVolumeResponseBody = { data?: VolumeData | undefined };

export const GetStorageVolumeResponseBody$zodSchema: z.ZodType<
  GetStorageVolumeResponseBody
> = z.object({
  data: VolumeData$zodSchema.optional(),
}).describe("Success");

export type GetStorageVolumeResponse = {
  ContentType: string;
  StatusCode: number;
  RawResponse: Response;
  object?: GetStorageVolumeResponseBody | undefined;
};

export const GetStorageVolumeResponse$zodSchema: z.ZodType<
  GetStorageVolumeResponse
> = z.object({
  ContentType: z.string(),
  RawResponse: z.custom<Response>(x => x instanceof Response),
  StatusCode: z.int(),
  object: z.lazy(() => GetStorageVolumeResponseBody$zodSchema).optional(),
});
