/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ErrorObject, ErrorObject$zodSchema } from "./errorobject.js";

export type GetStorageAccessKeysRequest = { project: string };

export const GetStorageAccessKeysRequest$zodSchema: z.ZodType<
  GetStorageAccessKeysRequest
> = z.object({
  project: z.string().describe("Project ID or slug to list access keys for."),
});

/**
 * Access key metadata. Exact fields depend on the storage provider.
 */
export type Standard = {
  name?: string | undefined;
  username?: string | undefined;
  access_key_id?: string | undefined;
  status?: string | undefined;
  created_at?: string | undefined;
  region?: string | null | undefined;
};

export const Standard$zodSchema: z.ZodType<Standard> = z.object({
  access_key_id: z.string().optional(),
  created_at: z.string().optional(),
  name: z.string().optional(),
  region: z.string().nullable().optional(),
  status: z.string().optional(),
  username: z.string().optional(),
}).describe(
  "Access key metadata. Exact fields depend on the storage provider.",
);

/**
 * Access key metadata. Exact fields depend on the storage provider.
 */
export type HighPerformance = {
  name?: string | undefined;
  username?: string | undefined;
  access_key_id?: string | undefined;
  status?: string | undefined;
  created_at?: string | undefined;
  region?: string | undefined;
};

export const HighPerformance$zodSchema: z.ZodType<HighPerformance> = z.object({
  access_key_id: z.string().optional(),
  created_at: z.string().optional(),
  name: z.string().optional(),
  region: z.string().optional(),
  status: z.string().optional(),
  username: z.string().optional(),
}).describe(
  "Access key metadata. Exact fields depend on the storage provider.",
);

/**
 * Access keys grouped by storage class.
 */
export type GetStorageAccessKeysData = {
  standard?: Array<Standard> | undefined;
  high_performance?: Array<HighPerformance> | undefined;
};

export const GetStorageAccessKeysData$zodSchema: z.ZodType<
  GetStorageAccessKeysData
> = z.object({
  high_performance: z.array(z.lazy(() => HighPerformance$zodSchema)).optional()
    .describe("VAST (high_performance) access keys, across all regions."),
  standard: z.array(z.lazy(() => Standard$zodSchema)).optional().describe(
    "Wasabi (standard) access keys.",
  ),
}).describe("Access keys grouped by storage class.");

/**
 * Success
 */
export type GetStorageAccessKeysResponseBody = {
  data?: GetStorageAccessKeysData | undefined;
};

export const GetStorageAccessKeysResponseBody$zodSchema: z.ZodType<
  GetStorageAccessKeysResponseBody
> = z.object({
  data: z.lazy(() => GetStorageAccessKeysData$zodSchema).optional().describe(
    "Access keys grouped by storage class.",
  ),
}).describe("Success");

export type GetStorageAccessKeysResponse =
  | GetStorageAccessKeysResponseBody
  | ErrorObject;

export const GetStorageAccessKeysResponse$zodSchema: z.ZodType<
  GetStorageAccessKeysResponse
> = z.union([
  z.lazy(() => GetStorageAccessKeysResponseBody$zodSchema),
  ErrorObject$zodSchema,
]);
