/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { User, User$zodSchema } from "./user.js";

/**
 * Success
 */
export type GetUserProfileResponseBody = { data?: User | undefined };

export const GetUserProfileResponseBody$zodSchema: z.ZodType<
  GetUserProfileResponseBody
> = z.object({
  data: User$zodSchema.optional(),
}).describe("Success");

export type GetUserProfileResponse = {
  ContentType: string;
  StatusCode: number;
  RawResponse: Response;
  object?: GetUserProfileResponseBody | undefined;
};

export const GetUserProfileResponse$zodSchema: z.ZodType<
  GetUserProfileResponse
> = z.object({
  ContentType: z.string(),
  RawResponse: z.custom<Response>(x => x instanceof Response),
  StatusCode: z.int(),
  object: z.lazy(() => GetUserProfileResponseBody$zodSchema).optional(),
});
