/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { User, User$zodSchema } from "./user.js";

/**
 * Success
 */
export type GetUserProfileResponse = { data?: User | undefined };

export const GetUserProfileResponse$zodSchema: z.ZodType<
  GetUserProfileResponse
> = z.object({
  data: User$zodSchema.optional(),
}).describe("Success");
