/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ErrorObject, ErrorObject$zodSchema } from "./errorobject.js";
import {
  VirtualMachineBackup,
  VirtualMachineBackup$zodSchema,
} from "./virtualmachinebackup.js";

export type GetVirtualMachineBackupRequest = { id: string };

export const GetVirtualMachineBackupRequest$zodSchema: z.ZodType<
  GetVirtualMachineBackupRequest
> = z.object({
  id: z.string(),
});

export type GetVirtualMachineBackupResponse =
  | VirtualMachineBackup
  | ErrorObject;

export const GetVirtualMachineBackupResponse$zodSchema: z.ZodType<
  GetVirtualMachineBackupResponse
> = z.union([
  VirtualMachineBackup$zodSchema,
  ErrorObject$zodSchema,
]);
