/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { VirtualNetwork, VirtualNetwork$zodSchema } from "./virtualnetwork.js";

export type GetVirtualNetworkRequest = { vlan_id: string };

export const GetVirtualNetworkRequest$zodSchema: z.ZodType<
  GetVirtualNetworkRequest
> = z.object({
  vlan_id: z.string().describe("Virtual Network ID"),
});

/**
 * Success
 */
export type GetVirtualNetworkResponseBody = {
  data?: VirtualNetwork | undefined;
};

export const GetVirtualNetworkResponseBody$zodSchema: z.ZodType<
  GetVirtualNetworkResponseBody
> = z.object({
  data: VirtualNetwork$zodSchema.optional(),
}).describe("Success");

export type GetVirtualNetworkResponse = {
  ContentType: string;
  StatusCode: number;
  RawResponse: Response;
  object?: GetVirtualNetworkResponseBody | undefined;
};

export const GetVirtualNetworkResponse$zodSchema: z.ZodType<
  GetVirtualNetworkResponse
> = z.object({
  ContentType: z.string(),
  RawResponse: z.custom<Response>(x => x instanceof Response),
  StatusCode: z.int(),
  object: z.lazy(() => GetVirtualNetworkResponseBody$zodSchema).optional(),
});
