/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";
import {
  VpnSessionDataWithPassword,
  VpnSessionDataWithPassword$zodSchema,
} from "./vpnsessiondatawithpassword.js";

export const FilterLocation = {
  Ash: "ASH",
  Bgt: "BGT",
  Bue: "BUE",
  Chi: "CHI",
  Dal: "DAL",
  Fra: "FRA",
  Lax: "LAX",
  Lon: "LON",
  Mex: "MEX",
  Mex2: "MEX2",
  Mia: "MIA",
  Mia2: "MIA2",
  Nyc: "NYC",
  San: "SAN",
  Sao: "SAO",
  Sao2: "SAO2",
  Syd: "SYD",
  Tyo: "TYO",
  Tyo4: "TYO4",
} as const;
export type FilterLocation = ClosedEnum<typeof FilterLocation>;

export const FilterLocation$zodSchema = z.enum([
  "ASH",
  "BGT",
  "BUE",
  "CHI",
  "DAL",
  "FRA",
  "LAX",
  "LON",
  "MEX",
  "MEX2",
  "MIA",
  "MIA2",
  "NYC",
  "SAN",
  "SAO",
  "SAO2",
  "SYD",
  "TYO",
  "TYO4",
]);

export type GetVpnSessionsRequest = {
  filterLocation?: FilterLocation | undefined;
};

export const GetVpnSessionsRequest$zodSchema: z.ZodType<GetVpnSessionsRequest> =
  z.object({
    filterLocation: FilterLocation$zodSchema.optional(),
  });

export type GetVpnSessionsMeta = {};

export const GetVpnSessionsMeta$zodSchema: z.ZodType<GetVpnSessionsMeta> = z
  .object({});

/**
 * Success
 */
export type GetVpnSessionsResponseBody = {
  data?: Array<VpnSessionDataWithPassword> | undefined;
  meta?: GetVpnSessionsMeta | undefined;
};

export const GetVpnSessionsResponseBody$zodSchema: z.ZodType<
  GetVpnSessionsResponseBody
> = z.object({
  data: z.array(VpnSessionDataWithPassword$zodSchema).optional(),
  meta: z.lazy(() => GetVpnSessionsMeta$zodSchema).optional(),
}).describe("Success");

export type GetVpnSessionsResponse = {
  ContentType: string;
  StatusCode: number;
  RawResponse: Response;
  object?: GetVpnSessionsResponseBody | undefined;
};

export const GetVpnSessionsResponse$zodSchema: z.ZodType<
  GetVpnSessionsResponse
> = z.object({
  ContentType: z.string(),
  RawResponse: z.custom<Response>(x => x instanceof Response),
  StatusCode: z.int(),
  object: z.lazy(() => GetVpnSessionsResponseBody$zodSchema).optional(),
});
