/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type GetVmPlansRequest = { filterGpu?: boolean | undefined };

export const GetVmPlansRequest$zodSchema: z.ZodType<GetVmPlansRequest> = z
  .object({
    filterGpu: z.boolean().describe("Filter plans by GPU availability")
      .optional(),
  });
