/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { VirtualNetwork, VirtualNetwork$zodSchema } from "./virtualnetwork.js";

export type GetVirtualNetworkRequest = { vlan_id: string };

export const GetVirtualNetworkRequest$zodSchema: z.ZodType<
  GetVirtualNetworkRequest
> = z.object({
  vlan_id: z.string().describe("Virtual Network ID"),
});

/**
 * Success
 */
export type GetVirtualNetworkResponse = { data?: VirtualNetwork | undefined };

export const GetVirtualNetworkResponse$zodSchema: z.ZodType<
  GetVirtualNetworkResponse
> = z.object({
  data: VirtualNetwork$zodSchema.optional(),
}).describe("Success");
