/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type IndexVirtualMachineRequest = {
  filterProject?: string | undefined;
  extraFieldsVirtualMachines?: string | undefined;
};

export const IndexVirtualMachineRequest$zodSchema: z.ZodType<
  IndexVirtualMachineRequest
> = z.object({
  extraFieldsVirtualMachines: z.string().describe(
    "The `credentials` are provided as extra attributes that are lazy loaded. To request it, just set `extra_fields[virtual_machines]=credentials` in the query string.",
  ).optional(),
  filterProject: z.string().describe("The project ID or Slug to filter by")
    .optional(),
});
