/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { IpAddressData, IpAddressData$zodSchema } from "./ipaddressdata.js";

export type IpAddressesMeta = {};

export const IpAddressesMeta$zodSchema: z.ZodType<IpAddressesMeta> = z.object(
  {},
);

export type IpAddresses = {
  data?: Array<IpAddressData> | undefined;
  meta?: IpAddressesMeta | undefined;
};

export const IpAddresses$zodSchema: z.ZodType<IpAddresses> = z.object({
  data: z.array(IpAddressData$zodSchema).optional(),
  meta: z.lazy(() => IpAddressesMeta$zodSchema).optional(),
});
