/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { IpAddressData, IpAddressData$zodSchema } from "./ipaddressdata.js";

export type IpAddressMeta = {};

export const IpAddressMeta$zodSchema: z.ZodType<IpAddressMeta> = z.object({});

export type IpAddress = {
  data?: IpAddressData | undefined;
  meta?: IpAddressMeta | undefined;
};

export const IpAddress$zodSchema: z.ZodType<IpAddress> = z.object({
  data: IpAddressData$zodSchema.optional(),
  meta: z.lazy(() => IpAddressMeta$zodSchema).optional(),
});
