/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type KubernetesAvailableVersionsData = {
  latest?: string | undefined;
  minor?: string | undefined;
};

export const KubernetesAvailableVersionsData$zodSchema: z.ZodType<
  KubernetesAvailableVersionsData
> = z.object({
  latest: z.string().optional().describe(
    "The latest full Kubernetes version string for this minor version (e.g., v1.35.3+rke2r1)",
  ),
  minor: z.string().optional().describe(
    "The minor version number (e.g., 1.35)",
  ),
});

/**
 * Response schema for available Kubernetes versions
 */
export type KubernetesAvailableVersions = {
  data?: Array<KubernetesAvailableVersionsData> | undefined;
};

export const KubernetesAvailableVersions$zodSchema: z.ZodType<
  KubernetesAvailableVersions
> = z.object({
  data: z.array(z.lazy(() => KubernetesAvailableVersionsData$zodSchema))
    .optional(),
}).describe("Response schema for available Kubernetes versions");
