/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  KubernetesClusterData,
  KubernetesClusterData$zodSchema,
} from "./kubernetesclusterdata.js";

export type KubernetesCluster = { data?: KubernetesClusterData | undefined };

export const KubernetesCluster$zodSchema: z.ZodType<KubernetesCluster> = z
  .object({
    data: KubernetesClusterData$zodSchema.optional(),
  });
