/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { catchUnrecognizedEnum, ClosedEnum, OpenEnum } from "../types/enums.js";

/**
 * The current phase of the cluster lifecycle.
 */
export const KubernetesClusterSummaryDataPhase = {
  Pending: "Pending",
  Provisioning: "Provisioning",
  Provisioned: "Provisioned",
  Upgrading: "Upgrading",
  Deleting: "Deleting",
  Failed: "Failed",
  Unknown: "Unknown",
} as const;
/**
 * The current phase of the cluster lifecycle.
 */
export type KubernetesClusterSummaryDataPhase = OpenEnum<
  typeof KubernetesClusterSummaryDataPhase
>;

export const KubernetesClusterSummaryDataPhase$zodSchema = z.union([
  z.enum([
    "Pending",
    "Provisioning",
    "Provisioned",
    "Upgrading",
    "Deleting",
    "Failed",
    "Unknown",
  ]),
  z.string().transform(catchUnrecognizedEnum),
]).describe("The current phase of the cluster lifecycle.");

/**
 * Step identifier
 */
export const KubernetesClusterSummaryDataName = {
  Infrastructure: "infrastructure",
  ControlPlane: "control_plane",
  Workers: "workers",
} as const;
/**
 * Step identifier
 */
export type KubernetesClusterSummaryDataName = ClosedEnum<
  typeof KubernetesClusterSummaryDataName
>;

export const KubernetesClusterSummaryDataName$zodSchema = z.enum([
  "infrastructure",
  "control_plane",
  "workers",
]).describe("Step identifier");

/**
 * Current status of this step
 */
export const KubernetesClusterSummaryDataStatus = {
  Pending: "pending",
  InProgress: "in_progress",
  Completed: "completed",
} as const;
/**
 * Current status of this step
 */
export type KubernetesClusterSummaryDataStatus = ClosedEnum<
  typeof KubernetesClusterSummaryDataStatus
>;

export const KubernetesClusterSummaryDataStatus$zodSchema = z.enum([
  "pending",
  "in_progress",
  "completed",
]).describe("Current status of this step");

export type KubernetesClusterSummaryDataStep = {
  name?: KubernetesClusterSummaryDataName | undefined;
  status?: KubernetesClusterSummaryDataStatus | undefined;
};

export const KubernetesClusterSummaryDataStep$zodSchema: z.ZodType<
  KubernetesClusterSummaryDataStep
> = z.object({
  name: KubernetesClusterSummaryDataName$zodSchema.optional().describe(
    "Step identifier",
  ),
  status: KubernetesClusterSummaryDataStatus$zodSchema.optional().describe(
    "Current status of this step",
  ),
});

export type KubernetesClusterSummaryDataAttributes = {
  name?: string | undefined;
  phase?: KubernetesClusterSummaryDataPhase | undefined;
  ready?: boolean | undefined;
  infrastructure_ready?: boolean | undefined;
  control_plane_ready?: boolean | undefined;
  message?: string | undefined;
  steps?: Array<KubernetesClusterSummaryDataStep> | undefined;
  last_status_change?: string | null | undefined;
  created_at?: string | undefined;
};

export const KubernetesClusterSummaryDataAttributes$zodSchema: z.ZodType<
  KubernetesClusterSummaryDataAttributes
> = z.object({
  control_plane_ready: z.boolean().optional().describe(
    "Whether the control plane is ready",
  ),
  created_at: z.iso.datetime({ offset: true }).optional().describe(
    "When the cluster was created",
  ),
  infrastructure_ready: z.boolean().optional().describe(
    "Whether the underlying infrastructure is ready",
  ),
  last_status_change: z.iso.datetime({ offset: true }).nullable().optional()
    .describe("Timestamp of the most recent status condition change"),
  message: z.string().optional().describe(
    "Human-readable status message describing the current provisioning state",
  ),
  name: z.string().optional().describe("The cluster name"),
  phase: KubernetesClusterSummaryDataPhase$zodSchema.optional().describe(
    "The current phase of the cluster lifecycle.",
  ),
  ready: z.boolean().optional().describe(
    "Whether the cluster is ready to accept workloads",
  ),
  steps: z.array(z.lazy(() => KubernetesClusterSummaryDataStep$zodSchema))
    .optional().describe("Provisioning progress steps for dashboard display"),
});

/**
 * Summary representation of a cluster (used in list responses)
 */
export type KubernetesClusterSummaryData = {
  id?: string | undefined;
  type?: string | undefined;
  attributes?: KubernetesClusterSummaryDataAttributes | undefined;
};

export const KubernetesClusterSummaryData$zodSchema: z.ZodType<
  KubernetesClusterSummaryData
> = z.object({
  attributes: z.lazy(() => KubernetesClusterSummaryDataAttributes$zodSchema)
    .optional(),
  id: z.string().optional().describe(
    "The cluster ID in hashed format (kc_<hash>)",
  ),
  type: z.string().optional(),
}).describe("Summary representation of a cluster (used in list responses)");
