/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

export const LifecycleRuleDataType = {
  LifecycleRules: "lifecycle_rules",
} as const;
export type LifecycleRuleDataType = ClosedEnum<typeof LifecycleRuleDataType>;

export const LifecycleRuleDataType$zodSchema = z.enum([
  "lifecycle_rules",
]);

export type LifecycleRuleDataAttributes = {
  name?: string | undefined;
  enabled?: boolean | undefined;
  prefix?: string | null | undefined;
  expiration_days?: number | undefined;
  noncurrent_days?: number | null | undefined;
  abort_mpu_days_after_initiation?: number | null | undefined;
};

export const LifecycleRuleDataAttributes$zodSchema: z.ZodType<
  LifecycleRuleDataAttributes
> = z.object({
  abort_mpu_days_after_initiation: z.int().nullable().optional().describe(
    "Number of days after initiation to abort incomplete multipart uploads",
  ),
  enabled: z.boolean().optional().describe(
    "Whether the rule is currently active",
  ),
  expiration_days: z.int().optional().describe(
    "Number of days after object creation when the object expires and is automatically deleted",
  ),
  name: z.string().optional().describe("Name of the lifecycle rule"),
  noncurrent_days: z.int().nullable().optional().describe(
    "Number of days after which noncurrent object versions expire (for versioned buckets)",
  ),
  prefix: z.string().nullable().optional().describe(
    "Object key prefix filter. When set, the rule only applies to objects whose keys start with this prefix.",
  ),
});

export type LifecycleRuleData = {
  id?: string | undefined;
  type?: LifecycleRuleDataType | undefined;
  attributes?: LifecycleRuleDataAttributes | undefined;
};

export const LifecycleRuleData$zodSchema: z.ZodType<LifecycleRuleData> = z
  .object({
    attributes: z.lazy(() => LifecycleRuleDataAttributes$zodSchema).optional(),
    id: z.string().optional().describe(
      "Lifecycle rule ID with lifecycle_ prefix",
    ),
    type: LifecycleRuleDataType$zodSchema.optional(),
  });
