/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ErrorObject, ErrorObject$zodSchema } from "./errorobject.js";
import {
  VirtualMachineRestores,
  VirtualMachineRestores$zodSchema,
} from "./virtualmachinerestores.js";

export type ListBackupRestoresRequest = { backup_id: string };

export const ListBackupRestoresRequest$zodSchema: z.ZodType<
  ListBackupRestoresRequest
> = z.object({
  backup_id: z.string(),
});

export type ListBackupRestoresResponse = VirtualMachineRestores | ErrorObject;

export const ListBackupRestoresResponse$zodSchema: z.ZodType<
  ListBackupRestoresResponse
> = z.union([
  VirtualMachineRestores$zodSchema,
  ErrorObject$zodSchema,
]);
