/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ErrorObject, ErrorObject$zodSchema } from "./errorobject.js";
import {
  LksKubernetesVersions,
  LksKubernetesVersions$zodSchema,
} from "./lkskubernetesversions.js";

export type ListLksAvailableVersionsResponse =
  | LksKubernetesVersions
  | ErrorObject;

export const ListLksAvailableVersionsResponse$zodSchema: z.ZodType<
  ListLksAvailableVersionsResponse
> = z.union([
  LksKubernetesVersions$zodSchema,
  ErrorObject$zodSchema,
]);
