/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type ListManagedDatabasesRequest = {
  project_id: string;
  engine?: string | undefined;
};

export const ListManagedDatabasesRequest$zodSchema: z.ZodType<
  ListManagedDatabasesRequest
> = z.object({
  engine: z.string().describe("Filter by database engine").optional(),
  project_id: z.string().describe("The project slug to filter databases by"),
});
