/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ErrorObject, ErrorObject$zodSchema } from "./errorobject.js";
import { LksSites, LksSites$zodSchema } from "./lkssites.js";

export type ListLksSitesResponse = LksSites | ErrorObject;

export const ListLksSitesResponse$zodSchema: z.ZodType<ListLksSitesResponse> = z
  .union([
    LksSites$zodSchema,
    ErrorObject$zodSchema,
  ]);
