/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ErrorObject, ErrorObject$zodSchema } from "./errorobject.js";
import { LksClusters, LksClusters$zodSchema } from "./lksclusters.js";

export type ListLksClustersRequest = { project_id: string };

export const ListLksClustersRequest$zodSchema: z.ZodType<
  ListLksClustersRequest
> = z.object({
  project_id: z.string().describe(
    "Project `id_hash` or slug. Required — clusters are always scoped to a project.",
  ),
});

export type ListLksClustersResponse = LksClusters | ErrorObject;

export const ListLksClustersResponse$zodSchema: z.ZodType<
  ListLksClustersResponse
> = z.union([
  LksClusters$zodSchema,
  ErrorObject$zodSchema,
]);
