/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { LksClusterData, LksClusterData$zodSchema } from "./lksclusterdata.js";

export type LksCluster = { data?: LksClusterData | undefined };

export const LksCluster$zodSchema: z.ZodType<LksCluster> = z.object({
  data: LksClusterData$zodSchema.optional(),
});
