/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  LksKubernetesVersionData,
  LksKubernetesVersionData$zodSchema,
} from "./lkskubernetesversiondata.js";

export type LksKubernetesVersions = {
  data?: Array<LksKubernetesVersionData> | undefined;
};

export const LksKubernetesVersions$zodSchema: z.ZodType<LksKubernetesVersions> =
  z.object({
    data: z.array(LksKubernetesVersionData$zodSchema).optional(),
  });
