/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";
import { ProjectInclude, ProjectInclude$zodSchema } from "./projectinclude.js";
import { TeamInclude, TeamInclude$zodSchema } from "./teaminclude.js";

export const ManagedDatabaseAttributesType = {
  ManagedDatabases: "managed_databases",
} as const;
export type ManagedDatabaseAttributesType = ClosedEnum<
  typeof ManagedDatabaseAttributesType
>;

export const ManagedDatabaseAttributesType$zodSchema = z.enum([
  "managed_databases",
]);

export type ManagedDatabaseAttributesSpecs = {
  cpu?: number | null | undefined;
  memory?: number | null | undefined;
  storage?: number | null | undefined;
  shards?: number | null | undefined;
  replicas?: number | null | undefined;
  iops?: string | null | undefined;
};

export const ManagedDatabaseAttributesSpecs$zodSchema: z.ZodType<
  ManagedDatabaseAttributesSpecs
> = z.object({
  cpu: z.int().nullable().optional(),
  iops: z.string().nullable().optional(),
  memory: z.int().nullable().optional(),
  replicas: z.int().nullable().optional(),
  shards: z.int().nullable().optional(),
  storage: z.int().nullable().optional(),
});

export type ManagedDatabaseAttributesSite = {
  id?: string | undefined;
  name?: string | undefined;
  slug?: string | undefined;
  facility?: string | undefined;
};

export const ManagedDatabaseAttributesSite$zodSchema: z.ZodType<
  ManagedDatabaseAttributesSite
> = z.object({
  facility: z.string().optional(),
  id: z.string().optional(),
  name: z.string().optional(),
  slug: z.string().optional(),
});

export type ManagedDatabaseAttributesRegion = {
  city?: string | null | undefined;
  country?: string | null | undefined;
  site?: ManagedDatabaseAttributesSite | null | undefined;
};

export const ManagedDatabaseAttributesRegion$zodSchema: z.ZodType<
  ManagedDatabaseAttributesRegion
> = z.object({
  city: z.string().nullable().optional(),
  country: z.string().nullable().optional(),
  site: z.lazy(() => ManagedDatabaseAttributesSite$zodSchema).nullable()
    .optional(),
});

export type ManagedDatabaseAttributesPlan = {
  id?: string | undefined;
  name?: string | null | undefined;
  slug?: string | null | undefined;
  billing?: string | undefined;
};

export const ManagedDatabaseAttributesPlan$zodSchema: z.ZodType<
  ManagedDatabaseAttributesPlan
> = z.object({
  billing: z.string().optional(),
  id: z.string().optional(),
  name: z.string().nullable().optional(),
  slug: z.string().nullable().optional(),
});

export type ManagedDatabaseAttributesCredentials = {
  host?: string | undefined;
  http_port?: number | null | undefined;
  tcp_port?: number | null | undefined;
  port?: number | null | undefined;
  database?: string | null | undefined;
  url?: string | null | undefined;
  username?: string | undefined;
  password?: string | null | undefined;
};

export const ManagedDatabaseAttributesCredentials$zodSchema: z.ZodType<
  ManagedDatabaseAttributesCredentials
> = z.object({
  database: z.string().nullable().optional(),
  host: z.string().optional(),
  http_port: z.int().nullable().optional(),
  password: z.string().nullable().optional(),
  port: z.int().nullable().optional().describe("Postgres NodePort"),
  tcp_port: z.int().nullable().optional(),
  url: z.string().nullable().optional().describe("Postgres connection string"),
  username: z.string().optional(),
});

export type ManagedDatabaseAttributesRecovery = {
  enabled?: boolean | null | undefined;
};

export const ManagedDatabaseAttributesRecovery$zodSchema: z.ZodType<
  ManagedDatabaseAttributesRecovery
> = z.object({
  enabled: z.boolean().nullable().optional(),
});

export type Supabase = { enabled?: boolean | undefined };

export const Supabase$zodSchema: z.ZodType<Supabase> = z.object({
  enabled: z.boolean().optional(),
});

export type ManagedDatabaseAttributesAttributes = {
  name?: string | undefined;
  engine?: string | undefined;
  status?: string | undefined;
  namespace?: string | null | undefined;
  created_at?: string | null | undefined;
  specs?: ManagedDatabaseAttributesSpecs | null | undefined;
  region?: ManagedDatabaseAttributesRegion | undefined;
  plan?: ManagedDatabaseAttributesPlan | undefined;
  team?: TeamInclude | undefined;
  project?: ProjectInclude | undefined;
  trusted_sources?: Array<string> | undefined;
  play_url?: string | null | undefined;
  credentials?: ManagedDatabaseAttributesCredentials | null | undefined;
  parameters?: { [k: string]: string } | undefined;
  pooler?: { [k: string]: any } | undefined;
  backup?: { [k: string]: any } | undefined;
  recovery?: ManagedDatabaseAttributesRecovery | undefined;
  supabase?: Supabase | undefined;
};

export const ManagedDatabaseAttributesAttributes$zodSchema: z.ZodType<
  ManagedDatabaseAttributesAttributes
> = z.object({
  backup: z.record(z.string(), z.any()).optional().describe(
    "Scheduled backup configuration",
  ),
  created_at: z.string().nullable().optional(),
  credentials: z.lazy(() => ManagedDatabaseAttributesCredentials$zodSchema)
    .nullable().optional(),
  engine: z.string().optional(),
  name: z.string().optional(),
  namespace: z.string().nullable().optional(),
  parameters: z.record(z.string(), z.string()).optional().describe(
    "Custom PostgreSQL parameters",
  ),
  plan: z.lazy(() => ManagedDatabaseAttributesPlan$zodSchema).optional(),
  play_url: z.string().nullable().optional(),
  pooler: z.record(z.string(), z.any()).optional().describe(
    "PgBouncer pooler configuration",
  ),
  project: ProjectInclude$zodSchema.optional(),
  recovery: z.lazy(() => ManagedDatabaseAttributesRecovery$zodSchema)
    .optional(),
  region: z.lazy(() => ManagedDatabaseAttributesRegion$zodSchema).optional(),
  specs: z.lazy(() => ManagedDatabaseAttributesSpecs$zodSchema).nullable()
    .optional(),
  status: z.string().optional(),
  supabase: z.lazy(() => Supabase$zodSchema).optional(),
  team: TeamInclude$zodSchema.optional(),
  trusted_sources: z.array(z.string()).optional().describe(
    "Array of CIDR addresses allowed to connect",
  ),
});

export type ManagedDatabaseAttributes = {
  id?: string | undefined;
  type?: ManagedDatabaseAttributesType | undefined;
  attributes?: ManagedDatabaseAttributesAttributes | undefined;
};

export const ManagedDatabaseAttributes$zodSchema: z.ZodType<
  ManagedDatabaseAttributes
> = z.object({
  attributes: z.lazy(() => ManagedDatabaseAttributesAttributes$zodSchema)
    .optional(),
  id: z.string().optional(),
  type: ManagedDatabaseAttributesType$zodSchema.optional(),
});
