/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  ManagedDatabaseAttributes,
  ManagedDatabaseAttributes$zodSchema,
} from "./manageddatabaseattributes.js";

export type ManagedDatabase = { data?: ManagedDatabaseAttributes | undefined };

export const ManagedDatabase$zodSchema: z.ZodType<ManagedDatabase> = z.object({
  data: ManagedDatabaseAttributes$zodSchema.optional(),
});
