/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

export const MembershipRole = {
  Owner: "owner",
  Administrator: "administrator",
  Collaborator: "collaborator",
  Billing: "billing",
} as const;
export type MembershipRole = ClosedEnum<typeof MembershipRole>;

export const MembershipRole$zodSchema = z.enum([
  "owner",
  "administrator",
  "collaborator",
  "billing",
]);

export type MembershipAttributes = {
  first_name?: string | undefined;
  last_name?: string | undefined;
  email?: string | undefined;
  role?: MembershipRole | undefined;
  mfa_enabled?: boolean | undefined;
  created_at?: string | undefined;
  updated_at?: string | undefined;
  last_login_at?: string | undefined;
};

export const MembershipAttributes$zodSchema: z.ZodType<MembershipAttributes> = z
  .object({
    created_at: z.iso.datetime({ offset: true }).optional(),
    email: z.string().optional(),
    first_name: z.string().optional(),
    last_login_at: z.iso.datetime({ offset: true }).optional(),
    last_name: z.string().optional(),
    mfa_enabled: z.boolean().optional(),
    role: MembershipRole$zodSchema.optional(),
    updated_at: z.iso.datetime({ offset: true }).optional(),
  });

export type MembershipData = {
  id?: string | undefined;
  attributes?: MembershipAttributes | undefined;
};

export const MembershipData$zodSchema: z.ZodType<MembershipData> = z.object({
  attributes: z.lazy(() => MembershipAttributes$zodSchema).optional(),
  id: z.string().optional(),
});

export type Membership = { data?: MembershipData | undefined };

export const Membership$zodSchema: z.ZodType<Membership> = z.object({
  data: z.lazy(() => MembershipData$zodSchema).optional(),
});
