/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type Total = { count?: number | undefined };

export const Total$zodSchema: z.ZodType<Total> = z.object({
  count: z.int().optional().describe(
    "Total number of records, returned when `stats[total]=count` is requested",
  ),
});

export type PaginationMetaStats = { total?: Total | undefined };

export const PaginationMetaStats$zodSchema: z.ZodType<PaginationMetaStats> = z
  .object({
    total: z.lazy(() => Total$zodSchema).optional(),
  });

export type PaginationMeta = { stats?: PaginationMetaStats | undefined };

export const PaginationMeta$zodSchema: z.ZodType<PaginationMeta> = z.object({
  stats: z.lazy(() => PaginationMetaStats$zodSchema).optional(),
});
