/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";
import { UserUpdate, UserUpdate$zodSchema } from "./userupdate.js";

export const PatchUserProfileType2 = {
  Users: "users",
} as const;
export type PatchUserProfileType2 = ClosedEnum<typeof PatchUserProfileType2>;

export const PatchUserProfileType2$zodSchema = z.enum([
  "users",
]);

export const PatchUserProfileRole2 = {
  Administrator: "administrator",
  Billing: "billing",
  Collaborator: "collaborator",
  Owner: "owner",
} as const;
export type PatchUserProfileRole2 = ClosedEnum<typeof PatchUserProfileRole2>;

export const PatchUserProfileRole2$zodSchema = z.enum([
  "administrator",
  "billing",
  "collaborator",
  "owner",
]);

export type PatchUserProfileAttributes2 = {
  first_name?: string | undefined;
  last_name?: string | undefined;
  role?: PatchUserProfileRole2 | undefined;
};

export const PatchUserProfileAttributes2$zodSchema: z.ZodType<
  PatchUserProfileAttributes2
> = z.object({
  first_name: z.string().optional(),
  last_name: z.string().optional(),
  role: PatchUserProfileRole2$zodSchema.optional(),
});

export type PatchUserProfileData2 = {
  id: string;
  type: PatchUserProfileType2;
  attributes?: PatchUserProfileAttributes2 | undefined;
};

export const PatchUserProfileData2$zodSchema: z.ZodType<PatchUserProfileData2> =
  z.object({
    attributes: z.lazy(() => PatchUserProfileAttributes2$zodSchema).optional(),
    id: z.string(),
    type: PatchUserProfileType2$zodSchema,
  });

export type PatchUserProfileRequestBody2 = { data: PatchUserProfileData2 };

export const PatchUserProfileRequestBody2$zodSchema: z.ZodType<
  PatchUserProfileRequestBody2
> = z.object({
  data: z.lazy(() => PatchUserProfileData2$zodSchema),
});

export type PatchUserProfileRequest = {
  id: string;
  RequestBody: PatchUserProfileRequestBody2;
};

export const PatchUserProfileRequest$zodSchema: z.ZodType<
  PatchUserProfileRequest
> = z.object({
  RequestBody: z.lazy(() => PatchUserProfileRequestBody2$zodSchema),
  id: z.string(),
});

/**
 * Success
 */
export type PatchUserProfileResponseBody = { data?: UserUpdate | undefined };

export const PatchUserProfileResponseBody$zodSchema: z.ZodType<
  PatchUserProfileResponseBody
> = z.object({
  data: UserUpdate$zodSchema.optional(),
}).describe("Success");

export type PatchUserProfileResponse = {
  ContentType: string;
  StatusCode: number;
  RawResponse: Response;
  object?: PatchUserProfileResponseBody | undefined;
};

export const PatchUserProfileResponse$zodSchema: z.ZodType<
  PatchUserProfileResponse
> = z.object({
  ContentType: z.string(),
  RawResponse: z.custom<Response>(x => x instanceof Response),
  StatusCode: z.int(),
  object: z.lazy(() => PatchUserProfileResponseBody$zodSchema).optional(),
});
