/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { PlanData, PlanData$zodSchema } from "./plandata.js";

export type Plan = { data?: PlanData | undefined };

export const Plan$zodSchema: z.ZodType<Plan, z.ZodTypeDef, unknown> = z.object({
  data: PlanData$zodSchema.optional(),
});
