/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ApiKey, ApiKey$zodSchema } from "./apikey.js";

/**
 * Created
 */
export type PostApiKeyResponse = { data?: ApiKey | undefined };

export const PostApiKeyResponse$zodSchema: z.ZodType<PostApiKeyResponse> = z
  .object({
    data: ApiKey$zodSchema.optional(),
  }).describe("Created");
