/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";
import { ErrorObject, ErrorObject$zodSchema } from "./errorobject.js";
import { VolumeData, VolumeData$zodSchema } from "./volumedata.js";

export const PostStorageVolumesType2 = {
  Volumes: "volumes",
} as const;
export type PostStorageVolumesType2 = ClosedEnum<
  typeof PostStorageVolumesType2
>;

export const PostStorageVolumesType2$zodSchema = z.enum([
  "volumes",
]);

export type PostStorageVolumesAttributes2 = {
  project: string;
  name: string;
  region: string;
  size_in_gb: number;
};

export const PostStorageVolumesAttributes2$zodSchema: z.ZodType<
  PostStorageVolumesAttributes2
> = z.object({
  name: z.string().describe("Volume name"),
  project: z.string().describe("Project ID or slug"),
  region: z.string().describe(
    "Region (site) slug where the volume is provisioned",
  ),
  size_in_gb: z.int().describe("Size in GB"),
});

export type PostStorageVolumesData2 = {
  type: PostStorageVolumesType2;
  attributes: PostStorageVolumesAttributes2;
};

export const PostStorageVolumesData2$zodSchema: z.ZodType<
  PostStorageVolumesData2
> = z.object({
  attributes: z.lazy(() => PostStorageVolumesAttributes2$zodSchema),
  type: PostStorageVolumesType2$zodSchema,
});

export type PostStorageVolumesRequest = { data: PostStorageVolumesData2 };

export const PostStorageVolumesRequest$zodSchema: z.ZodType<
  PostStorageVolumesRequest
> = z.object({
  data: z.lazy(() => PostStorageVolumesData2$zodSchema),
});

/**
 * Created
 */
export type PostStorageVolumesResponseBody = { data?: VolumeData | undefined };

export const PostStorageVolumesResponseBody$zodSchema: z.ZodType<
  PostStorageVolumesResponseBody
> = z.object({
  data: VolumeData$zodSchema.optional(),
}).describe("Created");

export type PostStorageVolumesResponse =
  | PostStorageVolumesResponseBody
  | ErrorObject;

export const PostStorageVolumesResponse$zodSchema: z.ZodType<
  PostStorageVolumesResponse
> = z.union([
  z.lazy(() => PostStorageVolumesResponseBody$zodSchema),
  ErrorObject$zodSchema,
]);
