/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

export const PostStorageVolumesMountType = {
  Volumes: "volumes",
} as const;
export type PostStorageVolumesMountType = ClosedEnum<
  typeof PostStorageVolumesMountType
>;

export const PostStorageVolumesMountType$zodSchema = z.enum([
  "volumes",
]);

export type PostStorageVolumesMountAttributes = { nqn: string };

export const PostStorageVolumesMountAttributes$zodSchema: z.ZodType<
  PostStorageVolumesMountAttributes
> = z.object({
  nqn: z.string().describe(
    "NVMe Qualified Name (NQN) of the client/server that will access the volume. Format: nqn.YYYY-MM.domain:identifier (e.g., \"nqn.2024-01.com.example:server01\"). This uniquely identifies the NVMe client and must be configured on the client server.",
  ),
});

export type PostStorageVolumesMountData = {
  type: PostStorageVolumesMountType;
  attributes: PostStorageVolumesMountAttributes;
};

export const PostStorageVolumesMountData$zodSchema: z.ZodType<
  PostStorageVolumesMountData
> = z.object({
  attributes: z.lazy(() => PostStorageVolumesMountAttributes$zodSchema),
  type: PostStorageVolumesMountType$zodSchema,
});

export type PostStorageVolumesMountRequestBody = {
  data: PostStorageVolumesMountData;
};

export const PostStorageVolumesMountRequestBody$zodSchema: z.ZodType<
  PostStorageVolumesMountRequestBody
> = z.object({
  data: z.lazy(() => PostStorageVolumesMountData$zodSchema),
});

export type PostStorageVolumesMountRequest = {
  id: string;
  RequestBody: PostStorageVolumesMountRequestBody;
};

export const PostStorageVolumesMountRequest$zodSchema: z.ZodType<
  PostStorageVolumesMountRequest
> = z.object({
  RequestBody: z.lazy(() => PostStorageVolumesMountRequestBody$zodSchema),
  id: z.string().describe("Volume ID"),
});
