/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { catchUnrecognizedEnum, ClosedEnum, OpenEnum } from "../types/enums.js";

export const PostVpnSessionType2 = {
  VpnSessions: "vpn_sessions",
} as const;
export type PostVpnSessionType2 = ClosedEnum<typeof PostVpnSessionType2>;

export const PostVpnSessionType2$zodSchema = z.enum([
  "vpn_sessions",
]);

export const PostVpnSessionSite2 = {
  Ams: "AMS",
  Ash: "ASH",
  Ash2: "ASH2",
  Bgt: "BGT",
  Bue: "BUE",
  Chi: "CHI",
  Dal: "DAL",
  Fra: "FRA",
  Fra2: "FRA2",
  Lax: "LAX",
  Lax2: "LAX2",
  Lon: "LON",
  Lon2: "LON2",
  Mex2: "MEX2",
  Mia2: "MIA2",
  Nyc: "NYC",
  San3: "SAN3",
  Sao: "SAO",
  Sao2: "SAO2",
  Sgp: "SGP",
  Sjc2: "SJC2",
  Syd: "SYD",
  Syd2: "SYD2",
  Tor: "TOR",
  Tyo3: "TYO3",
  Tyo4: "TYO4",
} as const;
export type PostVpnSessionSite2 = OpenEnum<typeof PostVpnSessionSite2>;

export const PostVpnSessionSite2$zodSchema = z.union([
  z.enum([
    "AMS",
    "ASH",
    "ASH2",
    "BGT",
    "BUE",
    "CHI",
    "DAL",
    "FRA",
    "FRA2",
    "LAX",
    "LAX2",
    "LON",
    "LON2",
    "MEX2",
    "MIA2",
    "NYC",
    "SAN3",
    "SAO",
    "SAO2",
    "SGP",
    "SJC2",
    "SYD",
    "SYD2",
    "TOR",
    "TYO3",
    "TYO4",
  ]),
  z.string().transform(catchUnrecognizedEnum),
]);

export type PostVpnSessionAttributes2 = {
  site: PostVpnSessionSite2;
  server_id: string;
};

export const PostVpnSessionAttributes2$zodSchema: z.ZodType<
  PostVpnSessionAttributes2
> = z.object({
  server_id: z.string(),
  site: PostVpnSessionSite2$zodSchema,
});

export type PostVpnSessionData2 = {
  type?: PostVpnSessionType2 | undefined;
  attributes?: PostVpnSessionAttributes2 | undefined;
};

export const PostVpnSessionData2$zodSchema: z.ZodType<PostVpnSessionData2> = z
  .object({
    attributes: z.lazy(() => PostVpnSessionAttributes2$zodSchema).optional(),
    type: PostVpnSessionType2$zodSchema.optional(),
  });

export type PostVpnSessionRequest = { data?: PostVpnSessionData2 | undefined };

export const PostVpnSessionRequest$zodSchema: z.ZodType<PostVpnSessionRequest> =
  z.object({
    data: z.lazy(() => PostVpnSessionData2$zodSchema).optional(),
  });
