/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { VolumeData, VolumeData$zodSchema } from "./volumedata.js";

export const PostStorageVolumesType2$zodSchema = z.enum([
  "volumes",
]);

export type PostStorageVolumesType2 = z.infer<
  typeof PostStorageVolumesType2$zodSchema
>;

export type PostStorageVolumesAttributes2 = {
  project: string;
  name: string;
  size_in_gb?: number | undefined;
};

export const PostStorageVolumesAttributes2$zodSchema: z.ZodType<
  PostStorageVolumesAttributes2,
  z.ZodTypeDef,
  unknown
> = z.object({
  name: z.string(),
  project: z.string(),
  size_in_gb: z.number().int().default(1500),
});

export type PostStorageVolumesData2 = {
  type: PostStorageVolumesType2;
  attributes: PostStorageVolumesAttributes2;
};

export const PostStorageVolumesData2$zodSchema: z.ZodType<
  PostStorageVolumesData2,
  z.ZodTypeDef,
  unknown
> = z.object({
  attributes: z.lazy(() => PostStorageVolumesAttributes2$zodSchema),
  type: PostStorageVolumesType2$zodSchema,
});

export type PostStorageVolumesRequest = { data: PostStorageVolumesData2 };

export const PostStorageVolumesRequest$zodSchema: z.ZodType<
  PostStorageVolumesRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  data: z.lazy(() => PostStorageVolumesData2$zodSchema),
});

/**
 * Created
 */
export type PostStorageVolumesResponseBody = { data?: VolumeData | undefined };

export const PostStorageVolumesResponseBody$zodSchema: z.ZodType<
  PostStorageVolumesResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  data: VolumeData$zodSchema.optional(),
}).describe("Created");

export type PostStorageVolumesResponse = {
  ContentType: string;
  StatusCode: number;
  RawResponse: Response;
  object?: PostStorageVolumesResponseBody | undefined;
};

export const PostStorageVolumesResponse$zodSchema: z.ZodType<
  PostStorageVolumesResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  ContentType: z.string(),
  RawResponse: z.instanceof(Response),
  StatusCode: z.number().int(),
  object: z.lazy(() => PostStorageVolumesResponseBody$zodSchema).optional(),
});
