/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";
import { ErrorObject, ErrorObject$zodSchema } from "./errorobject.js";
import {
  ObjectStorageData,
  ObjectStorageData$zodSchema,
} from "./objectstoragedata.js";

export const PostStorageBucketsType = {
  Objects: "objects",
} as const;
export type PostStorageBucketsType = ClosedEnum<typeof PostStorageBucketsType>;

export const PostStorageBucketsType$zodSchema = z.enum([
  "objects",
]);

/**
 * Backend storage tier. `standard` is the default S3-compatible tier. `high_performance` is a lower-latency, higher-throughput tier available in select regions only.
 */
export const PostStorageBucketsStorageClass = {
  Standard: "standard",
  HighPerformance: "high_performance",
} as const;
/**
 * Backend storage tier. `standard` is the default S3-compatible tier. `high_performance` is a lower-latency, higher-throughput tier available in select regions only.
 */
export type PostStorageBucketsStorageClass = ClosedEnum<
  typeof PostStorageBucketsStorageClass
>;

export const PostStorageBucketsStorageClass$zodSchema = z.enum([
  "standard",
  "high_performance",
]).describe(
  "Backend storage tier. `standard` is the default S3-compatible tier. `high_performance` is a lower-latency, higher-throughput tier available in select regions only.",
);

/**
 * Object Lock retention mode applied to new objects. `GOVERNANCE` allows privileged users to override the retention; `COMPLIANCE` cannot be overridden by anyone. Only applies when `locking` is `true`.
 */
export const PostStorageBucketsRetentionMode = {
  None: "NONE",
  Compliance: "COMPLIANCE",
  Governance: "GOVERNANCE",
} as const;
/**
 * Object Lock retention mode applied to new objects. `GOVERNANCE` allows privileged users to override the retention; `COMPLIANCE` cannot be overridden by anyone. Only applies when `locking` is `true`.
 */
export type PostStorageBucketsRetentionMode = ClosedEnum<
  typeof PostStorageBucketsRetentionMode
>;

export const PostStorageBucketsRetentionMode$zodSchema = z.enum([
  "NONE",
  "COMPLIANCE",
  "GOVERNANCE",
]).describe(
  "Object Lock retention mode applied to new objects. `GOVERNANCE` allows privileged users to override the retention; `COMPLIANCE` cannot be overridden by anyone. Only applies when `locking` is `true`.",
);

export type PostStorageBucketsAttributes = {
  project: string;
  name: string;
  region: string;
  scoped?: boolean | undefined;
  customer?: string | undefined;
  storage_class?: PostStorageBucketsStorageClass | undefined;
  versioning?: boolean | undefined;
  locking?: boolean | undefined;
  retention_mode?: PostStorageBucketsRetentionMode | undefined;
  retention_period?: number | null | undefined;
};

export const PostStorageBucketsAttributes$zodSchema: z.ZodType<
  PostStorageBucketsAttributes
> = z.object({
  customer: z.string().optional().describe(
    "Customer identifier for scoped storage. Used when `scoped` is true to create customer-specific bucket isolation.",
  ),
  locking: z.boolean().default(false).describe(
    "Enable S3 Object Lock (WORM). Must be enabled at bucket creation; cannot be added to an existing bucket. When `locking` is `true`, `versioning` is automatically enabled.",
  ),
  name: z.string().describe(
    "Object storage name. Cannot contain special characters or spaces.",
  ),
  project: z.string().describe("Project ID or slug"),
  region: z.string().describe(
    "Site slug representing the region (e.g., DAL, SAO2)",
  ),
  retention_mode: PostStorageBucketsRetentionMode$zodSchema.default("NONE")
    .describe(
      "Object Lock retention mode applied to new objects. `GOVERNANCE` allows privileged users to override the retention; `COMPLIANCE` cannot be overridden by anyone. Only applies when `locking` is `true`.",
    ),
  retention_period: z.int().nullable().optional().describe(
    "Default retention period, in days, applied to new objects when Object Lock is enabled. Only applies when `locking` is `true`.",
  ),
  scoped: z.boolean().default(false).describe(
    "Whether to create a scoped storage bucket. When true, the bucket is isolated to a specific customer context. Defaults to false.",
  ),
  storage_class: PostStorageBucketsStorageClass$zodSchema.default("standard")
    .describe(
      "Backend storage tier. `standard` is the default S3-compatible tier. `high_performance` is a lower-latency, higher-throughput tier available in select regions only.",
    ),
  versioning: z.boolean().default(false).describe(
    "Enable S3 object versioning. Once enabled, versioning cannot be disabled.",
  ),
});

export type PostStorageBucketsData = {
  type: PostStorageBucketsType;
  attributes: PostStorageBucketsAttributes;
};

export const PostStorageBucketsData$zodSchema: z.ZodType<
  PostStorageBucketsData
> = z.object({
  attributes: z.lazy(() => PostStorageBucketsAttributes$zodSchema),
  type: PostStorageBucketsType$zodSchema,
});

export type PostStorageBucketsRequest = { data: PostStorageBucketsData };

export const PostStorageBucketsRequest$zodSchema: z.ZodType<
  PostStorageBucketsRequest
> = z.object({
  data: z.lazy(() => PostStorageBucketsData$zodSchema),
});

/**
 * Created
 */
export type PostStorageBucketsResponseBody = {
  data?: ObjectStorageData | undefined;
};

export const PostStorageBucketsResponseBody$zodSchema: z.ZodType<
  PostStorageBucketsResponseBody
> = z.object({
  data: ObjectStorageData$zodSchema.optional(),
}).describe("Created");

export type PostStorageBucketsResponse =
  | PostStorageBucketsResponseBody
  | ErrorObject;

export const PostStorageBucketsResponse$zodSchema: z.ZodType<
  PostStorageBucketsResponse
> = z.union([
  z.lazy(() => PostStorageBucketsResponseBody$zodSchema),
  ErrorObject$zodSchema,
]);
