/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";
import { TeamInclude, TeamInclude$zodSchema } from "./teaminclude.js";

export const BillingType = {
  Yearly: "Yearly",
  Monthly: "Monthly",
  Hourly: "Hourly",
  Normal: "Normal",
  Custom: "Custom",
} as const;
export type BillingType = ClosedEnum<typeof BillingType>;

export const BillingType$zodSchema = z.enum([
  "Yearly",
  "Monthly",
  "Hourly",
  "Normal",
  "Custom",
]);

export const BillingMethod = {
  Normal: "Normal",
  NinetyFivethPercentile: "95th percentile",
} as const;
export type BillingMethod = ClosedEnum<typeof BillingMethod>;

export const BillingMethod$zodSchema = z.enum([
  "Normal",
  "95th percentile",
]);

export const Environment = {
  Development: "Development",
  Staging: "Staging",
  Production: "Production",
} as const;
export type Environment = ClosedEnum<typeof Environment>;

export const Environment$zodSchema = z.enum([
  "Development",
  "Staging",
  "Production",
]);

export type ProjectStats = {
  ip_addresses?: number | undefined;
  prefixes?: number | undefined;
  servers?: number | undefined;
  containers?: number | undefined;
  vlans?: number | undefined;
};

export const ProjectStats$zodSchema: z.ZodType<ProjectStats> = z.object({
  containers: z.number().optional().describe(
    "The number of containers assigned to the project",
  ),
  ip_addresses: z.number().optional().describe(
    "The number of IP addresses assigned to the project",
  ),
  prefixes: z.number().optional().describe(
    "The IP address prefixes in the project",
  ),
  servers: z.number().optional().describe(
    "The number of servers assigned to the project",
  ),
  vlans: z.number().optional().describe(
    "The number of VLANs assigned to the project",
  ),
});

export type ProjectBilling = {
  subscription_id?: string | undefined;
  type?: string | undefined;
  method?: string | undefined;
};

export const ProjectBilling$zodSchema: z.ZodType<ProjectBilling> = z.object({
  method: z.string().optional(),
  subscription_id: z.string().optional(),
  type: z.string().optional(),
});

export type ProjectAttributes = {
  name?: string | undefined;
  slug?: string | undefined;
  description?: string | null | undefined;
  billing_type?: BillingType | null | undefined;
  billing_method?: BillingMethod | null | undefined;
  cost?: string | null | undefined;
  environment?: Environment | null | undefined;
  stats?: ProjectStats | undefined;
  billing?: ProjectBilling | undefined;
  team?: TeamInclude | undefined;
  created_at?: string | undefined;
  updated_at?: string | undefined;
};

export const ProjectAttributes$zodSchema: z.ZodType<ProjectAttributes> = z
  .object({
    billing: z.lazy(() => ProjectBilling$zodSchema).optional(),
    billing_method: BillingMethod$zodSchema.nullable().optional(),
    billing_type: BillingType$zodSchema.nullable().optional(),
    cost: z.string().nullable().optional(),
    created_at: z.string().optional(),
    description: z.string().nullable().optional().describe(
      "The project description",
    ),
    environment: Environment$zodSchema.nullable().optional(),
    name: z.string().optional().describe("The project name"),
    slug: z.string().optional().describe("A unique project identifier"),
    stats: z.lazy(() => ProjectStats$zodSchema).optional(),
    team: TeamInclude$zodSchema.optional(),
    updated_at: z.string().optional(),
  });

export type Project = {
  id?: string | undefined;
  attributes?: ProjectAttributes | undefined;
};

export const Project$zodSchema: z.ZodType<Project> = z.object({
  attributes: z.lazy(() => ProjectAttributes$zodSchema).optional(),
  id: z.string().optional().describe("The project ID"),
});
