/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type ProjectIncludeBilling = {
  subscription_id?: string | undefined;
  type?: string | undefined;
  method?: string | undefined;
};

export const ProjectIncludeBilling$zodSchema: z.ZodType<
  ProjectIncludeBilling,
  z.ZodTypeDef,
  unknown
> = z.object({
  method: z.string().optional(),
  subscription_id: z.string().optional(),
  type: z.string().optional(),
});

export type ProjectIncludeStats = {
  ip_addresses?: number | undefined;
  prefixes?: number | undefined;
  servers?: number | undefined;
  vlans?: number | undefined;
};

export const ProjectIncludeStats$zodSchema: z.ZodType<
  ProjectIncludeStats,
  z.ZodTypeDef,
  unknown
> = z.object({
  ip_addresses: z.number().int().optional(),
  prefixes: z.number().int().optional(),
  servers: z.number().int().optional(),
  vlans: z.number().int().optional(),
});

export type ProjectInclude = {
  id?: string | undefined;
  name?: string | undefined;
  slug?: string | undefined;
  description?: string | undefined;
  billing_type?: string | undefined;
  provisioning_type?: string | undefined;
  billing_method?: string | undefined;
  bandwidth_alert?: boolean | undefined;
  environment?: string | undefined;
  billing?: ProjectIncludeBilling | undefined;
  stats?: ProjectIncludeStats | undefined;
};

export const ProjectInclude$zodSchema: z.ZodType<
  ProjectInclude,
  z.ZodTypeDef,
  unknown
> = z.object({
  bandwidth_alert: z.boolean().optional(),
  billing: z.lazy(() => ProjectIncludeBilling$zodSchema).optional(),
  billing_method: z.string().optional(),
  billing_type: z.string().optional(),
  description: z.string().optional(),
  environment: z.string().optional(),
  id: z.string().optional(),
  name: z.string().optional(),
  provisioning_type: z.string().optional(),
  slug: z.string().optional(),
  stats: z.lazy(() => ProjectIncludeStats$zodSchema).optional(),
});
