/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  PublicNetworkData,
  PublicNetworkData$zodSchema,
} from "./publicnetworkdata.js";

export type PublicNetworksMeta = {};

export const PublicNetworksMeta$zodSchema: z.ZodType<PublicNetworksMeta> = z
  .object({});

export type PublicNetworks = {
  data?: Array<PublicNetworkData> | undefined;
  meta?: PublicNetworksMeta | undefined;
};

export const PublicNetworks$zodSchema: z.ZodType<PublicNetworks> = z.object({
  data: z.array(PublicNetworkData$zodSchema).optional(),
  meta: z.lazy(() => PublicNetworksMeta$zodSchema).optional(),
});
