/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  PublicNetworkData,
  PublicNetworkData$zodSchema,
} from "./publicnetworkdata.js";

export type PublicNetwork = { data?: PublicNetworkData | undefined };

export const PublicNetwork$zodSchema: z.ZodType<PublicNetwork> = z.object({
  data: PublicNetworkData$zodSchema.optional(),
});
