/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { VolumeData, VolumeData$zodSchema } from "./volumedata.js";

export type RetrieveVolumeRequest = { id: string };

export const RetrieveVolumeRequest$zodSchema: z.ZodType<RetrieveVolumeRequest> =
  z.object({
    id: z.string().describe("The volume ID"),
  });

/**
 * Success
 */
export type RetrieveVolumeResponse = { data?: VolumeData | undefined };

export const RetrieveVolumeResponse$zodSchema: z.ZodType<
  RetrieveVolumeResponse
> = z.object({
  data: VolumeData$zodSchema.optional(),
}).describe("Success");
