/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { RoleData, RoleData$zodSchema } from "./roledata.js";

export type RoleMeta = {};

export const RoleMeta$zodSchema: z.ZodType<RoleMeta, z.ZodTypeDef, unknown> = z
  .object({});

export type Role = { data?: RoleData | undefined; meta?: RoleMeta | undefined };

export const Role$zodSchema: z.ZodType<Role, z.ZodTypeDef, unknown> = z.object({
  data: RoleData$zodSchema.optional(),
  meta: z.lazy(() => RoleMeta$zodSchema).optional(),
});
