/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type ServerStartRescueModeRequest = { server_id: string };

export const ServerStartRescueModeRequest$zodSchema: z.ZodType<
  ServerStartRescueModeRequest
> = z.object({
  server_id: z.string(),
});
