/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

export const ServerScheduleDeletionType = {
  ScheduleDeletion: "schedule_deletion",
} as const;
export type ServerScheduleDeletionType = ClosedEnum<
  typeof ServerScheduleDeletionType
>;

export const ServerScheduleDeletionType$zodSchema = z.enum([
  "schedule_deletion",
]);

export type ServerScheduleDeletionAttributes = {
  server_id?: string | undefined;
  scheduled_deletion_at?: string | undefined;
};

export const ServerScheduleDeletionAttributes$zodSchema: z.ZodType<
  ServerScheduleDeletionAttributes
> = z.object({
  scheduled_deletion_at: z.string().optional(),
  server_id: z.string().optional(),
});

export type ServerScheduleDeletionData = {
  id?: string | undefined;
  type?: ServerScheduleDeletionType | undefined;
  attributes?: ServerScheduleDeletionAttributes | undefined;
};

export const ServerScheduleDeletionData$zodSchema: z.ZodType<
  ServerScheduleDeletionData
> = z.object({
  attributes: z.lazy(() => ServerScheduleDeletionAttributes$zodSchema)
    .optional(),
  id: z.string().optional(),
  type: ServerScheduleDeletionType$zodSchema.optional(),
});

export type ServerScheduleDeletion = {
  data?: ServerScheduleDeletionData | undefined;
};

export const ServerScheduleDeletion$zodSchema: z.ZodType<
  ServerScheduleDeletion
> = z.object({
  data: z.lazy(() => ServerScheduleDeletionData$zodSchema).optional(),
});
