/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { PaginationMeta, PaginationMeta$zodSchema } from "./paginationmeta.js";
import { ServerData, ServerData$zodSchema } from "./serverdata.js";

export type Servers = {
  data?: Array<ServerData> | undefined;
  meta?: PaginationMeta | undefined;
};

export const Servers$zodSchema: z.ZodType<Servers> = z.object({
  data: z.array(ServerData$zodSchema).optional(),
  meta: PaginationMeta$zodSchema.optional(),
});
