/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";
import { ProjectInclude, ProjectInclude$zodSchema } from "./projectinclude.js";
import {
  ServerRegionResourceData,
  ServerRegionResourceData$zodSchema,
} from "./serverregionresourcedata.js";
import { TeamInclude, TeamInclude$zodSchema } from "./teaminclude.js";

export const IpmiStatus = {
  Unavailable: "Unavailable",
  Intermittent: "Intermittent",
  Normal: "Normal",
} as const;
export type IpmiStatus = ClosedEnum<typeof IpmiStatus>;

export const IpmiStatus$zodSchema = z.enum([
  "Unavailable",
  "Intermittent",
  "Normal",
]);

export const ServerDataRole = {
  External: "external",
  Internal: "internal",
  Ipmi: "ipmi",
  Unknown: "unknown",
} as const;
export type ServerDataRole = ClosedEnum<typeof ServerDataRole>;

export const ServerDataRole$zodSchema = z.enum([
  "external",
  "internal",
  "ipmi",
  "unknown",
]);

export type ServerDataTag = {
  id?: string | undefined;
  name?: string | undefined;
  description?: string | null | undefined;
  color?: string | null | undefined;
};

export const ServerDataTag$zodSchema: z.ZodType<ServerDataTag> = z.object({
  color: z.string().nullable().optional(),
  description: z.string().nullable().optional(),
  id: z.string().optional(),
  name: z.string().optional(),
});

/**
 * **Preview.** Available to teams with public networks enabled. The public network this server is attached onto, or null. Fetch full details from GET /public_networks/{id}.
 */
export type ServerDataPublicNetwork = {
  id?: string | undefined;
  ipv4?: string | null | undefined;
  ipv6?: string | null | undefined;
};

export const ServerDataPublicNetwork$zodSchema: z.ZodType<
  ServerDataPublicNetwork
> = z.object({
  id: z.string().optional(),
  ipv4: z.string().nullable().optional(),
  ipv6: z.string().nullable().optional(),
}).describe(
  "**Preview.** Available to teams with public networks enabled. The public network this server is attached onto, or null. Fetch full details from GET /public_networks/{id}.",
);

export type ServerDataPlan = {
  id?: string | undefined;
  name?: string | undefined;
  slug?: string | undefined;
  billing?: string | null | undefined;
};

export const ServerDataPlan$zodSchema: z.ZodType<ServerDataPlan> = z.object({
  billing: z.string().nullable().optional().describe(
    "hourly/monthly pricing. Defaults to `hourly`. Appliable for `on_demand` projects only.",
  ),
  id: z.string().optional().describe("The plan ID"),
  name: z.string().optional().describe("The plan name"),
  slug: z.string().optional().describe("The plan slug"),
});

export type ServerDataFeatures = {
  raid?: boolean | undefined;
  ssh_keys?: boolean | undefined;
  user_data?: boolean | undefined;
  accelerate?: boolean | undefined;
  rescue?: boolean | undefined;
  workflow?: boolean | undefined;
};

export const ServerDataFeatures$zodSchema: z.ZodType<ServerDataFeatures> = z
  .object({
    accelerate: z.boolean().optional(),
    raid: z.boolean().optional(),
    rescue: z.boolean().optional(),
    ssh_keys: z.boolean().optional(),
    user_data: z.boolean().optional(),
    workflow: z.boolean().optional(),
  });

export type ServerDataDistro = {
  name?: string | undefined;
  slug?: string | undefined;
  series?: string | undefined;
};

export const ServerDataDistro$zodSchema: z.ZodType<ServerDataDistro> = z.object(
  {
    name: z.string().optional().describe("The OS Distro name"),
    series: z.string().optional().describe("The OS Distro Series"),
    slug: z.string().optional().describe("The OS Distro slug"),
  },
);

export type ServerDataOperatingSystem = {
  name?: string | undefined;
  slug?: string | undefined;
  version?: string | undefined;
  features?: ServerDataFeatures | undefined;
  distro?: ServerDataDistro | undefined;
};

export const ServerDataOperatingSystem$zodSchema: z.ZodType<
  ServerDataOperatingSystem
> = z.object({
  distro: z.lazy(() => ServerDataDistro$zodSchema).optional(),
  features: z.lazy(() => ServerDataFeatures$zodSchema).optional(),
  name: z.string().optional().describe("The OS name"),
  slug: z.string().optional().describe("The OS slug"),
  version: z.string().optional().describe("The OS description"),
});

export type ServerDataSpecs = {
  cpu?: string | undefined;
  disk?: string | undefined;
  ram?: string | undefined;
  nic?: string | undefined;
  gpu?: string | null | undefined;
};

export const ServerDataSpecs$zodSchema: z.ZodType<ServerDataSpecs> = z.object({
  cpu: z.string().optional().describe("CPU model"),
  disk: z.string().optional().describe(
    "Disk quantity and size in GB (e.g. 2 x 500GB)",
  ),
  gpu: z.string().nullable().optional().describe(
    "GPU model and quantity, if present",
  ),
  nic: z.string().optional().describe("NIC quantity and speed"),
  ram: z.string().optional().describe("RAM size in GB"),
});

export type Interface = {
  role?: ServerDataRole | undefined;
  name?: string | undefined;
  mac_address?: string | null | undefined;
  description?: string | undefined;
};

export const Interface$zodSchema: z.ZodType<Interface> = z.object({
  description: z.string().optional(),
  mac_address: z.string().nullable().optional(),
  name: z.string().optional(),
  role: ServerDataRole$zodSchema.optional(),
});

export type ServerDataSshKey = {
  id?: number | undefined;
  name?: string | undefined;
  fingerprint?: string | undefined;
  public_key?: string | undefined;
  created_at?: string | undefined;
  updated_at?: string | undefined;
  user_id?: string | undefined;
  group_id?: number | null | undefined;
};

export const ServerDataSshKey$zodSchema: z.ZodType<ServerDataSshKey> = z.object(
  {
    created_at: z.iso.datetime({ offset: true }).optional(),
    fingerprint: z.string().optional(),
    group_id: z.int().nullable().optional(),
    id: z.int().optional(),
    name: z.string().optional(),
    public_key: z.string().optional(),
    updated_at: z.iso.datetime({ offset: true }).optional(),
    user_id: z.string().optional(),
  },
);

/**
 * Latest provisioning credentials, lazy loaded. Request it with `extra_fields[servers]=credentials`. Empty when the latest provisioning has no valid credentials.
 */
export type ServerDataCredentials = {
  username?: string | null | undefined;
  password?: string | null | undefined;
  ssh_keys?: Array<ServerDataSshKey> | null | undefined;
  expires_at?: string | null | undefined;
};

export const ServerDataCredentials$zodSchema: z.ZodType<ServerDataCredentials> =
  z.object({
    expires_at: z.iso.datetime({ offset: true }).nullable().optional(),
    password: z.string().nullable().optional(),
    ssh_keys: z.array(z.lazy(() => ServerDataSshKey$zodSchema)).nullable()
      .optional(),
    username: z.string().nullable().optional(),
  }).describe(
    "Latest provisioning credentials, lazy loaded. Request it with `extra_fields[servers]=credentials`. Empty when the latest provisioning has no valid credentials.",
  );

export type ServerDataAttributes = {
  tags?: Array<ServerDataTag> | undefined;
  hostname?: string | undefined;
  label?: string | undefined;
  price?: number | null | undefined;
  status?: string | undefined;
  ipmi_status?: IpmiStatus | null | undefined;
  role?: string | undefined;
  public_network_eligible?: boolean | undefined;
  bgp_eligible?: boolean | undefined;
  bgp_deployed?: boolean | undefined;
  public_network?: ServerDataPublicNetwork | null | undefined;
  site?: string | undefined;
  locked?: boolean | undefined;
  legacy_network?: boolean | null | undefined;
  features?: Array<string> | null | undefined;
  rescue_allowed?: boolean | undefined;
  primary_ipv4?: string | null | undefined;
  primary_ipv6?: string | null | undefined;
  created_at?: string | null | undefined;
  scheduled_deletion_at?: string | null | undefined;
  plan?: ServerDataPlan | undefined;
  operating_system?: ServerDataOperatingSystem | undefined;
  region?: ServerRegionResourceData | undefined;
  specs?: ServerDataSpecs | undefined;
  interfaces?: Array<Interface> | undefined;
  credentials?: ServerDataCredentials | null | undefined;
  project?: ProjectInclude | undefined;
  team?: TeamInclude | undefined;
};

export const ServerDataAttributes$zodSchema: z.ZodType<ServerDataAttributes> = z
  .object({
    bgp_deployed: z.boolean().optional().describe(
      "Whether the server was deployed with the BGP option.",
    ),
    bgp_eligible: z.boolean().optional().describe(
      "Whether the server can announce a BGP Elastic IP. Lazy loaded; request it with `extra_fields[servers]=bgp_eligible`.",
    ),
    created_at: z.string().nullable().optional(),
    credentials: z.lazy(() => ServerDataCredentials$zodSchema).nullable()
      .optional().describe(
        "Latest provisioning credentials, lazy loaded. Request it with `extra_fields[servers]=credentials`. Empty when the latest provisioning has no valid credentials.",
      ),
    features: z.array(z.string()).nullable().optional().describe(
      "Feature slugs supported by the server hardware (e.g. `direct_remote_access`).",
    ),
    hostname: z.string().optional(),
    interfaces: z.array(z.lazy(() => Interface$zodSchema)).optional(),
    ipmi_status: IpmiStatus$zodSchema.nullable().optional(),
    label: z.string().optional().describe("The server label"),
    legacy_network: z.boolean().nullable().optional().describe(
      "Whether the server is attached to a legacy network.",
    ),
    locked: z.boolean().optional(),
    operating_system: z.lazy(() => ServerDataOperatingSystem$zodSchema)
      .optional(),
    plan: z.lazy(() => ServerDataPlan$zodSchema).optional(),
    price: z.number().nullable().optional(),
    primary_ipv4: z.string().nullable().optional(),
    primary_ipv6: z.string().nullable().optional(),
    project: ProjectInclude$zodSchema.optional(),
    public_network: z.lazy(() => ServerDataPublicNetwork$zodSchema).nullable()
      .optional().describe(
        "**Preview.** Available to teams with public networks enabled. The public network this server is attached onto, or null. Fetch full details from GET /public_networks/{id}.",
      ),
    public_network_eligible: z.boolean().optional().describe(
      "Whether the server is eligible to attach a public network (carries the bond-vpc-enabled tag).",
    ),
    region: ServerRegionResourceData$zodSchema.optional(),
    rescue_allowed: z.boolean().optional(),
    role: z.string().optional().describe("The server role (e.g. Bare Metal)"),
    scheduled_deletion_at: z.string().nullable().optional(),
    site: z.string().optional(),
    specs: z.lazy(() => ServerDataSpecs$zodSchema).optional(),
    status: z.string().optional().describe(
      "`on` - The server is powered ON\n`off` - The server is powered OFF\n`unknown` - The server power status is unknown\n`disk_erasing` - The server is in reinstalling state `disk_erasing`\n`deploying` - The server is deploying or reinstalling\n`failed_deployment` - The server has failed deployment or reinstall\n`rescue_mode` - The server is in rescue mode\n`entering_rescue_mode` - The server is entering rescue mode\n`exiting_rescue_mode` - The server is exiting rescue mode\n\nWhile a server is provisioning, the provisioning state slug is returned verbatim,\nso values outside this list (e.g. `queued`, `starting_deploy`, `commissioning`)\nare possible. Treat this field as an open set, not a closed enum.\n",
    ),
    tags: z.array(z.lazy(() => ServerDataTag$zodSchema)).optional(),
    team: TeamInclude$zodSchema.optional(),
  });

export type ServerData = {
  id?: string | undefined;
  type?: string | undefined;
  attributes?: ServerDataAttributes | undefined;
};

export const ServerData$zodSchema: z.ZodType<ServerData> = z.object({
  attributes: z.lazy(() => ServerDataAttributes$zodSchema).optional(),
  id: z.string().optional(),
  type: z.string().optional(),
});
