/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

export const ShowVirtualMachineMetricsMetric = {
  Cpu: "cpu",
  Memory: "memory",
  Network: "network",
  Disk: "disk",
} as const;
export type ShowVirtualMachineMetricsMetric = ClosedEnum<
  typeof ShowVirtualMachineMetricsMetric
>;

export const ShowVirtualMachineMetricsMetric$zodSchema = z.enum([
  "cpu",
  "memory",
  "network",
  "disk",
]);

export const ShowVirtualMachineMetricsRange = {
  Fivem: "5m",
  Fifteenm: "15m",
  Oneh: "1h",
  TwentyFourh: "24h",
} as const;
export type ShowVirtualMachineMetricsRange = ClosedEnum<
  typeof ShowVirtualMachineMetricsRange
>;

export const ShowVirtualMachineMetricsRange$zodSchema = z.enum([
  "5m",
  "15m",
  "1h",
  "24h",
]);

export type ShowVirtualMachineMetricsRequest = {
  virtual_machine_id: string;
  metric: ShowVirtualMachineMetricsMetric;
  range?: ShowVirtualMachineMetricsRange | undefined;
  force_refresh?: boolean | undefined;
};

export const ShowVirtualMachineMetricsRequest$zodSchema: z.ZodType<
  ShowVirtualMachineMetricsRequest
> = z.object({
  force_refresh: z.boolean().optional(),
  metric: ShowVirtualMachineMetricsMetric$zodSchema,
  range: ShowVirtualMachineMetricsRange$zodSchema.optional(),
  virtual_machine_id: z.string(),
});
