/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type ShowVirtualMachineRequest = { virtual_machine_id: string };

export const ShowVirtualMachineRequest$zodSchema: z.ZodType<
  ShowVirtualMachineRequest
> = z.object({
  virtual_machine_id: z.string(),
});
