/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type StorageUsageAttributes = {
  date?: string | undefined;
  storage_id?: number | undefined;
  project_id?: number | undefined;
  storage_type?: string | null | undefined;
  tier?: string | null | undefined;
  region?: string | undefined;
  bytes?: number | undefined;
  raw_value?: number | undefined;
  raw_unit?: string | undefined;
  ingested_at?: string | undefined;
};

export const StorageUsageAttributes$zodSchema: z.ZodType<
  StorageUsageAttributes
> = z.object({
  bytes: z.int().optional().describe(
    "Canonical storage usage for the day, in bytes",
  ),
  date: z.string().date().optional().describe(
    "The day this usage row refers to",
  ),
  ingested_at: z.iso.datetime({ offset: true }).optional(),
  project_id: z.int().optional(),
  raw_unit: z.string().optional().describe(
    "The unit raw_value is expressed in",
  ),
  raw_value: z.number().optional().describe(
    "The provider-reported usage value, in raw_unit",
  ),
  region: z.string().optional(),
  storage_id: z.int().optional(),
  storage_type: z.string().nullable().optional().describe(
    "Storage kind. One of: object, file, block.",
  ),
  tier: z.string().nullable().optional().describe(
    "Performance tier. One of: high, standard.",
  ),
});

export type StorageUsageData = {
  id?: string | undefined;
  type?: string | undefined;
  attributes?: StorageUsageAttributes | undefined;
};

export const StorageUsageData$zodSchema: z.ZodType<StorageUsageData> = z.object(
  {
    attributes: z.lazy(() => StorageUsageAttributes$zodSchema).optional(),
    id: z.string().optional(),
    type: z.string().optional(),
  },
);

export type StorageUsage = { data?: Array<StorageUsageData> | undefined };

export const StorageUsage$zodSchema: z.ZodType<StorageUsage> = z.object({
  data: z.array(z.lazy(() => StorageUsageData$zodSchema)).optional(),
});
