/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type Currency = {};

export const Currency$zodSchema: z.ZodType<Currency, z.ZodTypeDef, unknown> = z
  .object({});

export type TeamInclude = {
  id?: string | undefined;
  name?: string | undefined;
  slug?: string | undefined;
  description?: string | undefined;
  address?: string | undefined;
  currency?: Currency | undefined;
  status?: string | undefined;
  feature_flags?: Array<string> | undefined;
};

export const TeamInclude$zodSchema: z.ZodType<
  TeamInclude,
  z.ZodTypeDef,
  unknown
> = z.object({
  address: z.string().optional(),
  currency: z.lazy(() => Currency$zodSchema).optional(),
  description: z.string().optional(),
  feature_flags: z.array(z.string()).optional(),
  id: z.string().optional(),
  name: z.string().optional(),
  slug: z.string().optional(),
  status: z.string().optional(),
});
