/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export const TrafficQuotaType$zodSchema = z.enum([
  "traffic_quota",
]);

export type TrafficQuotaType = z.infer<typeof TrafficQuotaType$zodSchema>;

export type QuotaInTb = {
  granted?: number | undefined;
  additional?: number | undefined;
  total?: number | undefined;
};

export const QuotaInTb$zodSchema: z.ZodType<QuotaInTb, z.ZodTypeDef, unknown> =
  z.object({
    additional: z.number().int().optional(),
    granted: z.number().int().optional(),
    total: z.number().int().optional(),
  });

export type QuotaInMbps = {
  granted?: number | undefined;
  additional?: number | undefined;
  total?: number | undefined;
};

export const QuotaInMbps$zodSchema: z.ZodType<
  QuotaInMbps,
  z.ZodTypeDef,
  unknown
> = z.object({
  additional: z.number().int().optional(),
  granted: z.number().int().optional(),
  total: z.number().int().optional(),
});

export type QuotaPerRegion = {
  region_id?: string | undefined;
  region_slug?: string | undefined;
  quota_in_tb?: QuotaInTb | undefined;
  quota_in_mbps?: QuotaInMbps | undefined;
};

export const QuotaPerRegion$zodSchema: z.ZodType<
  QuotaPerRegion,
  z.ZodTypeDef,
  unknown
> = z.object({
  quota_in_mbps: z.lazy(() => QuotaInMbps$zodSchema).optional(),
  quota_in_tb: z.lazy(() => QuotaInTb$zodSchema).optional(),
  region_id: z.string().optional(),
  region_slug: z.string().optional(),
});

export type QuotaPerProject = {
  project_id?: string | undefined;
  project_slug?: string | undefined;
  price?: number | undefined;
  billing_method?: string | undefined;
  quota_per_region?: Array<QuotaPerRegion> | undefined;
};

export const QuotaPerProject$zodSchema: z.ZodType<
  QuotaPerProject,
  z.ZodTypeDef,
  unknown
> = z.object({
  billing_method: z.string().optional(),
  price: z.number().int().optional(),
  project_id: z.string().optional(),
  project_slug: z.string().optional(),
  quota_per_region: z.array(z.lazy(() => QuotaPerRegion$zodSchema)).optional(),
});

export type TrafficQuotaAttributes = {
  quota_per_project?: Array<QuotaPerProject> | undefined;
};

export const TrafficQuotaAttributes$zodSchema: z.ZodType<
  TrafficQuotaAttributes,
  z.ZodTypeDef,
  unknown
> = z.object({
  quota_per_project: z.array(z.lazy(() => QuotaPerProject$zodSchema))
    .optional(),
});

export type TrafficQuotaData = {
  id?: string | undefined;
  type?: TrafficQuotaType | undefined;
  attributes?: TrafficQuotaAttributes | undefined;
};

export const TrafficQuotaData$zodSchema: z.ZodType<
  TrafficQuotaData,
  z.ZodTypeDef,
  unknown
> = z.object({
  attributes: z.lazy(() => TrafficQuotaAttributes$zodSchema).optional(),
  id: z.string().optional(),
  type: TrafficQuotaType$zodSchema.optional(),
});

export type TrafficQuota = { data?: TrafficQuotaData | undefined };

export const TrafficQuota$zodSchema: z.ZodType<
  TrafficQuota,
  z.ZodTypeDef,
  unknown
> = z.object({
  data: z.lazy(() => TrafficQuotaData$zodSchema).optional(),
});
