/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

export const TrafficType = {
  Traffic: "traffic",
} as const;
export type TrafficType = ClosedEnum<typeof TrafficType>;

export const TrafficType$zodSchema = z.enum([
  "traffic",
]);

export type AttributesData = {
  date?: string | undefined;
  inbound_gb?: number | undefined;
  outbound_gb?: number | undefined;
  avg_outbound_speed_mbps?: number | undefined;
  avg_inbound_speed_mbps?: number | undefined;
};

export const AttributesData$zodSchema: z.ZodType<AttributesData> = z.object({
  avg_inbound_speed_mbps: z.number().optional().describe("Value in Mbps"),
  avg_outbound_speed_mbps: z.number().optional().describe("Value in Mbps"),
  date: z.string().optional().describe("The datetime of the day"),
  inbound_gb: z.int().optional().describe("Value in GB"),
  outbound_gb: z.int().optional().describe("Value in GB"),
});

export type TrafficRegion = {
  region_slug?: string | undefined;
  total_inbound_gb?: number | undefined;
  total_outbound_gb?: number | undefined;
  total_inbound_95th_percentile_mbps?: number | undefined;
  total_outbound_95th_percentile_mbps?: number | undefined;
  data?: Array<AttributesData> | undefined;
};

export const TrafficRegion$zodSchema: z.ZodType<TrafficRegion> = z.object({
  data: z.array(z.lazy(() => AttributesData$zodSchema)).optional(),
  region_slug: z.string().optional(),
  total_inbound_95th_percentile_mbps: z.number().optional().describe(
    "The 95th percentile of inbound bandwidth for this region, calculated from 30-minute intervals. Value in Mbps",
  ),
  total_inbound_gb: z.int().optional().describe("Value in GB"),
  total_outbound_95th_percentile_mbps: z.number().optional().describe(
    "The 95th percentile of outbound bandwidth for this region, calculated from 30-minute intervals. Value in Mbps",
  ),
  total_outbound_gb: z.int().optional().describe("Value in GB"),
});

export type TrafficAttributes = {
  from_date?: number | undefined;
  to_date?: number | undefined;
  regions?: Array<TrafficRegion> | undefined;
  total_inbound_gb?: number | undefined;
  total_outbound_gb?: number | undefined;
  total_inbound_95th_percentile_mbps?: number | undefined;
  total_outbound_95th_percentile_mbps?: number | undefined;
};

export const TrafficAttributes$zodSchema: z.ZodType<TrafficAttributes> = z
  .object({
    from_date: z.int().optional().describe(
      "The start timestamp. Must be a unix timestamp",
    ),
    regions: z.array(z.lazy(() => TrafficRegion$zodSchema)).optional(),
    to_date: z.int().optional().describe(
      "The end timestamp. Must be a unix timestamp",
    ),
    total_inbound_95th_percentile_mbps: z.number().optional().describe(
      "The 95th percentile of inbound bandwidth across all regions, calculated from all 30-minute intervals combined. This is a global percentile, not a sum of regional percentiles. Value in Mbps",
    ),
    total_inbound_gb: z.int().optional().describe("Value in GB"),
    total_outbound_95th_percentile_mbps: z.number().optional().describe(
      "The 95th percentile of outbound bandwidth across all regions, calculated from all 30-minute intervals combined. This is a global percentile, not a sum of regional percentiles. Value in Mbps",
    ),
    total_outbound_gb: z.int().optional().describe("Value in GB"),
  });

export type TrafficData = {
  id?: string | undefined;
  type?: TrafficType | undefined;
  attributes?: TrafficAttributes | undefined;
};

export const TrafficData$zodSchema: z.ZodType<TrafficData> = z.object({
  attributes: z.lazy(() => TrafficAttributes$zodSchema).optional(),
  id: z.string().optional(),
  type: TrafficType$zodSchema.optional(),
});

export type Traffic = { data?: TrafficData | undefined };

export const Traffic$zodSchema: z.ZodType<Traffic> = z.object({
  data: z.lazy(() => TrafficData$zodSchema).optional(),
});
