/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ElasticIp, ElasticIp$zodSchema } from "./elasticip.js";
import { ErrorObject, ErrorObject$zodSchema } from "./errorobject.js";
import {
  UpdateElasticIp,
  UpdateElasticIp$zodSchema,
} from "./updateelasticip.js";

export type UpdateElasticIpRequest = {
  elastic_ip_id: string;
  update_elastic_ip: UpdateElasticIp;
};

export const UpdateElasticIpRequest$zodSchema: z.ZodType<
  UpdateElasticIpRequest
> = z.object({
  elastic_ip_id: z.string().describe("The Elastic IP ID"),
  update_elastic_ip: UpdateElasticIp$zodSchema,
});

export type UpdateElasticIpResponse = ElasticIp | ErrorObject;

export const UpdateElasticIpResponse$zodSchema: z.ZodType<
  UpdateElasticIpResponse
> = z.union([
  ElasticIp$zodSchema,
  ErrorObject$zodSchema,
]);
