/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";
import { CustomTag, CustomTag$zodSchema } from "./customtag.js";
import { ErrorObject, ErrorObject$zodSchema } from "./errorobject.js";

export const UpdateTagType2 = {
  Tags: "tags",
} as const;
export type UpdateTagType2 = ClosedEnum<typeof UpdateTagType2>;

export const UpdateTagType2$zodSchema = z.enum([
  "tags",
]);

export type UpdateTagAttributes2 = {
  name?: string | undefined;
  description?: string | null | undefined;
  color?: string | undefined;
};

export const UpdateTagAttributes2$zodSchema: z.ZodType<UpdateTagAttributes2> = z
  .object({
    color: z.string().default("#ffffff").describe("Color of the Tag"),
    description: z.string().nullable().optional().describe(
      "Description of the Tag",
    ),
    name: z.string().optional().describe("Name of the Tag"),
  });

export type UpdateTagData2 = {
  id?: string | undefined;
  type?: UpdateTagType2 | undefined;
  attributes?: UpdateTagAttributes2 | undefined;
};

export const UpdateTagData2$zodSchema: z.ZodType<UpdateTagData2> = z.object({
  attributes: z.lazy(() => UpdateTagAttributes2$zodSchema).optional(),
  id: z.string().optional(),
  type: UpdateTagType2$zodSchema.optional(),
});

export type UpdateTagRequestBody2 = { data?: UpdateTagData2 | undefined };

export const UpdateTagRequestBody2$zodSchema: z.ZodType<UpdateTagRequestBody2> =
  z.object({
    data: z.lazy(() => UpdateTagData2$zodSchema).optional(),
  });

export type UpdateTagRequest = {
  tag_id: string;
  RequestBody: UpdateTagRequestBody2;
};

export const UpdateTagRequest$zodSchema: z.ZodType<UpdateTagRequest> = z.object(
  {
    RequestBody: z.lazy(() => UpdateTagRequestBody2$zodSchema),
    tag_id: z.string(),
  },
);

export type UpdateTagResponse = CustomTag | ErrorObject;

export const UpdateTagResponse$zodSchema: z.ZodType<UpdateTagResponse> = z
  .union([
    CustomTag$zodSchema,
    ErrorObject$zodSchema,
  ]);
