/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

export const UpdateLksClusterType = {
  LksClusters: "lks_clusters",
} as const;
export type UpdateLksClusterType = ClosedEnum<typeof UpdateLksClusterType>;

export const UpdateLksClusterType$zodSchema = z.enum([
  "lks_clusters",
]);

/**
 * At least one of name, description or kubernetes_version must be provided.
 */
export type UpdateLksClusterAttributes = {
  name?: string | undefined;
  description?: string | undefined;
  kubernetes_version?: string | undefined;
};

export const UpdateLksClusterAttributes$zodSchema: z.ZodType<
  UpdateLksClusterAttributes
> = z.object({
  description: z.string().optional(),
  kubernetes_version: z.string().optional().describe(
    "Setting a newer patch consents to a control-plane upgrade. Must not be lower than the current patch (422 DOWNGRADE_NOT_ALLOWED)",
  ),
  name: z.string().optional(),
}).describe(
  "At least one of name, description or kubernetes_version must be provided.",
);

export type UpdateLksClusterData = {
  type: UpdateLksClusterType;
  attributes?: UpdateLksClusterAttributes | undefined;
};

export const UpdateLksClusterData$zodSchema: z.ZodType<UpdateLksClusterData> = z
  .object({
    attributes: z.lazy(() => UpdateLksClusterAttributes$zodSchema).optional()
      .describe(
        "At least one of name, description or kubernetes_version must be provided.",
      ),
    type: UpdateLksClusterType$zodSchema,
  });

export type UpdateLksCluster = { data: UpdateLksClusterData };

export const UpdateLksCluster$zodSchema: z.ZodType<UpdateLksCluster> = z.object(
  {
    data: z.lazy(() => UpdateLksClusterData$zodSchema),
  },
);
