/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ErrorObject, ErrorObject$zodSchema } from "./errorobject.js";
import { LksNodePool, LksNodePool$zodSchema } from "./lksnodepool.js";
import {
  UpdateLksNodePool,
  UpdateLksNodePool$zodSchema,
} from "./updatelksnodepool.js";

export type UpdateLksNodePoolRequest = {
  cluster_id: string;
  id: string;
  update_lks_node_pool: UpdateLksNodePool;
};

export const UpdateLksNodePoolRequest$zodSchema: z.ZodType<
  UpdateLksNodePoolRequest
> = z.object({
  cluster_id: z.string().describe("The cluster ID (format: `lksc_<hash>`)."),
  id: z.string().describe("The node pool ID (format: `lksnp_<hash>`)."),
  update_lks_node_pool: UpdateLksNodePool$zodSchema,
});

export type UpdateLksNodePoolResponse = LksNodePool | ErrorObject;

export const UpdateLksNodePoolResponse$zodSchema: z.ZodType<
  UpdateLksNodePoolResponse
> = z.union([
  LksNodePool$zodSchema,
  ErrorObject$zodSchema,
]);
