/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

export const UpdateServerDeployConfigType2 = {
  DeployConfig: "deploy_config",
} as const;
export type UpdateServerDeployConfigType2 = ClosedEnum<
  typeof UpdateServerDeployConfigType2
>;

export const UpdateServerDeployConfigType2$zodSchema = z.enum([
  "deploy_config",
]);

export const UpdateServerDeployConfigOperatingSystem2 = {
  Centos74X64: "centos_7_4_x64",
  Centos8X64: "centos_8_x64",
  Debian10: "debian_10",
  Debian11: "debian_11",
  Debian12: "debian_12",
  Ipxe: "ipxe",
  Rhel8: "rhel8",
  Rockylinux8: "rockylinux_8",
  Ubuntu22MlInABox: "ubuntu22_ml_in_a_box",
  Ubuntu24MlInABox: "ubuntu24_ml_in_a_box",
  Ubuntu2004X64Lts: "ubuntu_20_04_x64_lts",
  Ubuntu2204X64Lts: "ubuntu_22_04_x64_lts",
  Ubuntu2404X64Lts: "ubuntu_24_04_x64_lts",
  Windows2022Std: "windows_2022_std",
  WindowsServer2019StdV1: "windows_server_2019_std_v1",
} as const;
export type UpdateServerDeployConfigOperatingSystem2 = ClosedEnum<
  typeof UpdateServerDeployConfigOperatingSystem2
>;

export const UpdateServerDeployConfigOperatingSystem2$zodSchema = z.enum([
  "centos_7_4_x64",
  "centos_8_x64",
  "debian_10",
  "debian_11",
  "debian_12",
  "ipxe",
  "rhel8",
  "rockylinux_8",
  "ubuntu22_ml_in_a_box",
  "ubuntu24_ml_in_a_box",
  "ubuntu_20_04_x64_lts",
  "ubuntu_22_04_x64_lts",
  "ubuntu_24_04_x64_lts",
  "windows_2022_std",
  "windows_server_2019_std_v1",
]);

/**
 * RAID mode for the server. Set to 'raid-0' for RAID 0, 'raid-1' for RAID 1, or omit/null for no RAID configuration
 */
export const UpdateServerDeployConfigRaid2 = {
  Raid0: "raid-0",
  Raid1: "raid-1",
} as const;
/**
 * RAID mode for the server. Set to 'raid-0' for RAID 0, 'raid-1' for RAID 1, or omit/null for no RAID configuration
 */
export type UpdateServerDeployConfigRaid2 = ClosedEnum<
  typeof UpdateServerDeployConfigRaid2
>;

export const UpdateServerDeployConfigRaid2$zodSchema = z.enum([
  "raid-0",
  "raid-1",
]).describe(
  "RAID mode for the server. Set to 'raid-0' for RAID 0, 'raid-1' for RAID 1, or omit/null for no RAID configuration",
);

export type UpdateServerDeployConfigPartition2 = {
  size_in_gb?: number | undefined;
  path?: string | undefined;
  filesystem_type?: string | undefined;
};

export const UpdateServerDeployConfigPartition2$zodSchema: z.ZodType<
  UpdateServerDeployConfigPartition2
> = z.object({
  filesystem_type: z.string().optional(),
  path: z.string().optional(),
  size_in_gb: z.int().optional(),
});

export type UpdateServerDeployConfigAttributes2 = {
  hostname?: string | null | undefined;
  operating_system?:
    | UpdateServerDeployConfigOperatingSystem2
    | null
    | undefined;
  raid?: UpdateServerDeployConfigRaid2 | null | undefined;
  user_data?: string | null | undefined;
  ssh_keys?: Array<string> | null | undefined;
  partitions?: Array<UpdateServerDeployConfigPartition2> | null | undefined;
  ipxe_url?: string | null | undefined;
};

export const UpdateServerDeployConfigAttributes2$zodSchema: z.ZodType<
  UpdateServerDeployConfigAttributes2
> = z.object({
  hostname: z.string().nullable().optional(),
  ipxe_url: z.string().nullable().optional(),
  operating_system: UpdateServerDeployConfigOperatingSystem2$zodSchema
    .nullable().optional(),
  partitions: z.array(
    z.lazy(() => UpdateServerDeployConfigPartition2$zodSchema),
  ).nullable().optional(),
  raid: UpdateServerDeployConfigRaid2$zodSchema.nullable().optional(),
  ssh_keys: z.array(z.string()).nullable().optional(),
  user_data: z.string().nullable().optional(),
});

export type UpdateServerDeployConfigRequestBody2 = {
  type: UpdateServerDeployConfigType2;
  attributes?: UpdateServerDeployConfigAttributes2 | undefined;
};

export const UpdateServerDeployConfigRequestBody2$zodSchema: z.ZodType<
  UpdateServerDeployConfigRequestBody2
> = z.object({
  attributes: z.lazy(() => UpdateServerDeployConfigAttributes2$zodSchema)
    .optional(),
  type: UpdateServerDeployConfigType2$zodSchema,
});

export type UpdateServerDeployConfigRequest = {
  server_id: string;
  RequestBody: UpdateServerDeployConfigRequestBody2;
};

export const UpdateServerDeployConfigRequest$zodSchema: z.ZodType<
  UpdateServerDeployConfigRequest
> = z.object({
  RequestBody: z.lazy(() => UpdateServerDeployConfigRequestBody2$zodSchema),
  server_id: z.string().describe("The Server ID"),
});
