/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ErrorObject, ErrorObject$zodSchema } from "./errorobject.js";
import { PublicNetwork, PublicNetwork$zodSchema } from "./publicnetwork.js";
import {
  UpdatePublicNetworkIp,
  UpdatePublicNetworkIp$zodSchema,
} from "./updatepublicnetworkip.js";

export type UpdatePublicNetworkIpRequest = {
  id: string;
  update_public_network_ip: UpdatePublicNetworkIp;
};

export const UpdatePublicNetworkIpRequest$zodSchema: z.ZodType<
  UpdatePublicNetworkIpRequest
> = z.object({
  id: z.string(),
  update_public_network_ip: UpdatePublicNetworkIp$zodSchema,
});

export type UpdatePublicNetworkIpResponse = PublicNetwork | ErrorObject;

export const UpdatePublicNetworkIpResponse$zodSchema: z.ZodType<
  UpdatePublicNetworkIpResponse
> = z.union([
  PublicNetwork$zodSchema,
  ErrorObject$zodSchema,
]);
