/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";
import { VirtualNetwork, VirtualNetwork$zodSchema } from "./virtualnetwork.js";

export const UpdateVirtualNetworkType2 = {
  VirtualNetworks: "virtual_networks",
} as const;
export type UpdateVirtualNetworkType2 = ClosedEnum<
  typeof UpdateVirtualNetworkType2
>;

export const UpdateVirtualNetworkType2$zodSchema = z.enum([
  "virtual_networks",
]);

export type UpdateVirtualNetworkAttributes2 = {
  tags?: Array<string> | undefined;
  description?: string | undefined;
};

export const UpdateVirtualNetworkAttributes2$zodSchema: z.ZodType<
  UpdateVirtualNetworkAttributes2
> = z.object({
  description: z.string().default("Test virtual network update"),
  tags: z.array(z.string()).optional(),
});

export type UpdateVirtualNetworkData2 = {
  id: string;
  type: UpdateVirtualNetworkType2;
  attributes?: UpdateVirtualNetworkAttributes2 | undefined;
};

export const UpdateVirtualNetworkData2$zodSchema: z.ZodType<
  UpdateVirtualNetworkData2
> = z.object({
  attributes: z.lazy(() => UpdateVirtualNetworkAttributes2$zodSchema)
    .optional(),
  id: z.string(),
  type: UpdateVirtualNetworkType2$zodSchema,
});

export type UpdateVirtualNetworkRequestBody2 = {
  data: UpdateVirtualNetworkData2;
};

export const UpdateVirtualNetworkRequestBody2$zodSchema: z.ZodType<
  UpdateVirtualNetworkRequestBody2
> = z.object({
  data: z.lazy(() => UpdateVirtualNetworkData2$zodSchema),
});

export type UpdateVirtualNetworkRequest = {
  vlan_id: string;
  RequestBody: UpdateVirtualNetworkRequestBody2;
};

export const UpdateVirtualNetworkRequest$zodSchema: z.ZodType<
  UpdateVirtualNetworkRequest
> = z.object({
  RequestBody: z.lazy(() => UpdateVirtualNetworkRequestBody2$zodSchema),
  vlan_id: z.string().describe("The Virtual Network ID"),
});

export type UpdateVirtualNetworkResponse = {
  ContentType: string;
  StatusCode: number;
  RawResponse: Response;
  virtual_network?: VirtualNetwork | undefined;
};

export const UpdateVirtualNetworkResponse$zodSchema: z.ZodType<
  UpdateVirtualNetworkResponse
> = z.object({
  ContentType: z.string(),
  RawResponse: z.custom<Response>(x => x instanceof Response),
  StatusCode: z.int(),
  virtual_network: VirtualNetwork$zodSchema.optional(),
});
