/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ApiKey, ApiKey$zodSchema } from "./apikey.js";
import { UpdateApiKey, UpdateApiKey$zodSchema } from "./updateapikey.js";

export type UpdateApiKeyRequest = {
  api_key_id: string;
  update_api_key: UpdateApiKey;
};

export const UpdateApiKeyRequest$zodSchema: z.ZodType<UpdateApiKeyRequest> = z
  .object({
    api_key_id: z.string(),
    update_api_key: UpdateApiKey$zodSchema,
  });

/**
 * Success - Update name without rotating token
 */
export type UpdateApiKeyResponse = { data?: ApiKey | undefined };

export const UpdateApiKeyResponse$zodSchema: z.ZodType<UpdateApiKeyResponse> = z
  .object({
    data: ApiKey$zodSchema.optional(),
  }).describe("Success - Update name without rotating token");
