/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";
import { ProjectInclude, ProjectInclude$zodSchema } from "./projectinclude.js";

export const UserDataPropertiesType = {
  UserData: "user_data",
} as const;
export type UserDataPropertiesType = ClosedEnum<typeof UserDataPropertiesType>;

export const UserDataPropertiesType$zodSchema = z.enum([
  "user_data",
]);

export type UserDataPropertiesAttributes = {
  description?: string | undefined;
  content?: string | undefined;
  project?: ProjectInclude | undefined;
  created_at?: string | undefined;
  updated_at?: string | undefined;
};

export const UserDataPropertiesAttributes$zodSchema: z.ZodType<
  UserDataPropertiesAttributes
> = z.object({
  content: z.string().optional().describe("content of the User Data"),
  created_at: z.string().optional(),
  description: z.string().optional().describe("description of the User Data"),
  project: ProjectInclude$zodSchema.optional(),
  updated_at: z.string().optional(),
});

export type UserDataProperties = {
  id?: string | undefined;
  type: UserDataPropertiesType;
  attributes?: UserDataPropertiesAttributes | undefined;
};

export const UserDataProperties$zodSchema: z.ZodType<UserDataProperties> = z
  .object({
    attributes: z.lazy(() => UserDataPropertiesAttributes$zodSchema).optional(),
    id: z.string().optional(),
    type: UserDataPropertiesType$zodSchema,
  });
