/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { PaginationMeta, PaginationMeta$zodSchema } from "./paginationmeta.js";
import {
  UserDataProperties,
  UserDataProperties$zodSchema,
} from "./userdataproperties.js";

export type UserData = {
  data?: Array<UserDataProperties> | undefined;
  meta?: PaginationMeta | undefined;
};

export const UserData$zodSchema: z.ZodType<UserData> = z.object({
  data: z.array(UserDataProperties$zodSchema).optional(),
  meta: PaginationMeta$zodSchema.optional(),
});
