/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

export const VirtualMachinePayloadType = {
  VirtualMachines: "virtual_machines",
} as const;
export type VirtualMachinePayloadType = ClosedEnum<
  typeof VirtualMachinePayloadType
>;

export const VirtualMachinePayloadType$zodSchema = z.enum([
  "virtual_machines",
]);

export type VirtualMachinePayloadAttributes = {
  name?: string | undefined;
  plan?: string | null | undefined;
  ssh_keys?: Array<string> | null | undefined;
  project?: string | undefined;
  operating_system?: string | null | undefined;
};

export const VirtualMachinePayloadAttributes$zodSchema: z.ZodType<
  VirtualMachinePayloadAttributes
> = z.object({
  name: z.string().default("my-vm"),
  operating_system: z.string().nullable().optional().describe(
    "The operating system slug for the Virtual Machine. If not specified, defaults to ubuntu-24-04 for CPU plans or ubuntu24_ml_in_a_box for GPU plans.",
  ),
  plan: z.string().nullable().optional().describe(
    "The plan ID or Slug for the Virtual Machine",
  ),
  project: z.string().default("my-project"),
  ssh_keys: z.array(z.string()).nullable().optional(),
});

export type VirtualMachinePayloadData = {
  type?: VirtualMachinePayloadType | undefined;
  attributes?: VirtualMachinePayloadAttributes | undefined;
};

export const VirtualMachinePayloadData$zodSchema: z.ZodType<
  VirtualMachinePayloadData
> = z.object({
  attributes: z.lazy(() => VirtualMachinePayloadAttributes$zodSchema)
    .optional(),
  type: VirtualMachinePayloadType$zodSchema.optional(),
});

export type VirtualMachinePayload = {
  data?: VirtualMachinePayloadData | undefined;
};

export const VirtualMachinePayload$zodSchema: z.ZodType<VirtualMachinePayload> =
  z.object({
    data: z.lazy(() => VirtualMachinePayloadData$zodSchema).optional(),
  });
