/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { PaginationMeta, PaginationMeta$zodSchema } from "./paginationmeta.js";
import {
  VirtualMachineAttributes,
  VirtualMachineAttributes$zodSchema,
} from "./virtualmachineattributes.js";

export type VirtualMachines = {
  data?: Array<VirtualMachineAttributes> | undefined;
  meta?: PaginationMeta | undefined;
};

export const VirtualMachines$zodSchema: z.ZodType<VirtualMachines> = z.object({
  data: z.array(VirtualMachineAttributes$zodSchema).optional(),
  meta: PaginationMeta$zodSchema.optional(),
});
