/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  VirtualMachineAttributes,
  VirtualMachineAttributes$zodSchema,
} from "./virtualmachineattributes.js";

export type VirtualMachinesMeta = {};

export const VirtualMachinesMeta$zodSchema: z.ZodType<VirtualMachinesMeta> = z
  .object({});

export type VirtualMachines = {
  data?: Array<VirtualMachineAttributes> | undefined;
  meta?: VirtualMachinesMeta | undefined;
};

export const VirtualMachines$zodSchema: z.ZodType<VirtualMachines> = z.object({
  data: z.array(VirtualMachineAttributes$zodSchema).optional(),
  meta: z.lazy(() => VirtualMachinesMeta$zodSchema).optional(),
});
