/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";
import { ProjectInclude, ProjectInclude$zodSchema } from "./projectinclude.js";

export const VirtualNetworkDataType = {
  VirtualNetworks: "virtual_networks",
} as const;
export type VirtualNetworkDataType = ClosedEnum<typeof VirtualNetworkDataType>;

export const VirtualNetworkDataType$zodSchema = z.enum([
  "virtual_networks",
]);

export type VirtualNetworkDataSite = {
  id?: string | undefined;
  facility?: string | undefined;
  name?: string | undefined;
  slug?: string | undefined;
};

export const VirtualNetworkDataSite$zodSchema: z.ZodType<
  VirtualNetworkDataSite
> = z.object({
  facility: z.string().optional(),
  id: z.string().optional(),
  name: z.string().optional(),
  slug: z.string().optional(),
});

export type VirtualNetworkDataRegion = {
  city?: string | undefined;
  country?: string | undefined;
  site?: VirtualNetworkDataSite | undefined;
};

export const VirtualNetworkDataRegion$zodSchema: z.ZodType<
  VirtualNetworkDataRegion
> = z.object({
  city: z.string().optional(),
  country: z.string().optional(),
  site: z.lazy(() => VirtualNetworkDataSite$zodSchema).optional(),
});

export type Tag = {
  id?: string | undefined;
  name?: string | undefined;
  description?: string | undefined;
  color?: string | undefined;
};

export const Tag$zodSchema: z.ZodType<Tag> = z.object({
  color: z.string().optional(),
  description: z.string().optional(),
  id: z.string().optional(),
  name: z.string().optional(),
});

export type VirtualNetworkDataAttributes = {
  vid?: number | undefined;
  name?: string | undefined;
  description?: string | undefined;
  project?: ProjectInclude | undefined;
  region?: VirtualNetworkDataRegion | undefined;
  created_at?: string | null | undefined;
  assignments_count?: number | undefined;
  tags?: Array<Tag> | undefined;
};

export const VirtualNetworkDataAttributes$zodSchema: z.ZodType<
  VirtualNetworkDataAttributes
> = z.object({
  assignments_count: z.int().optional(),
  created_at: z.iso.datetime({ offset: true }).nullable().optional(),
  description: z.string().optional(),
  name: z.string().optional(),
  project: ProjectInclude$zodSchema.optional(),
  region: z.lazy(() => VirtualNetworkDataRegion$zodSchema).optional(),
  tags: z.array(z.lazy(() => Tag$zodSchema)).optional(),
  vid: z.int().optional(),
});

export type VirtualNetworkData = {
  id?: string | undefined;
  type?: VirtualNetworkDataType | undefined;
  attributes?: VirtualNetworkDataAttributes | undefined;
};

export const VirtualNetworkData$zodSchema: z.ZodType<VirtualNetworkData> = z
  .object({
    attributes: z.lazy(() => VirtualNetworkDataAttributes$zodSchema).optional(),
    id: z.string().optional(),
    type: VirtualNetworkDataType$zodSchema.optional(),
  });
