/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";
import { ProjectInclude, ProjectInclude$zodSchema } from "./projectinclude.js";
import { TeamInclude, TeamInclude$zodSchema } from "./teaminclude.js";

export const VirtualMachineAttributesType = {
  VirtualMachines: "virtual_machines",
} as const;
export type VirtualMachineAttributesType = ClosedEnum<
  typeof VirtualMachineAttributesType
>;

export const VirtualMachineAttributesType$zodSchema = z.enum([
  "virtual_machines",
]);

export const VirtualMachineAttributesStatus = {
  Running: "Running",
  ConfiguringNetwork: "Configuring network",
  Starting: "Starting",
  Scheduling: "Scheduling",
  Scheduled: "Scheduled",
} as const;
export type VirtualMachineAttributesStatus = ClosedEnum<
  typeof VirtualMachineAttributesStatus
>;

export const VirtualMachineAttributesStatus$zodSchema = z.enum([
  "Running",
  "Configuring network",
  "Starting",
  "Scheduling",
  "Scheduled",
]);

export type VirtualMachineAttributesCredentials = {
  username?: string | undefined;
  host?: string | undefined;
  password?: string | undefined;
  ssh_keys?: Array<string> | undefined;
};

export const VirtualMachineAttributesCredentials$zodSchema: z.ZodType<
  VirtualMachineAttributesCredentials
> = z.object({
  host: z.string().optional(),
  password: z.string().optional(),
  ssh_keys: z.array(z.string()).optional(),
  username: z.string().optional(),
});

export type VirtualMachineAttributesPlan = {
  id?: string | undefined;
  name?: string | undefined;
};

export const VirtualMachineAttributesPlan$zodSchema: z.ZodType<
  VirtualMachineAttributesPlan
> = z.object({
  id: z.string().optional(),
  name: z.string().optional(),
});

export type VirtualMachineAttributesSpecs = {
  vcpu?: number | null | undefined;
  ram?: string | null | undefined;
  storage?: string | null | undefined;
  nic?: string | null | undefined;
  gpu?: string | null | undefined;
};

export const VirtualMachineAttributesSpecs$zodSchema: z.ZodType<
  VirtualMachineAttributesSpecs
> = z.object({
  gpu: z.string().nullable().optional(),
  nic: z.string().nullable().optional(),
  ram: z.string().nullable().optional(),
  storage: z.string().nullable().optional(),
  vcpu: z.int().nullable().optional(),
});

export type VirtualMachineAttributesAttributes = {
  name?: string | undefined;
  created_at?: string | undefined;
  status?: VirtualMachineAttributesStatus | undefined;
  primary_ipv4?: string | null | undefined;
  operating_system?: string | null | undefined;
  credentials?: VirtualMachineAttributesCredentials | null | undefined;
  plan?: VirtualMachineAttributesPlan | undefined;
  specs?: VirtualMachineAttributesSpecs | undefined;
  team?: TeamInclude | undefined;
  project?: ProjectInclude | undefined;
};

export const VirtualMachineAttributesAttributes$zodSchema: z.ZodType<
  VirtualMachineAttributesAttributes
> = z.object({
  created_at: z.string().optional(),
  credentials: z.lazy(() => VirtualMachineAttributesCredentials$zodSchema)
    .nullable().optional(),
  name: z.string().optional(),
  operating_system: z.string().nullable().optional(),
  plan: z.lazy(() => VirtualMachineAttributesPlan$zodSchema).optional(),
  primary_ipv4: z.string().nullable().optional(),
  project: ProjectInclude$zodSchema.optional(),
  specs: z.lazy(() => VirtualMachineAttributesSpecs$zodSchema).optional(),
  status: VirtualMachineAttributesStatus$zodSchema.optional(),
  team: TeamInclude$zodSchema.optional(),
});

export type VirtualMachineAttributes = {
  id?: string | undefined;
  type?: VirtualMachineAttributesType | undefined;
  attributes?: VirtualMachineAttributesAttributes | undefined;
};

export const VirtualMachineAttributes$zodSchema: z.ZodType<
  VirtualMachineAttributes
> = z.object({
  attributes: z.lazy(() => VirtualMachineAttributesAttributes$zodSchema)
    .optional(),
  id: z.string().optional(),
  type: VirtualMachineAttributesType$zodSchema.optional(),
});
