/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  VirtualNetworkAssignmentData,
  VirtualNetworkAssignmentData$zodSchema,
} from "./virtualnetworkassignmentdata.js";

export type VirtualNetworkAssignmentMeta = {};

export const VirtualNetworkAssignmentMeta$zodSchema: z.ZodType<
  VirtualNetworkAssignmentMeta,
  z.ZodTypeDef,
  unknown
> = z.object({});

export type VirtualNetworkAssignment = {
  data?: VirtualNetworkAssignmentData | undefined;
  meta?: VirtualNetworkAssignmentMeta | undefined;
};

export const VirtualNetworkAssignment$zodSchema: z.ZodType<
  VirtualNetworkAssignment,
  z.ZodTypeDef,
  unknown
> = z.object({
  data: VirtualNetworkAssignmentData$zodSchema.optional(),
  meta: z.lazy(() => VirtualNetworkAssignmentMeta$zodSchema).optional(),
});
