/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

export const VirtualMachineUpdatePayloadType = {
  VirtualMachines: "virtual_machines",
} as const;
export type VirtualMachineUpdatePayloadType = ClosedEnum<
  typeof VirtualMachineUpdatePayloadType
>;

export const VirtualMachineUpdatePayloadType$zodSchema = z.enum([
  "virtual_machines",
]);

export type VirtualMachineUpdatePayloadAttributes = { name: string };

export const VirtualMachineUpdatePayloadAttributes$zodSchema: z.ZodType<
  VirtualMachineUpdatePayloadAttributes
> = z.object({
  name: z.string().describe(
    "The new display name (hostname) for the Virtual Machine",
  ),
});

export type VirtualMachineUpdatePayloadData = {
  type: VirtualMachineUpdatePayloadType;
  id?: string | undefined;
  attributes: VirtualMachineUpdatePayloadAttributes;
};

export const VirtualMachineUpdatePayloadData$zodSchema: z.ZodType<
  VirtualMachineUpdatePayloadData
> = z.object({
  attributes: z.lazy(() => VirtualMachineUpdatePayloadAttributes$zodSchema),
  id: z.string().optional(),
  type: VirtualMachineUpdatePayloadType$zodSchema,
});

export type VirtualMachineUpdatePayload = {
  data: VirtualMachineUpdatePayloadData;
};

export const VirtualMachineUpdatePayload$zodSchema: z.ZodType<
  VirtualMachineUpdatePayload
> = z.object({
  data: z.lazy(() => VirtualMachineUpdatePayloadData$zodSchema),
});
