/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export const VirtualNetworkAssignmentDataType$zodSchema = z.enum([
  "virtual_network_assignment",
]);

export type VirtualNetworkAssignmentDataType = z.infer<
  typeof VirtualNetworkAssignmentDataType$zodSchema
>;

export type VirtualNetworkAssignmentDataServer = {
  id?: string | undefined;
  hostname?: string | undefined;
  label?: string | undefined;
  locked?: boolean | undefined;
  status?: string | undefined;
};

export const VirtualNetworkAssignmentDataServer$zodSchema: z.ZodType<
  VirtualNetworkAssignmentDataServer,
  z.ZodTypeDef,
  unknown
> = z.object({
  hostname: z.string().optional(),
  id: z.string().optional(),
  label: z.string().optional(),
  locked: z.boolean().optional(),
  status: z.string().optional(),
});

export type VirtualNetworkAssignmentDataAttributes = {
  virtual_network_id?: string | undefined;
  vid?: number | undefined;
  description?: string | undefined;
  status?: string | undefined;
  server?: VirtualNetworkAssignmentDataServer | undefined;
};

export const VirtualNetworkAssignmentDataAttributes$zodSchema: z.ZodType<
  VirtualNetworkAssignmentDataAttributes,
  z.ZodTypeDef,
  unknown
> = z.object({
  description: z.string().optional(),
  server: z.lazy(() => VirtualNetworkAssignmentDataServer$zodSchema).optional(),
  status: z.string().optional(),
  vid: z.number().int().optional(),
  virtual_network_id: z.string().optional(),
});

export type VirtualNetworkAssignmentData = {
  id?: string | undefined;
  type?: VirtualNetworkAssignmentDataType | undefined;
  attributes?: VirtualNetworkAssignmentDataAttributes | undefined;
};

export const VirtualNetworkAssignmentData$zodSchema: z.ZodType<
  VirtualNetworkAssignmentData,
  z.ZodTypeDef,
  unknown
> = z.object({
  attributes: z.lazy(() => VirtualNetworkAssignmentDataAttributes$zodSchema)
    .optional(),
  id: z.string().optional(),
  type: VirtualNetworkAssignmentDataType$zodSchema.optional(),
});
