/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";
import { ProjectInclude, ProjectInclude$zodSchema } from "./projectinclude.js";
import { TeamInclude, TeamInclude$zodSchema } from "./teaminclude.js";

export const VolumeDataType = {
  Volumes: "volumes",
} as const;
export type VolumeDataType = ClosedEnum<typeof VolumeDataType>;

export const VolumeDataType$zodSchema = z.enum([
  "volumes",
]);

export type Initiator = { nqn?: string | undefined };

export const Initiator$zodSchema: z.ZodType<Initiator> = z.object({
  nqn: z.string().optional(),
});

export type VolumeDataAttributes = {
  name?: string | undefined;
  size_in_gb?: number | undefined;
  created_at?: string | undefined;
  namespace_id?: string | null | undefined;
  connector_id?: string | undefined;
  initiators?: Array<Initiator> | undefined;
  project?: ProjectInclude | undefined;
  team?: TeamInclude | undefined;
};

export const VolumeDataAttributes$zodSchema: z.ZodType<VolumeDataAttributes> = z
  .object({
    connector_id: z.string().optional(),
    created_at: z.iso.datetime({ offset: true }).optional(),
    initiators: z.array(z.lazy(() => Initiator$zodSchema)).optional(),
    name: z.string().optional(),
    namespace_id: z.string().nullable().optional(),
    project: ProjectInclude$zodSchema.optional(),
    size_in_gb: z.int().optional(),
    team: TeamInclude$zodSchema.optional(),
  });

export type VolumeData = {
  id?: string | undefined;
  type?: VolumeDataType | undefined;
  attributes?: VolumeDataAttributes | undefined;
};

export const VolumeData$zodSchema: z.ZodType<VolumeData> = z.object({
  attributes: z.lazy(() => VolumeDataAttributes$zodSchema).optional(),
  id: z.string().optional(),
  type: VolumeDataType$zodSchema.optional(),
});
