/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  VpnSessionDataWithPassword,
  VpnSessionDataWithPassword$zodSchema,
} from "./vpnsessiondatawithpassword.js";

export type VpnSessionWithPassword = {
  data?: VpnSessionDataWithPassword | undefined;
};

export const VpnSessionWithPassword$zodSchema: z.ZodType<
  VpnSessionWithPassword,
  z.ZodTypeDef,
  unknown
> = z.object({
  data: VpnSessionDataWithPassword$zodSchema.optional(),
});
